### ISSUE TITLE
Automatically click use here when switching systems

### ISSUE THREAD

**Issue by smashah** [smashah/sulla#1]
Scenario:
Develop on macbook => scan qr code
Deploy on server => scan qr code
Develop on macbook => Gets stuck on qr code, need to delete sessions, scan qr code
Deploy on server => Gets stuck on qr code, need to delete sessions, scan qr code

[Example](https://i.stack.imgur.com/lfOI3.png)

**Comment by smashah** [comment]
some work done here:
88073c5ca6e1825f77589e8c0abd27f196b17000

**Comment by lookprintufc** [comment]
How can I use it?

**Comment by smashah** [comment]
@lookprintufc it's not really done yet

**Comment by smashah** [comment]
#66 related

**Comment by smashah** [comment]
https://github.com/smashah/sulla/issues/69#issuecomment-578830306
