### ISSUE TITLE
Can't send large images

### ISSUE THREAD

**Issue by OmarAttia** [smashah/sulla#10]
I can send media without problems but when it comes to an image > 200k it fails not errors caught nothing

**Comment by smashah** [comment]
@OmarAttia this would explain the massive amount of compression a picture shared via WhatsApp undergoes. You'll need to compress the image to under 200Kb in that case.

**Comment by smashah** [comment]
@OmarAttia it would be really helpful if you share your compression implementation, thanks.

**Comment by OmarAttia** [comment]
Convert to webp and resize to max-width 1280px and max-height 720. works like charm.
