### ISSUE TITLE
not able send message to new contact number which is saved in device but not initiated whats app chat yet

### ISSUE THREAD

**Issue by jigipatel** [smashah/sulla#101]
Hello,
i'm not able send message to new contact number which is saved in my device but i have not initiated whats app chat yet.

i need your help will you please suggest some solution how it will be achieved.
Thank You.

**Comment by arturromaorocha** [comment]
É necessário ter iniciado uma conversa anteriormente com o contato. PT-BR 
 
You must have started a conversation with the contact previously. PT-BR

**Comment by smashah** [comment]
Duplicate #89
