### ISSUE TITLE
after logout from mobile device qr code not generating

### ISSUE THREAD

**Issue by jigipatel** [smashah/sulla#102]
Hello,
I want to recreate qr code when user logout from mobile device or conflict occurs but not able to do that. i have also called client.forceRefocus() on CONFLICT and UNPAIRED onStateChanged callback.
please help me to solve this issue.

Thank You.

**Comment by smashah** [comment]
Force refocus will only work on conflict. On unpaired, run client kill then create it again

**Comment by smashah** [comment]
Closing for now thanks
