### ISSUE TITLE
Throw error in TOS_BLOCKed

### ISSUE THREAD

**Issue by haroldorodsilva** [smashah/sulla#103]
I am testing the killtimer and after some time without scan the qr-code I receive the TOS_BLOCKed.
```
Seems as though you have been TOS_BLOCKed, unable to refresh QR Code. Please see https://github.com/smashah/sulla#best-practice for information on how to prevent this from happeing. You will most likely not 
get a QR Code
```
@smashah Could you get the messages of error and put inside a error to be possible we catch later?

**Comment by smashah** [comment]
@haroldorodsilva I think that would get annoying for some people but maybe I can make `throwErrorOnTosBlock:true` an option

**Comment by haroldorodsilva** [comment]
Thanks

**Comment by smashah** [comment]
@haroldorodsilva implemented in v.1.7.8

try this:
https://github.com/smashah/sulla/blob/4b4a0c92f84c592899cdbf68c2b33d8f40328938/demo/index.ts#L122

**Comment by haroldorodsilva** [comment]
@smashah I tried but the error don't pass throw catch. See below my code.

Initializing whatsapp
Debug Info { WA_VERSION: 'I think you have been TOS_BLOCKed',
  PAGE_UA:
   'WhatsApp/0.4.607 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36',
  SULLA_HOTFIX_VERSION: '1.7.10',
  BROWSER_VERSION: 'HeadlessChrome/79.0.3945.0' }    
Possilby TOS_BLOCKed
i Authenticate to continue
√ Loading QR

Seems as though you have been TOS_BLOCKed, unable to 
refresh QR Code. Please see https://github.com/smashah/sulla#best-practice for information on how to prevent this from happeing. You will most likely not get a QR Code
(node:14340) UnhandledPromiseRejectionWarning: Error: TOSBLOCK

The code:
    const puppeteerConfigOverride = {
      throwErrorOnTosBlock: true,
      killTimer: 60,
      autoRefresh: true,
      qrRefreshS: 15,
    };

    await create('session', puppeteerConfigOverride)
      .then(async client => {
        this.client = client;
        await this.registerEvents(this.client);
      })
      .catch(e => {
        console.log('here the error: ', e.message);
      });

**Comment by rafael-sarti** [comment]
I have the same problem :(

**Comment by smashah** [comment]
@haroldorodsilva @rafael-sarti 

due to the fact that you have qr refresh on, the error shows up after the last qrLoop is finished. I'll change it so it throws on the first detection.

**Comment by smashah** [comment]
New change is live in v1.7.13

thanks
