### ISSUE TITLE
Module not found: Can't resolve 'ws' in React js

### ISSUE THREAD

**Issue by amajai** [smashah/sulla#105]
I keep getting this error when I try to import sulla library on react js.

`
./node_modules/puppeteer/lib/WebSocketTransport.js
Module not found: Can't resolve 'ws' in 'D:\project_folder\node_modules\puppeteer\lib'
`

 How can I resolve it please?

**Comment by gnadelwartz** [comment]
I know react.js as a framework running in a browser, do you really want to run chrome (puppeteer) inside a browser?

**Comment by amajai** [comment]
@gnadelwartz Oh, so pupperteer wouldnt work with react.js since its already in a browser or its not recommended? I was planning to create a web app built with the sulla library as a small project.

**Comment by gnadelwartz** [comment]
puppeteer is not running in a browser its a full-blown chrome browser and cannot run inside an other browser. im not a specialist for react.js but to use sulla / puppeteer from a ract.js app you may need a separate server process running sulla/puppeteer communicating with you react.js app.

https://stackoverflow.com/questions/55031823/how-to-make-puppeteer-work-with-a-reactjs-application-on-the-client-side

**Comment by smashah** [comment]
Yes please do not run this in a front end app. Not worth the headache.

**Comment by amajai** [comment]
@gnadelwartz Thanks for the explanation, I was not aware that puppeteer itself was actually a browser. I'll try out the client method and see.

@smashah Unfortunately it was too late for me lol. Had serious headache trying to make it work on the frontend. But, Im glad I posted my issue.
