### ISSUE TITLE
how to send picture from folder to whatsapp contact

### ISSUE THREAD

**Issue by xshion13** [smashah/sulla#106]
Anyone can teach me exactly how to send images, i look on demo but i can't understand each part of the code.

sorry i'm noob yet ^^'  i need to understand the sintaxis of this:

```
    client.onMessage(message => {
// /home/sullaproj/misc/images/Image.jpg
        if (message.body === 'Image') {
            client.sendFile(message.from, '/home/sullaproj/misc/images/Image.jpg', 'Hello this is the caption');
        }
```

![image](https://user-images.githubusercontent.com/56605018/74201067-99c52300-4c36-11ea-8710-494808e933e5.png)

**Comment by smashah** [comment]
@xshion13 

```
        const image = await utils.getFileInBase64('./image.jpg');
        await client.sendImage(
          message.from,
          String(image),
          'image.jpg',
          `Try to send image`
        );
      }
```

image.jpg has to be in the same direcgtory as your app.

**Comment by xshion13** [comment]
> @xshion13
> 
> ```
>         const image = await utils.getFileInBase64('./image.jpg');
>         await client.sendImage(
>           message.from,
>           String(image),
>           'image.jpg',
>           `Try to send image`
>         );
>       }
> ```
> 
> image.jpg has to be in the same directory as your app.

hi dear, is this still working? i am having issues importing "utils" ,,, update the demo with image convertion from folder pleasee
![image](https://user-images.githubusercontent.com/56605018/77235425-8a18f280-6b83-11ea-97d8-261b72a810f6.png)
