### ISSUE TITLE
TOS_Blocked failed

### ISSUE THREAD

**Issue by rafael-sarti** [smashah/sulla#107]
![Captura de Tela 2020-02-10 às 11 52 03 PM](https://user-images.githubusercontent.com/59804684/74208030-b2e2c980-4c60-11ea-91fc-5bdadcbeef4c.png)

The error has been pointing out as a possible block, it happens that the browser arrives to login. When it arrives at "The session is invalid" it is the time that the session is verified.

I realized that when checking the validity of the session that starts generating this error.

**Comment by rafael-sarti** [comment]
It is not a block because it is on a new server, with a new ip number. Locally works normally the script is some problem that is occurring in LINUX (Ubuntu) again :(

**Comment by smashah** [comment]
@rafael-sarti try using the PAGE_UA as the custom ua but change 0.4.607 to 0.4.613, delete the session folder then try again.

**Comment by smashah** [comment]
Duplicate #108
