### ISSUE TITLE
TOS_BLOCKed after authentication

### ISSUE THREAD

**Issue by mmc16** [smashah/sulla#108]
**Describe the bug**
Then again I am running into the same problem. Everything was working fine until now, when I started getting blocked again. I updated sulla and cleaned the session data, tried other UAs, etc. Even tried the default one.

btw, is there a way to know or at least guess when one is going to be blocked? 

**Steps to Reproduce**
1. `sulla.create(...)`
2. read the QRCode
3. TOS_BLOCKed

**create() code**
This is the code you use to create the client. e.g
```javascript
UA = "WhatsApp/0.4.613 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36";
sulla.create(sessionName,{}, UA);
```

**Expected behavior**
Don't get blocked...

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
 Initializing whatsapp
Debug Info {
  WA_VERSION: '0.4.613',
  PAGE_UA: 'WhatsApp/0.4.613 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36',
  SULLA_HOTFIX_VERSION: '1.7.10',
  BROWSER_VERSION: 'HeadlessChrome/79.0.3945.0'
}
ℹ Authenticate to continue
✔ Loading QR
 
[QRcode]

✔ Authenticating
✖ The session is invalid. Retrying
✔ Initializing whatsapp
Debug Info {
  WA_VERSION: 'I think you have been TOS_BLOCKed',
  PAGE_UA: 'WhatsApp/0.4.613 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36',
  SULLA_HOTFIX_VERSION: '1.7.10',
  BROWSER_VERSION: 'HeadlessChrome/79.0.3945.0'
}
Possilby TOS_BLOCKed
ℹ Authenticate to continue
✔ Loading QR

```

**Host (please complete the following information):**
 - OS: 5.3.18-1-MANJARO

**Additional context**
EDIT: when I run with `headless: false`, I don't get blocked

**Comment by gnadelwartz** [comment]
https://github.com/smashah/sulla/issues/110#issuecomment-584817587 did you try this solution?

**Comment by smashah** [comment]
more discussion of this on #110. Closing.
