### ISSUE TITLE
TOS BLOCKed problem at start session

### ISSUE THREAD

**Issue by ricardopereyra** [smashah/sulla#109]
**Describe the bug**
TOS_BLOCKed

**Steps to Reproduce**
1. npm start
2. See error

**create() code**
This is the code you use to create the client. e.g
```javascript
// Make an custom user agent
const uaOverride = "Opera/9.80 (iPhone; Opera Mini/8.0.0/34.2336; U; en) Presto/2.8.119 Version/11.10";

// Creating an sulla component and start it
create('session',
{
  executablePath: '/usr/bin/google-chrome', // Path para chrome en ubuntu
  headless: false,
  autoRefresh: false,
  qrRefreshS: 30 //please note that if this is too long then your qr code scan may end up being invalid. Generally qr codes expire every 15 seconds.
},
uaOverride
)
// create()
.then(async client => await start(client));
```

**Expected behavior**
Do not get blocked

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info { WA_VERSION: 'I think you have been TOS_BLOCKed',
  PAGE_UA:
   'Opera/9.80 (iPhone; Opera Mini/8.0.0/34.2336; U; en) Presto/2.8.119 Version/11.10',
  SULLA_HOTFIX_VERSION: '1.7.10',
  BROWSER_VERSION: 'Chrome/79.0.3945.130' }
Possilby TOS_BLOCKed
```

**Screenshots**
If applicable, add screenshots to help explain your problem. Use ```headless: false``` to get screenshots
![image](https://user-images.githubusercontent.com/13365955/74238523-bd2eb300-4cb4-11ea-9dcc-1b6697fae354.png)

**Host (please complete the following information):**
 - OS: Ubuntu 18.04.3 LTS

**Additional context**
- I did try using other custom user agents
- This error appeaars whit sulla-hotfix v1.7.5, and then I update it to 1.7.10, but problem persist
- I did try using google-chrome instance and chromium, but error persist

**Comment by smashah** [comment]
What makes you think a mobile opera UA is going to work at all with WhatsApp web? Thanks for filling out the template properly. Did you try deleting the session folder between attempts? Closing because duplicate #108

**Comment by ricardopereyra** [comment]
Thanks! I change the custom user agent to Mozilla Firefox for Windows, delete de session folder, and now it works.
