### ISSUE TITLE
TOS_BLOCK

### ISSUE THREAD

**Issue by algoz098** [smashah/sulla#110]
**Describe the bug**
My Headless sulla are being tos_blocked, tried new IP, computer, its always blocked

**Steps to Reproduce**
1. sulla.create() with headless true
2. scan qr code
3. tos_blocked

**create() code**
This is the code you use to create the client. e.g
```javascript

	let options = {
		headless: !dev,
		autoRefresh: true,
		qrRefreshS:20
	}

	global.generatedUa = 'WhatsApp/0.4.613 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36'

	global.sender = await sulla.create(session, options);
```

**Expected behavior**
A way to create a new UA so it doesnt get tos blocked

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
  WA_VERSION: 'I think you have been TOS_BLOCKed',
  PAGE_UA: 'WhatsApp/0.4.607 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36',
  SULLA_HOTFIX_VERSION: '1.7.5',
  BROWSER_VERSION: 'HeadlessChrome/79.0.3945.0'
}

Debug Info {
  WA_VERSION: '0.4.613',
  PAGE_UA: 'WhatsApp/0.4.607 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36',
  SULLA_HOTFIX_VERSION: '1.7.5',
  BROWSER_VERSION: 'HeadlessChrome/79.0.3945.0'
}
```

**Host (please complete the following information):**
 - OS: Ubuntu 18.04, Mac OS Catalina

**Comment by arturromaorocha** [comment]
![image](https://user-images.githubusercontent.com/11146355/74256443-b9f1f200-4cc9-11ea-8f24-d4cf4e6538b0.png)
I tried, but it didn't work.

**Comment by algoz098** [comment]
I have fixed this with those steps

So steps:
1 - erase yarn.lock, package-lock.json, node_modules
2 - run npm cache clean --force
3 - reinstall dependencies npm i 

Something on the npm cache system was the problem.

**Comment by CardosoGit** [comment]
@algoz098 Your solution worked for me.

**Comment by arturromaorocha** [comment]
Funcionou para mim também - PT-BR

**Comment by rafael-sarti** [comment]
Resolved here =) tks! ;)

**Comment by UnKnoWn-Consortium** [comment]
> I have fixed this with those steps
> 
> So steps:
> 1 - erase yarn.lock, package-lock.json, node_modules
> 2 - run npm cache clean --force
> 3 - reinstall dependencies npm i
> 
> Something on the npm cache system was the problem.
> 
> Can someone else test and comment here? Would be usefull for the future

It does not work for me. I have finally solved this TOS_BLOCKed issue by using XVFB and enabling `headless: false`....

**Comment by algoz098** [comment]
I have some information, some time after i got tos blocked aggain, in those case headles false was too. I have to open developer tools, and clear site data in application tab.

That solved for me.

**Comment by arturromaorocha** [comment]
XVFB  ?

**Comment by arturromaorocha** [comment]
> I have some information, some time after i got tos blocked aggain, in those case headles false was too. I have to open developer tools, and clear site data in application tab.
> 
> That solved for me.

 Parou de Funcionar para mim 9h pt-br
Stopped working for me 9am

**Comment by UnKnoWn-Consortium** [comment]
> XVFB ?

I am running Sulla on a Ubuntu VPS. Obviously it does not have a display. So for Chromium or Chrome to run in headful mode, I have to fake one. And Xvfb does exactly that.

**Comment by smashah** [comment]
Hey all, can you try the demo code with the latest version 1.7.12

https://github.com/smashah/sulla/blob/ec4963f9948689e86e0ed0ca3d6b7b250ca9f765/demo/index.ts#L118

Thanks

**Comment by arturromaorocha** [comment]
> Hey all, can you try the demo code with the latest version 1.7.12
> 
> https://github.com/smashah/sulla/blob/ec4963f9948689e86e0ed0ca3d6b7b250ca9f765/demo/index.ts#L118
> 
> Thanks

![image](https://user-images.githubusercontent.com/11146355/74400669-07b74900-4df5-11ea-8b77-2c7f732234ca.png)
Success! Thanks.

**Comment by algoz098** [comment]
I`m testing it all out.
I think i found somethings so, will return in a couple days. Or when something new happen!

Thanks for now

**Comment by alishahlakhani** [comment]
I seem to getting this issue too.
```
Seems as though you have been TOS_BLOCKed, unable to refresh QR Code. Please see https://github.com/smashah/sulla#best-practice for information on how to prevent this from happeing. You will most likely not get a QR Code
(node:91649) UnhandledPromiseRejectionWarning: Error: TOSBLOCK
    at Object.<anonymous> (/Users/alakhani/Documents/Codes/Personal/whatsapp-bot-using-sulla/app/node_modules/sulla-hotfix/dist/controllers/auth.js:99:35)
    at step (/Users/alakhani/Documents/Codes/Personal/whatsapp-bot-using-sulla/app/node_modules/sulla-hotfix/dist/controllers/auth.js:33:23)
    at Object.next (/Users/alakhani/Documents/Codes/Personal/whatsapp-bot-using-sulla/app/node_modules/sulla-hotfix/dist/controllers/auth.js:14:53)
    at fulfilled (/Users/alakhani/Documents/Codes/Personal/whatsapp-bot-using-sulla/app/node_modules/sulla-hotfix/dist/controllers/auth.js:5:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:91649) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:91649) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by e0xify** [comment]
same issue for me, still TOS blocked

**Comment by smashah** [comment]
@e0xify @alishahlakhani can you share your debug info please and any other relevant details.

**Comment by e0xify** [comment]
`/home/shell/npm# node test.js                                                                                                                                                                      
✔ Initializing whatsapp
Debug Info {                                                                                                                                                                                                       
  WA_VERSION: 'I think you have been TOS_BLOCKed',
  PAGE_UA: 'Mozilla/5.0 (Windows NT 6.1; WOW64; rv:54.0) Gecko/20100101 Firefox/73.0',
  SULLA_HOTFIX_VERSION: '1.7.13',
  BROWSER_VERSION: 'HeadlessChrome/80.0.3987.100'
}                                                                                                                                                                                                                  
Error: TOSBLOCK                                                                                                                                                                                                    
    at Object.<anonymous> (/home/shell/npm/node_modules/sulla-hotfix/dist/controllers/initializer.js:97:31)
    at step (/home/shell/npm/node_modules/sulla-hotfix/dist/controllers/initializer.js:33:23)
    at Object.next (/home/shell/npm/node_modules/sulla-hotfix/dist/controllers/initializer.js:14:53)
    at fulfilled (/home/shell/npm/node_modules/sulla-hotfix/dist/controllers/initializer.js:5:58)
    at runMicrotasks (<anonymous>)                                                                                                                                                                                 
    at processTicksAndRejections (internal/process/task_queues.js:93:5)`


`const sulla = require('sulla-hotfix');                                                                                                                                                                             
const uAOverride = "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:54.0) Gecko/20100101 Firefox/73.0";                                                                                                                     
sulla.create('session',                                                                                                                                                                                            
                                                                                                                                                                                                                   
{                                                                                                                                                                                                                  
                                                                                                                                                                                                                   
  executablePath: '/usr/bin/google-chrome',                                                                                                                                                                        
                                                                                                                                                                                                                   
  headless: true,                                                                                                                                                                                                  
                                                                                                                                                                                                                   
  throwErrorOnTosBlock:true,                                                                                                                                                                                       
                                                                                                                                                                                                                   
  killTimer:40,                                                                                                                                                                                                    
                                                                                                                                                                                                                   
  autoRefresh:true, //default to true                                                                                                                                                                              
                                                                                                                                                                                                                   
  qrRefreshS:15, //please note that if this is too long then your qr code scan may end up being invalid. Generally qr codes expire every 15 seconds.                                                               
                                                                                                                                                                                                                   
  cacheEnabled:true,                                                                                                                                                                                               
                                                                                                                                                                                                                   
  //example chrome args. THIS MAY BREAK YOUR APP !!!ONLY FOR TESTING FOR NOW!!!.                                                                                                                                   
                                                                                                                                                                                                                   
  chromiumArgs:[                                                                                                                                                                                                   
                                                                                                                                                                                                                   
    '--aggressive-cache-discard',                                                                                                                                                                                  
                                                                                                                                                                                                                   
    '--disable-cache',                                                                                                                                                                                             
                                                                                                                                                                                                                   
    '--disable-application-cache',                                                                                                                                                                                 
                                                                                                                                                                                                                   
    '--disable-offline-load-stale-cache',                                                                                                                                                                          
                                                                                                                                                                                                                   
    '--disk-cache-size=0'                                                                                                                                                                                          
                                                                                                                                                                                                                   
  ]                                                                                                                                                                                                                
                                                                                                                                                                                                                   
},                                                                                                                                                                                                                 
uAOverride                                                                                                                                                                                                         
                                                                                                                                                                                                                   
)                                                                                                                                                                                                                  
                                                                                                                                                                                                                   
// create()                                                                                                                                                                                                        
                                                                                                                                                                                                                   
.then(async client => await start(client))                                                                                                                                                                         
                                                                                                                                                                                                                   
.catch(e=>{                                                                                                                                                                                                        
                                                                                                                                                                                                                   
  console.log(e);                                                                                                                                                                                                  
                                                                                                                                                                                                                   
  // process.exit();                                                                                                                                                                                               
                                                                                                                                                                                                                   
}); `

**Comment by e0xify** [comment]
tried changing cache, custom UA...still blocked.
first auth works when deleting the session folder, 

tried new install aswell by cleaning all the npm modules

**Comment by smashah** [comment]
Have you tried 

```
 create()                                                                                                                                                                                                                                                                                                                                                                                                                         
.then(async client => await start(client))                                                                                                                                                                                                                                                                                                                                                                                     
.catch(e=>{                                                                                                                                                                                                                                                                                                                                                                                                                       
  console.log(e);                                                                                                                                                                                                                                                                                                                                                                                                               
  process.exit();                                                                                                                                                                                                                                                                                                                                                                                                            
}); 
```

**Comment by e0xify** [comment]
yep, jumps into tosblocked exception and quits :/

**Comment by haroldorodsilva** [comment]
I deleted the session files and managed to authenticate several times. Now I received the TOS_BLOCK and when placing headless: false I caught the problem of chrome asking to update.
![Screenshot_1](https://user-images.githubusercontent.com/15693100/74567360-fcc2fc80-4f4b-11ea-87a7-4668b15b3ca7.png)

**Comment by smashah** [comment]
Hi all,

Some progress on TOS_BLOCK. Thus far I have been operating under the assumption that TOS_BLOCK screen is shown based on a SSR response to the web.whatsapp.com request.

This is not true. I found this out by implementing a request interceptor for #126 . When already TOS blocked, the browser makes 0 actual calls over the network. This means that the browser session is branded as TOS_BLOCK and then only shows you the screen after a new session is started from the cache/sw.

How to get passed TOS_BLOCK screen in browser:
1. Unregister the service worker
2. Refresh the page.

This is good news and bad news. This can be implemented in the code however, if you had a valid session before, you will have to rescan the QR code to log in.

**Comment by haroldorodsilva** [comment]
Someone can try using this?

```
      chromiumArgs: [
        '--disable-background-timer-throttling',
        '--disable-backgrounding-occluded-windows',
        '--disable-breakpad',
        '--disable-component-extensions-with-background-pages',
        '--disable-dev-shm-usage',
        '--disable-extensions',
        '--disable-features=TranslateUI,BlinkGenPropertyTrees',
        '--disable-ipc-flooding-protection',
        '--disable-renderer-backgrounding',
        '--enable-features=NetworkService,NetworkServiceInProcess',
        '--force-color-profile=srgb',
        '--hide-scrollbars',
        '--metrics-recording-only',
        '--mute-audio',
        '--headless',
        '--no-sandbox',
      ],
```

**Comment by jesusvalverde** [comment]
Debug Info { WA_VERSION: '0.4.930',
  PAGE_UA: 'WhatsApp/0.4.613 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36',
  SULLA_HOTFIX_VERSION: '1.7.24',
  BROWSER_VERSION: 'HeadlessChrome/79.0.3945.0' }

Solved my TOS_BLOCKed just deleting all qr-sesion and them all goes as usual.

**Comment by joweste** [comment]
Please what is TOS_Blocked? Can someone give me a quick explanation?

**Comment by itzharDev** [comment]
no matter which UserAgent I'm using or override  executablePath, I'm always getting  TOS_BLOCK problem.
if someone can fix it for me, ill pay
itzhar.dev@gmail.com

**Comment by joweste** [comment]
Do you have teamviewer? Can I see If I can help you?

**Comment by joweste** [comment]
I need TV <=10

**Comment by itzharDev** [comment]
@joweste  yes. contact me by mail

**Comment by smashah** [comment]
![image](https://user-images.githubusercontent.com/5903821/75717638-69b6f000-5cc9-11ea-8515-4f36a180fc8e.png)

**Comment by smashah** [comment]
EVERYONE, please report back if this issue is fixed for you with latest version.

Thanks

**Comment by JoeDozan24** [comment]
About that "Update Google Chrome"..
I found "something" that can bypass it but it's still manually
perhaps someone can done this via codes?

![image](https://user-images.githubusercontent.com/58735845/75752662-c531be00-5d5b-11ea-882c-dc87c4f4ef5e.png)

Click the `Unregister` and refresh the page without `Shift + F5` and it's ready to go

**Comment by e0xify** [comment]
@smashah confirmed working 1.8.0

**Comment by smashah** [comment]
Great thanks @e0xify.

@JoeDozan24 please follow e0xify's instructions and try again.

Closing.
