### ISSUE TITLE
Can't send message to any number which isn't in the "old" message list already.

### ISSUE THREAD

**Issue by alishahlakhani** [smashah/sulla#112]
Version numbers
**Sulla:** 1.7.10

**Describe the bug**
Sulla cannot create a new message if number hasn't sent a message to the phone number before.

**Steps to Reproduce**
1. Send a message to new number whom you have not yet communicated with
2. Sulla will say it has sent message but it doesn't send.

**create() code**
This is the code you use to create the client. e.g
```javascript
this.client?.sendText(
            to,
            message
        ).then(e => {
            this.log(`Message dispatched to ${to}`, message);
        }).catch(e => {
            this.logger.error(`Message FAILED to dispatch to ${to}`, message);
        });
```

This code returns in '.then' block however the message is never sent.

**Expected behaviour**
If the number is not in the list of 'old' messages then sulla should create a new chat for that number and send message.

**DEBUG INFO**
```
Debug Info { 
WA_VERSION: '0.4.613',
  PAGE_UA:
   'WhatsApp/0.4.607 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36',
  SULLA_HOTFIX_VERSION: '1.7.10',
  BROWSER_VERSION: 'Chrome/79.0.3945.0' }
```

**Screenshots**
### This is how it looks before sending a message
<img width="1199" alt="before" src="https://user-images.githubusercontent.com/12266036/74309561-f98e0c00-4da5-11ea-8035-9bf04dab5cef.png">

### This is how it looks after message is sent
<img width="1199" alt="after" src="https://user-images.githubusercontent.com/12266036/74309596-1296bd00-4da6-11ea-95b2-baf8501b23ae.png">

### This is how it should look
<img width="1199" alt="actual" src="https://user-images.githubusercontent.com/12266036/74309611-1aeef800-4da6-11ea-9ee2-3d079de1fad7.png">

**Host (please complete the following information):**
 - Mac OSX

**Additional context**

**Comment by alishahlakhani** [comment]
Possibly duplicate of #6

I am okay to close this. I'd rather respect the privacy and choice of people and ask them to initiate conversation first rather than spamming them even if they didn't subscribe willingly.

**Comment by gnadelwartz** [comment]
maybe @smashah should mention this in the send message example in readme.md

**Comment by alishahlakhani** [comment]
Yes I agree. I read #6 and I kinda agree with the explanation there. We all hate annoying spammy ads. Plus I'm not building an ad engine anyways.

**Comment by gnadelwartz** [comment]
depending on your use case you can place an  invite link so new users can establish a contact to you 

https://faq.whatsapp.com/en/26000030/

**Comment by alishahlakhani** [comment]
Yeah I will most probably be sending a "Click to chat" link. 
Should I just go ahead and close this thread?
Thanks.

**Comment by smashah** [comment]
@alishahlakhani I'll move this to a readme update then close this.

Regarding starting a chat, I made a simple webcomponent you can add to your site to get users to start chats.

https://github.com/smashah/whatsapp-button

**Comment by alishahlakhani** [comment]
@smashah Thanks will look into it.
Keep rocking!
