### ISSUE TITLE
How to read old messages

### ISSUE THREAD

**Issue by joweste** [smashah/sulla#115]
Hi, I need to read the an amount of latest messages from a chat.
This amount can be 50 for sample.
These messages can be new or old. 
I rave trying some samples posted here  as:
loadAndGetAllMessagesInChat, loadEarlierMessagesTillDate, loadAllEarlierMessages ans similares, but
nothing is working.
Is it possible? 
Does someone could post a sample?

**Comment by mmc16** [comment]
Ei, tente descrever o problema com mais detalhes em português, muitos de nós aqui somos brasileiros. Veja no arquivo API/whatsapp.ts, lá estão todas as funções que a api oferece. O loadAndGetAllMessagesInChat deveria resolver o seu problema

**Comment by rfscheidt** [comment]
Tenho a mesma demanda, porém o método loadAndGetAllMessagesInChat é bem lento, tenho 40k contatos no telefone, ficou inviável. O método que lê mensagens não lidas é mais eficiente.

**Comment by smashah** [comment]
Hey all, can you please add translations to your comments.

I don't think there's any way to do this other than loading all messages which takes some time. 

Thanks

**Comment by joweste** [comment]
> Ei, tente descrever o problema com mais detalhes em português, muitos de nós aqui somos brasileiros. Veja no arquivo API/whatsapp.ts, lá estão todas as funções que a api oferece. O loadAndGetAllMessagesInChat deveria resolver o seu problema

Oi, nao resolve, eu estou tendo randomicos erros como esse aqui:
F:\Programas\SWNodeWhats\src\web\SWapi.js:655 Uncaught (in promise) TypeError: Cannot read property 'msgs' of undefined TypeError: Cannot read property 'msgs' of undefined
    at x (F:\Programas\SWNodeWhats\src\web\SWapi.js:654)
    at Object.window.WAPI.loadAllEarlierMessages (F:\Programas\SWNodeWhats\src\web\SWapi.js:660)
    at Object.window.WAPI.loadAndGetAllMessagesInChat (F:\Programas\SWNodeWhats\src\web\SWapi.js:912)
    at <anonymous>:1:46
    at <anonymous>:2:3
x @ F:\Programas\SWNodeWhats\src\web\SWapi.js:654
window.WAPI.loadAllEarlierMessages @ F:\Programas\SWNodeWhats\src\web\SWapi.js:660
window.WAPI.loadAndGetAllMessagesInChat @ F:\Programas\SWNodeWhats\src\web\SWapi.js:912
(anonymous) @ VM1364:1
(anonymous) @ VM1364:2
F:\Programas\SWNodeWhats\src\web\SWapi.js:654 Uncaught (in promise) TypeError: Cannot read property 'msgs' of undefined
    at x (F:\Programas\SWNodeWhats\src\web\SWapi.js:654)
    at Object.window.WAPI.loadAllEarlierMessages (F:\Programas\SWNodeWhats\src\web\SWapi.js:660)
    at Object.window.WAPI.loadAndGetAllMessagesInChat (F:\Programas\SWNodeWhats\src\web\SWapi.js:912)
    at <anonymous>:1:46
    at <anonymous>:2:3
x @ F:\Programas\SWNodeWhats\src\web\SWapi.js:654
window.WAPI.loadAllEarlierMessages @ F:\Programas\SWNodeWhats\src\web\SWapi.js:660
window.WAPI.loadAndGetAllMessagesInChat @ F:\Programas\SWNodeWhats\src\web\SWapi.js:912
(anonymous) @ VM1364:1
(anonymous) @ VM1364:2
