### ISSUE TITLE
Error: Evaluation failed: ReferenceError: funcName is not defined

### ISSUE THREAD

**Issue by WangZhiYao** [smashah/sulla#117]
**Describe the bug**
When setting a use for `onParticipantsChanged` event it doesnt work and throw a error while loading the api

**Steps to Reproduce**
1. Setup the sulla-hotfix
2. Add a event callback for the funcion `onParticipantsChanged`
3. Scan the QR code

**create() code**
This is the code you use to create the client. e.g
```javascript
sullaHotfix.create().then(client => start(client));
```

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
    WA_VERSION: '0.4.613',
    PAGE_UA: 'WhatsApp/0.4.613 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36',
    SULLA_HOTFIX_VERSION: '1.7.12',
    BROWSER_VERSION: 'HeadlessChrome/79.0.3945.0'
}
```

**Screenshots**
![](https://user-images.githubusercontent.com/8477509/74437394-00e70f80-4ea3-11ea-82c2-4ce68df1e152.png)

**Host (please complete the following information):**
 - OS: Ubuntu 18.04 LTS

**Comment by smashah** [comment]
fix should be live in v1.7.13

**Comment by WangZhiYao** [comment]
@smashah thanks, no errors printed on the log now, but I still cannot receive the event when someone add the group by link

**Comment by smashah** [comment]
@WangZhiYao I added the invite subtype in v1.7.14. Let me know if it works.

Thanks

**Comment by WangZhiYao** [comment]
@smashah thanks for your help, I just test it again and now invite is worked but add & remove by admin still not works

**Comment by smashah** [comment]
@WangZhiYao I've tested all three and can confirm they are working as expected. Is the admin you are talking about the same as the phone being used with this library?

**Comment by WangZhiYao** [comment]
@smashah yes, the phone being used with this library is the admin, and I add participants by this account but quit the group voluntarily

**Comment by smashah** [comment]
Umm you can't receive updates if you quit the group @WangZhiYao

**Comment by WangZhiYao** [comment]
@smashah I tested it again, and now I can receive events of the add and remove participants using the admin account, but I still can’t receive events for participants quit the group voluntarily.

**Comment by smashah** [comment]
Oh right. I'll have a look at it tonight.

**Comment by smashah** [comment]
@WangZhiYao Should be live in v1.7.15

**Comment by smashah** [comment]
I've tested add, remove, leave and invite. They are all working now.

Thanks.
