### ISSUE TITLE
ReferenceError: WAPI is not defined

### ISSUE THREAD

**Issue by OmarAttia** [smashah/sulla#12]
ReferenceError: WAPI is not defined error thrown while sending and receiving is dead

**Comment by Marguelgtz** [comment]
@OmarAttia Getting the same error as of today, Looking into it 👀  haven't found anything yet🤕 . @smashah any ideas?

**Comment by OmarAttia** [comment]
I guess it's puppeteer related issue

**Comment by Marguelgtz** [comment]
not sure, used it a couple days ago w/out problems. Puppeteer is opening whatsapp web and authenticating correctly however most of the methods on the package fail throwing out this error. I'm thinking it may have something to do with **whatsapp web** page

**Comment by OmarAttia** [comment]
window.Store.ChatClass.default.prototype.sendMessage = function (e) {
return window.Store.SendTextMsgToChat(this, ...arguments);
}

Line 62 wapi.js

the problem lies here

**Comment by phantom-limb** [comment]
> window.Store.ChatClass.default.prototype.sendMessage = function (e) {
> return window.Store.SendTextMsgToChat(this, ...arguments);
> }
> 
> Line 62 wapi.js
> 
> the problem lies here

Yeah. I fix here.

**Comment by OmarAttia** [comment]
window.Store.ChatClass is undefined!
@phantom-limb post the fix then

**Comment by Marguelgtz** [comment]
> > window.Store.ChatClass.default.prototype.sendMessage = function (e) {
> > return window.Store.SendTextMsgToChat(this, ...arguments);
> > }
> > Line 62 wapi.js
> > the problem lies here
> 
> Yeah. I fix here.

@phantom-limb how?

**Comment by phantom-limb** [comment]
I disabled sending function.

**Comment by OmarAttia** [comment]
LOL

**Comment by Marguelgtz** [comment]
> I disabled sending function.

There isn't a better solution than ignoring the problem it seems 🤦‍♂

@OmarAttia any luck?

**Comment by OmarAttia** [comment]
in progress

**Comment by Marguelgtz** [comment]
> in progress

@OmarAttia how are you trying to approach it, maybe I can also jump in and try to find a solution too. At this point I don't really know what else to look for

**Comment by OmarAttia** [comment]
we need to redefine window.Store.Chat

**Comment by smashah** [comment]
@OmarAttia  can you make a pr with the fix?

**Comment by OmarAttia** [comment]
Sure, as soon as I finish

**Comment by smashah** [comment]
In meantime here is another discussion of this issue on the source of wapi.js https://github.com/mukulhase/WebWhatsapp-Wrapper/issues/754

**Comment by OmarAttia** [comment]
@smashah thnx very much

**Comment by smashah** [comment]
Have a few mins with the laptop, will push a new version in around 5 mins. Thanks all for your help and bringing up the issue.

**Comment by smashah** [comment]
Pushed a new v. 1.2.9 to npm. Please update and test it out. Thanks, everyone!
