### ISSUE TITLE
Add puppeteer-extra-plugin-devtools

### ISSUE THREAD

**Issue by algoz098** [smashah/sulla#122]
This lib allow to remote access to a puppeteer, would be nice to have a flag on sulla to enable this so we can debug better.

https://www.npmjs.com/package/puppeteer-extra-plugin-devtools

**Comment by smashah** [comment]
Just FYI, localtunnel is resulting in many errors:

`tunnel server offline: Request failed with status code 502, retry 1s`

This may be a temporary issue with localtunnels servers but untill it's resolved this will only return the local devtools url.

The best solution to this would be for someone to make a PR plugin-devtools to enable a fallback to ngrok or provide some sort of error handling on request failures. Unfortunately it just keeps retrying indefinitely.

**Comment by smashah** [comment]
@algoz098 live in v.1.7.14 to use add the following to the config object.

```javascript
  devtools:true,
  //OR
  // devtools:{
  //   user:'admin',
  //   pass:'root'
  // },
```
