### ISSUE TITLE
WAPI.deleteMessage not working

### ISSUE THREAD

**Issue by joweste** [smashah/sulla#124]
Hi there,
I am trying to delete a message.
I am using 
`WAPI.deleteMessage ("5521...@c.us",my_msg, false);`

The function returns true.
Next, I use `WAPI.getAllMessagesInChat ("5521...@c.us",.....`
And the message just deleted continues appearing in the return list of messages

**Comment by smashah** [comment]
Are you sure my_msg is a message if string? If you sent the message you need to set the last param to true iirc

**Comment by joweste** [comment]
> Are you sure my_msg is a message id string? If you sent the message you need to set the last param to true iirc

Yes I am. This is not working. Using revoke true ir false make no difference

**Comment by smashah** [comment]
@joweste use the latest version, it is now idiot proof. You don't need to send the third parameter anymore.

**Comment by joweste** [comment]
> @joweste use the latest version, it is now idiot proof. You don't need to send the third parameter anymore.

Thank you. I will test.
Please, can you tell me if there is some field in the message object to indicate if it was deleted/revoked? 
I am making some tests and I can reload old messages, some them, I had deleted.
So, I´d like to know if there is a field to indicate revoked/deleted such as exists to invis, ack, isMedia......
