### ISSUE TITLE
[feature] Block all WhatsApp error reporting.

### ISSUE THREAD

**Issue by smashah** [smashah/sulla#126]
Use the request interceptor to block all WhatsApp error reporting.

**Comment by smashah** [comment]
Now live in 1.7.24

add `blockCrashLogs:true,` to your create config to block all crash reporting to whatsapp.

**Comment by gnadelwartz** [comment]
shouldn't this the default to avoid detecting our bots?

**Comment by smashah** [comment]
@gnadelwartz maybe in the future but for now it's optional till we all learn the effects of this.
