### ISSUE TITLE
contactBlock returns setBlock is not a function

### ISSUE THREAD

**Issue by joweste** [smashah/sulla#127]
**Describe the bug**
window.WAPI.contactBlock and window.WAPI.uncontactBlock returns  
`contact.setBlock is not a function at Object.window.WAPI.contactBlock`

**Steps to Reproduce**
1. Load the wapi.js  into chrome dev console
2. execute in chrome dev console:  window.WAPI.uncontactBlock("5521.....@c.us")
3. The error will show

**Expected behavior**
The contact should be blocked

**DEBUG INFO**
`contact.setBlock is not a function at Object.window.WAPI.contactBlock`

  WA_VERSION: Latest,
  PAGE_UA: .default 
  SULLA_HOTFIX_VERSION: Latest
  BROWSER_VERSION: latest chrome

**Comment by smashah** [comment]
This is not a feature of sulla-hotfix right now so is low priority. I'll reopen when it's due to be worked on.
