### ISSUE TITLE
Problem to read qrcode capured

### ISSUE THREAD

**Issue by rfscheidt** [smashah/sulla#13]
I cannot read the qrcode captured with method bellow:

sulla.ev.on('qr', async qrcode => {
  //qrcode is base64 encoded qr code image
  //now you can do whatever you want with it
  const imageBuffer = Buffer.from(
    qrcode.replace('data:image/png;base64,', ''),
    'base64'
  );
  fs.writeFileSync('qr_code.png', imageBuffer);
});

The quality of image is very bad.

**Comment by smashah** [comment]
Can you give me an example of the QR code? It's not really supposed to be full hd. As long as you can see the QR code properly it should work fine.

**Comment by rfscheidt** [comment]
The quality of the image generated is so bad that the phone does not recognize. Your generated image, Do can you scan on the phone?

![qr_code](https://user-images.githubusercontent.com/7602639/69454124-38cb3480-0d44-11ea-9f15-9dc9a6af2598.png)

**Comment by rfscheidt** [comment]
The quality of the image generated is so bad that the phone does not recognize. Your generated image, Do can you scan on the phone?

**Comment by smashah** [comment]
@rfscheidt It is not the quality of the QRCode that is the issue.

Right now it just forwards the base64 src of the qr code element on whatsapp web page. Sometimes the qr code works, sometimes it doesn't not quite sure why, maybe open up the qr code in another applciation?

**Comment by rfscheidt** [comment]
I'm sorry, I created a html with src=qrcode.. and its works very well. I think that when have a background white the camera read ok. Thank you!

**Comment by smashah** [comment]
Awesome. I'll close this for now then thanks
