### ISSUE TITLE
TOS_BLOCK restart service

### ISSUE THREAD

**Issue by rafael-sarti** [smashah/sulla#131]
It is possible to restart the first session however when the process and start again. A saved session TOS_BLOCK, removes the session folder. Again the QR is requested.

He can no longer recover the saved session :(

![Captura de Tela 2020-02-17 às 6 30 02 PM](https://user-images.githubusercontent.com/59804684/74687589-9c35f880-51b3-11ea-8c58-e53c2a2e763d.png)

**Comment by rafael-sarti** [comment]
@smashah failed

**Comment by smashah** [comment]
Hey @rafael-sarti please re open this issue with template properly filled as this one is not clear. Thanks

**Comment by rafael-sarti** [comment]
What would be the model?
