### ISSUE TITLE
Add an event listeners to Loading Qr to prevent long waiting

### ISSUE THREAD

**Issue by mrbarnk** [smashah/sulla#133]
Hi @smashah , can you please add an event listener to `Loading Qr`? Some Qr's always hanging, and we would want to check if the QR has been waiting for more than 60 seconds without actually printing any QR code on the terminal.

Or you add the feature to the latest release, once the Loading Qr is taking forever, reCreate the WhatsApp instance again.

With this, the errors would reduce and page crashes should not be much again.

Thanks!

I don't know how to reproduce the error, as it happens sometimes only.

The Logs
 
```0|index    | - Authenticating
0|index    | ✔ Authenticating
0|index    | - Injecting api
0|index    | - WAPI injected
0|index    | - Authenticating
0|index    | ℹ Authenticate to continue
0|index    | - Loading QR
0|index    | ✔ Loading QR
```

Debug Info:

```
0|index  | Debug Info {
0|index  |   WA_VERSION: '0.4.930',
0|index  |   PAGE_UA: 'WhatsApp/0.4.613 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36',
0|index  |   SULLA_HOTFIX_VERSION: '1.7.24',
0|index  |   BROWSER_VERSION: 'HeadlessChrome/79.0.3945.0'
0|index  | }
```
It hangs at Loading Qr

It has be reported here I think. https://github.com/smashah/sulla/issues/125

**Comment by smashah** [comment]
@mrbarnk #120 was a bug. This is due to the new version of WhatsApp 0.4.930

**Comment by mrbarnk** [comment]
No, I'm not talking about that,
I was able to solve that, my bad I didn't post that.

I mean the text Loading Qr always hang and never prints the QR exactly like #125

**Comment by smashah** [comment]
@mrbarnk  there is a killtimer you can add to the create config. It's not documented properly but you can find it here. 

https://github.com/smashah/sulla/issues/97#issuecomment-583777080

**Comment by smashah** [comment]
Added to README

https://github.com/smashah/sulla#timing-out-an-unpaired-session

Closing.
