### ISSUE TITLE
Change profile info

### ISSUE THREAD

**Issue by mmc16** [smashah/sulla#134]
Probably, this is not something to be on the top priority list, but it could be useful.
In WhatsApp Web is possible to change the user name, the photo, and the description. So I was wondering, is it possible to do the same through Sulla?

**Comment by smashah** [comment]
@mmc16 if it's possible on web it is possible through here. Just takes some time to figure out. I'll keep this on the back burner for now. Thanks.

**Comment by smashah** [comment]
@mmc16 try it out in v1.7.26. Let me know if it works for you.

**Comment by mmc16** [comment]
I'll check it out, thnx

**Comment by mmc16** [comment]
@smashah it works with regular accounts. It doesn't seem to work with business accounts though

**Comment by smashah** [comment]
Iirc changing business details is a big deal ok WhatsApp. Is it possible to do it via WhatsApp web?

**Comment by mmc16** [comment]
My bad. I just found out that is not possible to change the name of a business account through WA web, and also that setMyStatus works fine with both kinds of account.

I'll close this issue for now
