### ISSUE TITLE
Requesting a QR CODE read again after restarting the process

### ISSUE THREAD

**Issue by rafael-sarti** [smashah/sulla#136]
Describe the bug

After the initialization of the example code in the "demo" I can read the QR CODE. When I finish the process and open again the session is not recovered generating an error or asking for the QR CODE again.

With the new update now the QR CODE keeps asking whenever the process starts again.

Debug Info {
   WA_VERSION: '0.4.930',
   PAGE_UA: 'WhatsApp / 0.4.613 Mozilla / 5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit / 537.36 (KHTML, like Gecko) Chrome / 79.0.3945.88 Safari / 537.36',
   SULLA_HOTFIX_VERSION: '1.7.26',
   BROWSER_VERSION: 'HeadlessChrome / 80.0.3987.116'
}

Steps to Reproduce

1. start the demo once and read the qr code
2. end the process and start again

![74687589-9c35f880-51b3-11ea-8c58-e53c2a2e763d](https://user-images.githubusercontent.com/59804684/74961657-2ddc7a80-53ed-11ea-8c83-11c56dd31330.png)

**Comment by mmc16** [comment]
Are you using the same session name? Or aren't you disconnecting from Whatsapp web from your phone? Or using the same number for another session simultaneously?

**Comment by smashah** [comment]
@rafael-sarti thanks, this is much clearer. I'm actually having this problem also. IDK what's going on. What's your operating system? Also, please share your create code.

**Comment by rafael-sarti** [comment]
@mmc16 I'm not using two sessions :(

**Comment by rafael-sarti** [comment]
@smashah I'm using demo / server.js to test if the error replicates. My operating system under development is OSX Catalina and in the production environment the same problem occurs as Ubuntu 18

**Comment by rafael-sarti** [comment]
Update: It seems that he understands another browser not compatible at a time that returns the session. Have you tried some items? Support, does anyone know that I can recover a session?

![Captura de Tela 2020-02-29 às 17 53 17](https://user-images.githubusercontent.com/59804684/75614928-70eccb00-5b1c-11ea-8b19-d147139be22c.png)

**Comment by rafael-sarti** [comment]
I discovered something very relevant by analyzing a similar project on github. They do the session just by keeping a JSON. Inside JSON it stores the following information.

{"WABrowserId": "\" 22 \ "", "WASecretBundle": "{\" key \ ": \" 2/2 = \ ", \" encKey \ ": \" 2 + 2 = \ ", \ "macKey \": \ "2/2 = \"} "," WAToken1 ":" \ "2 + 2/2 = \" "," WAToken2 ":" \ "1 @ / 2 + 2 == \" "}

Logically my data changed to number 2. Only with an inject is it possible to return to the session. See if this is evidence who understands the project better.

@smashah

**Comment by smashah** [comment]
@rafael-sarti can you provide a link to that, please

**Comment by rafael-sarti** [comment]
https://github.com/pedroslopez/whatsapp-web.js.git

**Comment by smashah** [comment]
![image](https://user-images.githubusercontent.com/5903821/75717579-4724d700-5cc9-11ea-849e-41e19ef658e4.png)


@rafael-sarti You're the MVP for the day. With your clue I was able to fix this issue. Thanks.

**Comment by rafael-sarti** [comment]
@smashah, Thanks! Now it's 100% functional again :)
Uhuuuullll!!!
