### ISSUE TITLE
idGroup, idParticipant 

### ISSUE THREAD

**Issue by ajisek** [smashah/sulla#137]
**Ask**

i will use the function ```removeParticipant``` ,  how to i can get the idGroup and idPariticipant?

**Comment by mmc16** [comment]
You can get the group id from `getAllChats()` or `getAllGroups()` and the participant id form `getGroupMembers()` or `getGroupMembersId()` . Take a look at the docs, it lists all functions you can use.
[https://smashah.github.io/sulla/classes/whatsapp.html](url)

**Comment by smashah** [comment]
This brings up a bigger point of standardising parameter names.

**Comment by ajisek** [comment]
i'm using ```client.getAllGroups(withNewMessagesOnly = true)``` and ```client.getGroupMembersId()``` to get idGroup,
when try debug, i'm getting nothing, look the pict
whats a problem?
![image](https://user-images.githubusercontent.com/33994563/75110811-55d61300-5665-11ea-9b24-fe256a40bb3d.png)

**Comment by mmc16** [comment]
@ajisek , are you using `await` or `.then()`? Those functions are asynchronous, that means that the program doesn’t wait the function to complete its execution before executing the next line. Read about asynchronous functions to understand it better.

**Comment by ajisek** [comment]
how i can use it? you can give a example?

**Comment by ajisek** [comment]
solved
