### ISSUE TITLE
Handling Multiple Session At Once

### ISSUE THREAD

**Issue by mrbarnk** [smashah/sulla#138]
Hello @smashah , is there a way to use a particular session to send message when dealing with multiple sessions?

Like after creating a session like this.
```
create('session_a').then(client => start(client));

create('another_session').then(client => start(client));

```

Then the two functions are working perfectly, then I want to reply to a contact outside `client.onMessage` function with `session_a`.

I want to send a notification or invoice to a client that has messaged `session_a` before and won't interfere with `another_session`.

How will I identify the sessions?

**Comment by gnadelwartz** [comment]
IMHO this is done by the variable client from inside the start() function.
if you need to access it from outside start you can possibly assign the local client variable to a global variable.

**Comment by mrbarnk** [comment]
No, You don't get me.

Just like receiving a webhook from somewhere, and it same start function that will be used by the two.

How will I say send this message from `POST` request to this number using this session?

That;t what I'm asking.

**Comment by mmc16** [comment]
For my program, I use an array of clients. Something like this:
```javascript
var clientsArray = [];
....
clientsArray[sessionName] = await sulla.create(sessionName,....);
start(clientsArray[sessionName]); // I set the message listeners inside this function
```
Now let's say I've received a message via POST to send somewhere. One of the parameters of this request could be the session name. This way I can send the message like this:
```javascript
var sessionName //retrieved from the POST request
var message // also retrieved from POST
var number // same
clientsArray[sessionName].sendText(number, message);
```
As for the message listeners, you can use function closure inside your `start()` to forward the messages to your server's clients

**Comment by mrbarnk** [comment]
Wow, thanks for this Idea. You're awesome. @mmc16

**Comment by smashah** [comment]
Yeah I would do it the same way as @mmc16 in a single node process environment.

**Comment by marcelocecin** [comment]
it would be encouraging to share sample code in the demo folder

**Comment by AgustinQuetto** [comment]
You can use multiple instances of Sulla on a same process or the same script inside various containers using Docker.

**Comment by smashah** [comment]
Closing for now
