### ISSUE TITLE
client.getMe method?

### ISSUE THREAD

**Issue by mrbarnk** [smashah/sulla#140]
Hi, is there a function that exposes the client number?

Like `client.getMe()` would return My details, like `name, number, profile picture` e.t.c.

**Comment by smashah** [comment]
You can call `client.getMe()` in v1.7.28 now and use [getProfilePicFromServer](https://smashah.github.io/sulla/classes/whatsapp.html#getprofilepicfromserver) to get the profile pic.

https://smashah.github.io/sulla/classes/whatsapp.html#getme

**Comment by smashah** [comment]
I've tested this already so will close for now. Reopen if there's any issues. Thanks

**Comment by sanep10** [comment]
Hi
client.getMe() return undefined

`
const generatedUa =
      "WhatsApp/0.4.613 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36";
    sulla
      .create(
        session,
        {
          executablePath: "/usr/bin/google-chrome",
          headless: true,
          autoRefresh: false,
          qrRefreshS: 30 //please note that if this is too long then your qr code scan may end up being invalid. Generally qr codes expire every 15 seconds.
        },
        generatedUa
      )
      .then(async client => {
        this.client = client;
        let number = await client.getMe();
        console.log(number);
      });
`

I don't start a new issue because i think that is an own error

¡Thanks!
