### ISSUE TITLE
detect if added into group

### ISSUE THREAD

**Issue by arelxcode** [smashah/sulla#143]
how to detect/listen if my whatapp added into group

**Comment by arelxcode** [comment]
and how to using onParticipantsChanged to my all group?

**Comment by smashah** [comment]
Regarding your second point, you'll need to traverse your groups and set up the listeners

**Comment by smashah** [comment]
Implemented in v1.7.32

https://smashah.github.io/sulla/classes/whatsapp.html#onaddedtogroup

thanks

**Comment by arelxcode** [comment]
why not showing a result?

**Comment by smashah** [comment]
@arelxcode if it is not working for you please make a new issue with the issue template filled out. Thanks
