### ISSUE TITLE
client.sendSeen not defined

### ISSUE THREAD

**Issue by algoz098** [smashah/sulla#147]
**Describe the bug**
The npm sulla-hotfix`s function sendSeen is not defined

**Steps to Reproduce**
1. Start sulla with the built version
2. After connection use sendSeen

**create() code**
This is the code you use to create the client. e.g
```javascript
sulla.create(createCb)
```

**Expected behavior**
Function should be defined (dist/api/whastapp.d.ts

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
1|3001     |   WA_VERSION: '0.4.930',
1|3001     |   PAGE_UA: 'WhatsApp/0.4.613 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36',
1|3001     |   SULLA_HOTFIX_VERSION: '1.7.28',
1|3001     |   BROWSER_VERSION: 'Chrome/79.0.3945.0'
```

**Host (please complete the following information):**
 - MacOS

**Comment by smashah** [comment]
https://smashah.github.io/sulla/classes/whatsapp.html#sendseen
