### ISSUE TITLE
Get all contacts from broadcast list

### ISSUE THREAD

**Issue by rfscheidt** [smashah/sulla#15]
Is there any way I can get all contacts from a broadcast list?

**Comment by smashah** [comment]
@rfscheidt I'm guessing it'd be the same as getting contacts from a group. Right now getting a broadcast fails via getChatById due to send message returning null. Will investigate further later today. In the meantime let me know if you have any ideas.

**Comment by rfscheidt** [comment]
I do not know, get all contacts from the group I also could not. Is there a specific method to do this?

**Comment by smashah** [comment]
@rfscheidt ignore my previous comment.

You can use 


```
client.getGroupMembersId('123456789@broadcast')
```

which should result in an array of all members in a group and as far as I know it works on broadcasts also.
