### ISSUE TITLE
Contribution to api

### ISSUE THREAD

**Issue by joweste** [smashah/sulla#153]
Here is a small function to get Status
/**
* Get your status
*   @param {string} to '000000000000@c.us'
*   returns: {string,string} and string -"Hi, I am using WhatsApp" 
*/
window.WAPI.getStatus = async (id) => {
    return await Store.MyStatus.getStatus(id)
}

**Comment by smashah** [comment]
![image](https://user-images.githubusercontent.com/5903821/75696780-05356a00-5ca4-11ea-845b-db61137b408d.png)

Thanks
