### ISSUE TITLE
Simulate "typing..." and "recording audio..."

### ISSUE THREAD

**Issue by marcelocecin** [smashah/sulla#154]
You can now do this using the sendStateTyping() and sendStateRecording() functions available on the Chat model. These will last for approximately 25 seconds and can be called again to refresh the timeout. A clearState() function is also available to immediately clear the typing or recording status.

```python
window.WAPI.sendChatstate = async function (state, chatId) => {
    switch(state) {
        case 'typing':
            await window.Store.Wap.sendChatstateComposing(chatId);
            break;
        case 'recording':
            await window.Store.Wap.sendChatstateRecording(chatId);
            break;
        case 'stop':
            await window.Store.Wap.sendChatstatePaused(chatId);
            break;
        default:
            throw 'Invalid chatstate';
    }
    return true;
};
```

**Comment by smashah** [comment]
@marcelocecin can you make a PR for this? I'm working on TOSBLOCK

**Comment by joweste** [comment]
> @marcelocecin can you make a PR for this? I'm working on TOSBLOCK

Hi, what is TOS_BLOCK? Why and when this happend?

**Comment by joweste** [comment]
> You can now do this using the sendStateTyping() and sendStateRecording() functions available on the Chat model. These will last for approximately 25 seconds and can be called again to refresh the timeout. A clearState() function is also available to immediately clear the typing or recording status.
> 
> ```python
> window.WAPI.sendChatstate = async function (state, chatId) => {
>     switch(state) {
>         case 'typing':
>             await window.Store.Wap.sendChatstateComposing(chatId);
>             break;
>         case 'recording':
>             await window.Store.Wap.sendChatstateRecording(chatId);
>             break;
>         case 'stop':
>             await window.Store.Wap.sendChatstatePaused(chatId);
>             break;
>         default:
>             throw 'Invalid chatstate';
>     }
>     return true;
> };
> ```

Hi I am not able to find clearState function.

**Comment by smashah** [comment]
![release](https://user-images.githubusercontent.com/5903821/75765912-319ac600-5d38-11ea-8472-df1a812004db.png)
