### ISSUE TITLE
Feature issue - authenticating event

### ISSUE THREAD

**Issue by itzharDev** [smashah/sulla#162]
get an event the moment the user has just scant the QR

**Comment by smashah** [comment]
Relates to #130

**Comment by smashah** [comment]
![image](https://user-images.githubusercontent.com/5903821/75815428-4ce2f100-5d8b-11ea-9e46-ac4ed62a3977.png)

You can now listen to startup  events like this:

```javascript
ev.on('STARTUP.**', async (data,sessionId,namespace) => {
  console.log("\n----------")
  console.log('STARTUP',data,sessionId,namespace)
  console.log("----------")
})
```

This sends out a new event with every message from the console upon startup.

Tested to be working.

Thanks
