### ISSUE TITLE
can't run example of index

### ISSUE THREAD

**Issue by xshion13** [smashah/sulla#183]
I downloaded and installed this in order to make a fresh start of this but the example is not working, please make it some easy for noobs i am still learning javascript i can't fix issues like a pro but i like itt 

pd: anyone is a teacher for this :d? 

![image](https://user-images.githubusercontent.com/56605018/76036257-94938500-5f11-11ea-8cc6-57f10457e3f5.png)

**Comment by gnadelwartz** [comment]
doc/index.ts is typescript, see https://github.com/smashah/sulla/issues/85

**Comment by smashah** [comment]
https://github.com/smashah/sulla#running-the-demo

**Comment by xshion13** [comment]
> https://github.com/smashah/sulla#running-the-demo

i tried to install google-chrome-stable and runn with this but it closed with this message:
![image](https://user-images.githubusercontent.com/56605018/76153654-cd139a00-609c-11ea-8ccc-cf31f77cdffd.png)
