### ISSUE TITLE
createGroup() and return created groupId

### ISSUE THREAD

**Issue by LucasDibz** [smashah/sulla#190]
I'm using client.createGroup('Cool new group','xxxxxxxxx@c.us')

But i would like to send some messages to this newly created group.

What would be the best way to create a group and get this groupId to send some texts/manipulate.

as groupId is going to be 'mynumber@c.us-RANDOMNUMBER@g.us

Thank you

**Comment by LucasDibz** [comment]
Also,
Could it be possible to: search allGroups to check if Group between me + other contact already exists?

Thank you

**Comment by smashah** [comment]
@LucasDibz Should be working in 1.8.13

![image](https://user-images.githubusercontent.com/5903821/76165169-b6c51700-614c-11ea-93f2-0605bdc4cbd9.png)


```javascript
    const groupCreationResponse= await client.createGroup('coolnewgroup','0000000000@c.us');
    console.log("start -> groupCreationResponse", groupCreationResponse);

// groupCreationResponse {
//     status: 200,
//     gid: {
//       server: 'g.us',
//       user: '447777777777-1583678870',
//       _serialized: '447777777777-1583678870@g.us'
//     },
//     participants: [
//       { '447777777777@c.us': [Object] },
//       { '447444444444@c.us': [Object] }
//     ]
//   }
```
