### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'browser' of undefined

### ISSUE THREAD

**Issue by bubaew95** [smashah/sulla#191]
**Describe the bug**

**Steps to Reproduce**

**create() code**
This is the code you use to create the client. e.g
```javascript
sulla.create(...)
```

**Expected behavior**

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
  WA_VERSION: ...,
  PAGE_UA: ...,
  SULLA_HOTFIX_VERSION: ...,
  BROWSER_VERSION: ...
}
```

**Screenshots**
If applicable, add screenshots to help explain your problem. Use ```headless: false``` to get screenshots

**Host (please complete the following information):**

**Additional context**

**Comment by barkerpedro** [comment]
The 'browser' error occurs when you configure the 'executablePath' incorrectly, below are some settings to test:

MAC:
`executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'`

Windows: 
`executablePath: 'C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe'`

Linux:
`executablePath: '/usr/bin/google-chrome-stable'`

**Comment by bubaew95** [comment]
@barkerpedro  Thank you man)

**Comment by xshion13** [comment]
what about centos 7 i am looking it

**Comment by gnadelwartz** [comment]
try `locate chromium` in terminal
mine is
```
// For Linux:                                                                                                                        
  executablePath: '/usr/bin/chromium',
```
@smashah may be you can add linux path example to readme

**Comment by smashah** [comment]
I think I'll implement some auto detector with a configuration flag like `useChrome: true` or something.

**Comment by smashah** [comment]
![image](https://user-images.githubusercontent.com/5903821/76154218-aff8be80-60d0-11ea-8759-13aad28cda64.png)


https://smashah.github.io/sulla/interfaces/configobject.html#usechrome
