### ISSUE TITLE
Error for execute Demo in Windows

### ISSUE THREAD

**Issue by andersondeoliveiramachado** [smashah/sulla#192]
![image](https://user-images.githubusercontent.com/1152426/76123801-2a91e300-5fd8-11ea-901e-8d9b54197661.png)

**Comment by smashah** [comment]
Try ora v4.0.2  and what is your ts-node version?

**Comment by andersondeoliveiramachado** [comment]
> Try ora v4.0.2 and what is your ts-node version?
ts-node v8.6.2
I installed ora@4.0.2 and it still didn't work. gives the same message as the image above.

**Comment by smashah** [comment]
@andersondeoliveiramachado I tried it on my windows machine at work. Can you pull the repo and do a fresh npm i. It is working fine for me.

**Comment by andersondeoliveiramachado** [comment]
> @andersondeoliveiramachado I tried it on my windows machine at work. Can you pull the repo and do a fresh npm i. It is working fine for me.

OK with  (sulla-hotfix@1.8.13)
