### ISSUE TITLE
Decrypting Media audio

### ISSUE THREAD

**Issue by alejandroguille** [smashah/sulla#2]
Hi.
Audio decryption is needed, currently this fails.

**Comment by lasoftinfo** [comment]
decryption audio voice ?

**Comment by smashah** [comment]
Hi @alejandroguille and @lasoftinfo this is fixed now in new version v1.2.2. thanks so much.

https://github.com/smashah/sulla/commit/7ceff9ebff1ef94cdaf79b490a6adbb733971105
