### ISSUE TITLE
[Suggestion] Create new Group between message.from and a contact_id

### ISSUE THREAD

**Issue by LucasDibz** [smashah/sulla#20]
Would it be possible to create a new Group with message.from (contactid) and another contact id?
Then make it so main phone leaves the group afterwards.

Thank you for your time

**Comment by marcelocecin** [comment]
did you try to use the `createGroup`, `promoteParticipantAdminGroup` and `leaveGroup` functions ?

**Comment by LucasDibz** [comment]
I didn't know they existed in the first place,
My project changed and i couldn't test/implement this action.
Will leave it open in case someone wants to post a code example...

**Comment by smashah** [comment]
@LucasDibz @marcelocecin 

You can now create groups and do all actions mentioned above in v1.7.2

https://github.com/smashah/sulla#create-group
https://github.com/smashah/sulla#group-participants-beta

Thanks
