### ISSUE TITLE
getAllUnreadMessages and getAllNewMessages return empty array

### ISSUE THREAD

**Issue by mmc16** [smashah/sulla#200]
**Describe the bug**
`getAllUnreadMessages` and `getAllNewMessages` are returning empty arrays, both in the Node env and on headful Chrome 

**Steps to Reproduce**
1. Create session (either headless or headful)
2. Call `getAllUnreadMessages` or `getAllNewMessages`
3. Get the empty arrays

**create() code**
This is the code you use to create the client. e.g
```javascript
var sullaParams = {
        executablePath: '/usr/bin/google-chrome-stable',
        headless: true,
        throwErrorOnTosBlock: true,
        killTimer: 30,
        autoRefresh: true, //default to true
        qrRefreshS: 10,
        cacheEnabled: false,
        headless: false
    };

sulla.create(sessionId, sullaParams);
```

**Expected behavior**
Get an array with the unread/new messages

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
  WA_VERSION: '0.4.1296',
  PAGE_UA: 'WhatsApp/0.4.613 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36',
  SULLA_HOTFIX_VERSION: '1.8.15',
  BROWSER_VERSION: 'Chrome/79.0.3945.130'
}

```

**Screenshots**
If applicable, add screenshots to help explain your problem. Use ```headless: false``` to get screenshots

![Captura de tela_2020-03-10_12-17-22](https://user-images.githubusercontent.com/27312683/76327732-1e07d600-62c9-11ea-99dd-d51403727c62.png)

![Captura de tela_2020-03-10_12-17-00](https://user-images.githubusercontent.com/27312683/76327606-fadd2680-62c8-11ea-851f-85bd32d45fa6.png)

**Host (please complete the following information):**
 - OS: 5.3.18-1-MANJARO

**Comment by smashah** [comment]
@mmc16 try this

```javascript
  const newMessages = await client.getUnreadMessages(false,true,false);
  console.log("TCL: start -> newMessages", newMessages)
```

**Comment by mmc16** [comment]
@smashah I tried this, but the problem is still the same...
And just for curiosity, what are these parameter for?

**Comment by smashah** [comment]
@mmc16 https://smashah.github.io/sulla/classes/whatsapp.html#getunreadmessages

**Comment by lucaspiressimao** [comment]
I'm facing the same problem. I tried many things but It was not possible to get it working

**Comment by smashah** [comment]
@lucaspiressimao please fill in the issue template:

https://github.com/open-wa/wa-automate-nodejs/issues/new?assignees=&labels=&template=bug_report.md&title=
