### ISSUE TITLE
onAddedToGroup

### ISSUE THREAD

**Issue by arelxcode** [smashah/sulla#201]
how to use this function?

i already test but not have result.

for test
`async function start(client)  
{    
    await client.onAddedToGroup(async chat =>
        {
            console.log(chat)
        })
}`

**Comment by arelxcode** [comment]
anyone?

**Comment by smashah** [comment]
@arelxcode https://github.com/smashah/sulla/blob/b4dd56512f47507ecc69281d336210af45d1c28c/demo/index.ts#L54

please use version 1.8.21
