### ISSUE TITLE
can I run a project in the browser so that the qr code is created in the browser?

### ISSUE THREAD

**Issue by bubaew95** [smashah/sulla#203]
**Describe the bug**

**Steps to Reproduce**

**create() code**
This is the code you use to create the client. e.g
```javascript
sulla.create(...)
```

**Expected behavior**

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
app    | Debug Info {
app    |   WA_VERSION: '0.4.1296',
app    |   PAGE_UA: 'WhatsApp/0.4.613 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36',
app    |   SULLA_HOTFIX_VERSION: '1.8.15',
app    |   BROWSER_VERSION: 'HeadlessChrome/80.0.3987.132'
app    | }

```

**Screenshots**
If applicable, add screenshots to help explain your problem. Use ```headless: false``` to get screenshots

**Host (please complete the following information):**

**Additional context**

**Comment by jesusvalverde** [comment]
You can save the QR (image) and over the browser show the image .
