### ISSUE TITLE
Get author in group chat

### ISSUE THREAD

**Issue by ajisek** [smashah/sulla#205]
**Describe the bug**
Get whois send text in group (author)

**create() code**
This is the code you use to create the client. e.g
```javascript
sulla.create('SESSION', {executablePath: '/usr/bin/google-chrome-stable'}).then(client => start(client));
```

**Expected behavior**
How can i get author (whois send the text in group) ?

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info { WA_VERSION: '0.4.1296',
  PAGE_UA: 'WhatsApp/0.4.613 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36',
  SULLA_HOTFIX_VERSION: '1.8.15',
  BROWSER_VERSION: 'HeadlessChrome/80.0.3987.132' }

```

**Comment by mmc16** [comment]
As far as I know, every message object has the `sender` attribute, which is the complete Contact data. If you want only the sender's id, you can also get it from the message's `from` attribute.

**Comment by gnadelwartz** [comment]
print(message.sender);

**Comment by ajisek** [comment]
> print(message.sender);
> 
> documentation if user attributes https://tl.telethon.dev/constructors/user.html

thanks, this work
