### ISSUE TITLE
how to fetch with sulla

### ISSUE THREAD

**Issue by xshion13** [smashah/sulla#207]
i am tryinh to use fetch

```
fetch('https://jsonplaceholder.typicode.com/todos/1')
  .then(response => response.json())
  .then(json => console.log(json))
```

to test how this works but nothing is in console, i want to create a command to send data to server and get a response to print in chat, please help

**Comment by Dikz** [comment]
@xshion13 fetch is for use in the browser.
You can use node-fetch or axios

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>Template!</summary>

```js
(async () => {
//label issue
await githubClient.issues. addLabels({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        labels: ["doesn't follow template"]
      })

 await postComment(`⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.md&title=)⚠️⚠️⚠️`);

//close issue
await githubClient.issues. update({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        state: "closed"
      })
})();
```
</details>

**Comment by smashah** [comment]
⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.md&title=)⚠️⚠️⚠️

**Comment by jesusvalverde** [comment]
const fetch = require('node-fetch');
 const path = "http://www.yoursite.com";
 
/* whatever you use to register and control incoming messages */

 const url='t='+message.from+'&n='+message.sender.pushname+'&whatTXT='+ message.body; 
 fetch(path + '?' + encodeURI(url) )
       .then(response => response.text() )
       .then(data => { client.sendText(message.from, data );  }) // you send whatever the URL responde you, you can also try response.json() if you get a JSON  
       .catch((error) => {  console.log(error) });
