### ISSUE TITLE
Unable to install actual version [Release 1.8.17]

### ISSUE THREAD

**Issue by jesusvalverde** [smashah/sulla#208]
**Describe the bug**
Unable to install sulla-hotfix

**Steps to Reproduce**
-Make a new AWS server  t2.micro
-Access via terminal

sudo apt-get update -y && sudo apt-get upgrade -y 
sudo apt install npm
npm i --save sulla-hotfix 
[also try sudo] 
*** end of steps ***

**create() code**
no code created 

**Expected behavior**
Install sulla-hotfix

**DEBUG INFO**
No debug over the sulla 

**Screenshots**
![Captura de Pantalla 2020-03-11 a la(s) 16 09 17](https://user-images.githubusercontent.com/6410702/76469806-9eefcc00-63b4-11ea-8918-138ff70e6e01.png)

**Host (please complete the following information):**
"Canonical, Ubuntu, 18.04 LTS, amd64 bionic image build on 2020-01-12"
Updated & upgraded
npm -v
 ==> 3.5.2

**Additional context**
none

**Comment by smashah** [comment]
@jesusvalverde 

https://sharp.pixelplumbing.com/install#aws-lambda

sharp is required now for webp conversions.

**Comment by jesusvalverde** [comment]
@smashah 

Thanks for the quick reply

**Describe the bug**
Unable to install 

**Steps to Reproduce**
-Make a NEW AWS server t2.micro
-Access via terminal

sudo apt-get update -y && sudo apt-get upgrade -y
sudo apt install npm
 using the recomedation code 
 https://sharp.pixelplumbing.com/install#aws-lambda
rm -rf node_modules/sharp
npm install --arch=x64 --platform=linux --target=12.0.0 sharp
*** end of steps ***
[No going further due errors]


create() code
no code created

Expected behavior
instal patch recomended 

DEBUG INFO
npm install --arch=x64 --platform=linux --target=12.0.0 sharp
▄ ╢░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadRequestedDeps         ▀ ╢██████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:tunnel-agent → ma ▀ ╢██████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:tunnel-agent → re ▀ ╢██████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:readable-stream → ▐ ╢████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟

> sharp@0.25.1 install /home/ubuntu/node_modules/sharp
> (node install/libvips && node install/dll-copy && prebuild-install --runtime=napi) || (node-gyp rebuild && node install/dll-copy)

info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.9.1/libvips-8.9.1-linux-x64.tar.gz
prebuild-install WARN This package does not support N-API version 12.0.0 
prebuild-install WARN install No prebuilt binaries found (target=12.0.0 runtime=napi arch=x64 libc= platform=linux)
gyp: name 'enable_lto' is not defined while evaluating condition 'enable_lto=="true"' in binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:340:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.15.0-1057-aws
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/ubuntu/node_modules/sharp
gyp ERR! node -v v8.10.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/home/ubuntu/package.json'
npm WARN ubuntu No description
npm WARN ubuntu No repository field.
npm WARN ubuntu No README data
npm WARN ubuntu No license field.
npm ERR! Linux 4.15.0-1057-aws
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "--arch=x64" "--platform=linux" "--target=12.0.0" "sharp"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! sharp@0.25.1 install: `(node install/libvips && node install/dll-copy && prebuild-install --runtime=napi) || (node-gyp rebuild && node install/dll-copy)`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.25.1 install script '(node install/libvips && node install/dll-copy && prebuild-install --runtime=napi) || (node-gyp rebuild && node install/dll-copy)'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the sharp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     (node install/libvips && node install/dll-copy && prebuild-install --runtime=napi) || (node-gyp rebuild && node install/dll-copy)
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs sharp
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls sharp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/npm-debug.log


Screenshots
![Captura de Pantalla 2020-03-11 a la(s) 17 10 28](https://user-images.githubusercontent.com/6410702/76472632-c302db80-63bb-11ea-9012-b7933105d08c.png)

**Comment by smashah** [comment]
@jesusvalverde please update your node version

https://sharp.pixelplumbing.com/install#prerequisites

> Node.js v10+

**Comment by smashah** [comment]
Added node version requirement to the README. Closing for now. Thanks.

**Comment by jesusvalverde** [comment]
Solved  able to make a fresh istalation over AWS server t2.micro  "Canonical, Ubuntu, 18.04 LTS, amd64 bionic image build on 2020-01-12"


curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
sudo apt-get install -y nodejs

[Older version had not this requirement]

Thanks
