### ISSUE TITLE
Cannot start session without scan QR again

### ISSUE THREAD

**Issue by lugoea** [smashah/sulla#209]
**Describe the bug**
I can start a session first time scanning QR code. After that the session is lost and is not possible start session again without delete session folder and re scan QR code. Last version was installed and all steps were followed.

**Steps to Reproduce**
1. ts-node test.ts
2. Scan QR code
3. Use Ctrl-C to exit execution
4. ts-node test.ts

**create() code**
This is the code you use to create the client. e.g
```javascript
const sulla = require('sulla-hotfix');
const readlineSync = require('readline-sync');
sulla.create().then(client => start(client));
function start(client) {
  client.onMessage(message => {
          if ((message.from != 'status@broadcast') && (!message.isGroupMsg))
          {
        console.log(message.from);
        console.log(message.sender.name);
        console.log(message.body);
        var msj = readlineSync.question('Respuesta: ');
        client.sendText(message.from, msj);
//        console.log('Enviando... ' + msj );
          }
  });
}
```

**Expected behavior**
I am expecting that session data allows start session without scan QR code again.

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
First execution 

Debug Info { WA_VERSION: '0.4.1296',
  PAGE_UA:
   'WhatsApp/0.4.613 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36',
  SULLA_HOTFIX_VERSION: '1.7.35',
  BROWSER_VERSION: 'HeadlessChrome/79.0.3945.0',
  BROWSER_ID: 'pbiM+hqokKfBClTvlg/EyQ==' }
ℹ Authenticate to continue
✔ Loading QR
 
▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█ ▄▄▄▄▄ █▄▀██▀█▀████▄█ █▀█ ▄▄ ▄█▄▄█ ▄▄▄▄▄ █
█ █   █ █  ▀▄▀ ▄▄▀██▀▄█ ▀▀▄ ▀██▄█▄█ █   █ █
█ █▄▄▄█ █▄█▄ ▄ ▀█▄ ▀▀█▀██▄ █▄██▄▀▀█ █▄▄▄█ █
█▄▄▄▄▄▄▄█▄▀▄█▄█ █▄▀▄▀▄█ ▀▄█ ▀ ▀ ▀ █▄▄▄▄▄▄▄█
█ ▄  ▀▀▄▀▄▄▀▄█  ▄ █▄ ███▀▄█ █  ▄█  █▀   ▀ █
█ ▀▄▀█ ▄█▄▀▄▀▀▀▀█▄█▀█▀██ █ ▄▀█▄█████▄▄▄█ ▀█
█ ██  ▄▄▀▀ ▄▀█▄█   █▀█ ▄▄▀█  ▀ ▄▀█▀█▄█▀▄█▀█
█▄██ █▄▄█ ▀ █ ▄ ▀▀█▄ ▄▀▀████▀▄▄█▄▀█ ▄ █▄ ▄█
█ █ ▀▀ ▄▄█ █▄▀███▄ ▄ ▀ ▄█ ▄▀▀█▀▀▀  ▀ ▄▄████
█ ▀▄█▀ ▄▄█▄██ █▄▄ ▀██▄▄ █▀▄▄▄▄  ██ █    ▀██
█ ▀  ▀ ▄▀▄▄▄▄█ █▀ ▀▄▄▀ ▄▀▀█ █▀▄  ▀▀  ▀▄█▀██
█ ▄█▀  ▄ ▄█ ▀▀▀▄▀▄█▀███▄▄ ▀▀▀▀█ ██ █▄▀▄█ ▀█
█ ▀▀  ▄▄█   ▄  ▀▀  ▀ ▄▀▀  ▄▀▄ ▄▀▄▄▀██▄▀█ ▀█
█▀  ▄▀▀▄█ █▀█ ▀▄█▀█ ▄█  █▀█▄█▀▄▄▄▄█▀▀ ▀▄█ █
█▄▄▀▄█ ▄▀ ▀ █▄██ ▀█ ▄ ▄ ▀▄█▀▄▄█▀█ ▄▀ ▄█▄ ▄█
█▄█ ▀▀█▄▄██ ▀█▄▄   ▄▀▄▄▀▀█▄█▄  ██▀▀██ ▀ ▄██
██▄██▄▄▄█ ▄▄▀█▄ █▄▄ █ █▀▀█▀▄█ ▄   ▄▄▄  █▀ █
█ ▄▄▄▄▄ ██ ▄▄▄▀ █ █▄▀██▀▄▀ ▄▀▄▄▀  █▄█  █▀██
█ █   █ █▀  ▀ ▀█▀▀▄█ ██  ▀█  ▀ █▀ ▄▄▄ █▄▄▄█
█ █▄▄▄█ █ ██ ███▀ ▄ ▄▄  █▀▄▄█ █  ▀ ▀ █ ▄▀██
█▄▄▄▄▄▄▄█▄█▄█▄▄█▄█▄▄█▄█▄████▄▄▄▄▄▄█▄▄▄█▄▄██

 
✔ Authenticating
✔ WAPI Reinjected
✔ Whatsapp is ready

Second execution

Debug Info { WA_VERSION: 'I think you have been TOS_BLOCKed',
  PAGE_UA:
   'WhatsApp/0.4.613 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/
79.0.3945.88 Safari/537.36',
  SULLA_HOTFIX_VERSION: '1.7.35',
  BROWSER_VERSION: 'HeadlessChrome/79.0.3945.0',
  BROWSER_ID: '' }
Possilby TOS_BLOCKed
ℹ Authenticate to continue
✔ Loading QR


```

**Screenshots**
If applicable, add screenshots to help explain your problem. Use ```headless: false``` to get screenshots

**Host (please complete the following information):**

**Additional context**
All this code is being executed into Google Cloud machine

**Comment by mrbarnk** [comment]
Same things here.

**Comment by smashah** [comment]
Remove node modules folder. Install latest version.

**Comment by lugoea** [comment]
Hi, already removed the node folder and installed the last version. The problem continue. Do you have another possible solution to this?

**Comment by smashah** [comment]
@lugoea  Please share your logs

**Comment by lugoea** [comment]
This is the info. If you need anything else please let me know.
'''
✔ Initializing whatsapp
Debug Info { WA_VERSION: 'I think you have been TOS_BLOCKed',
  PAGE_UA:
   'WhatsApp/0.4.613 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36',
  SULLA_HOTFIX_VERSION: '1.7.35',
  BROWSER_VERSION: 'HeadlessChrome/79.0.3945.0',
  BROWSER_ID: '' }
Possilby TOS_BLOCKed
ℹ Authenticate to continue
✔ Loading QR
'''
Thanks in advance

**Comment by smashah** [comment]
@lugoea you are still using the old version. Please follow the instructions properly. Remove node modules, update Sulla hotfix to latest version then try again.
