### ISSUE TITLE
forceRefocus function bug

### ISSUE THREAD

**Issue by JoeDozan24** [smashah/sulla#217]
**Describe the bug**
The Force Refocus seems to be bugged

**Steps to Reproduce**
1. Create new sulla obj
2. wait until Listeners started
3. try to make it CONFLICT by signing in on other browser
4. the "auto forceRefocus" stopped there..

**create() code**
This is the code you use to create the client. e.g
```javascript
const sulla = require('sulla-hotfix');

const opt = {
	headless: false
}

// Sleep in milliseconds
function sleep(ms) {
	return new Promise(resolve => setTimeout(resolve, ms));
}

async function init() {
	await sulla.create('a', opt).then(client => start(client));
}
init();

function start(client) {
  client.onAnyMessage(message => {
    if (message.body === 'Hi') {
      client.sendText(message.from, '👋 Hello from sulla!');
    }
  });

  client.onStateChanged(async state => {
	  if(state == "CONFLICT") {
		  console.log("conflicted");
		  await sleep(2000);
		  await client.forceRefocus();
		  console.log("done");
	  }
  });
}
```

**Expected behavior**
Refocused.

**DEBUG INFO**
![image](https://user-images.githubusercontent.com/58735845/76859781-8ab43f00-688c-11ea-907e-958c3d815c0a.png)

**Host (please complete the following information):**
 - OS: Windows

**Comment by smashah** [comment]
What happens when trying to refocus? The program crashes? What are the error logs? Please share headful screenshots.

**Comment by JoeDozan24** [comment]
![image](https://user-images.githubusercontent.com/58735845/76927925-bed24300-6912-11ea-972e-61a0615db0db.png)
It doesn't do the "Use here" click. It should show the "done" on terminal after the forceRefocus await. So the sulla will stop doing anything, waiting for the forceRefocus function.

**Comment by JoeDozan24** [comment]
so I did this:
````javascript
client.onStateChanged(async state => {
	  if(state == "CONFLICT") {
		  console.log("conflicted");
		  await sleep(2000);
		  await client.forceRefocus();
		  console.log("done");
	  }
  });
```

It should show "done" after 2+ secs of "sleep"

**Comment by JoeDozan24** [comment]
And then I find out what's wrong with this..
Original code:
```js
switch (_a.label) {
    case 0: return [4, this.page.evaluate(function () { return window.l10n.localeStrings[window.l10n._locale.l][0][255]; })];
    case 1:
        useHere = _a.sent();
        return [4, this.page.waitForFunction("[...document.querySelectorAll(\"div[role=button\")].find(e=>{return e.innerHTML.toLowerCase()===\"" + useHere.toLowerCase() + "\"})", { timeout: 0 })];
    case 2:
        _a.sent();
        return [4, this.page.evaluate("[...document.querySelectorAll(\"div[role=button\")].find(e=>{return e.innerHTML.toLowerCase()==\"" + useHere.toLowerCase() + "\"}).click()")];
    case 3:
        _a.sent();
        return [2];
}
```
Array 255th value:
![useHere](https://user-images.githubusercontent.com/58735845/77034762-569c6380-69dd-11ea-89cb-e4fc330f1c27.png)

Finding out the "use here" and it's on array 257th
![useHere2](https://user-images.githubusercontent.com/58735845/77034795-6f0c7e00-69dd-11ea-8073-ad660ccc3dc0.png)

And Changed its value
```js
switch (_a.label) {
    case 0: return [4, this.page.evaluate(function () { return window.l10n.localeStrings[window.l10n._locale.l][0][257]; })];
    case 1:
        useHere = _a.sent();
        return [4, this.page.waitForFunction("[...document.querySelectorAll(\"div[role=button\")].find(e=>{return e.innerHTML.toLowerCase()===\"" + useHere.toLowerCase() + "\"})", { timeout: 0 })];
    case 2:
        _a.sent();
        return [4, this.page.evaluate("[...document.querySelectorAll(\"div[role=button\")].find(e=>{return e.innerHTML.toLowerCase()==\"" + useHere.toLowerCase() + "\"}).click()")];
    case 3:
        _a.sent();
        return [2];
}
```
and everything is good to go.

**Comment by smashah** [comment]
ok interesting @JoeDozan24 thanks for your investigation. I'll try to figure out a more long term fix.

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i`);
exec(`npm run release-ci`);

var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [1.8.20](https://github.com/smashah/sulla/compare/1.8.19...1.8.20) (2020-03-19)

- Bump ts-node from 8.6.2 to 8.7.0 [`#219`](https://github.com/smashah/sulla/pull/219)
- Bump @types/node from 13.9.1 to 13.9.2 [`#220`](https://github.com/smashah/sulla/pull/220)
- Bump marked from 0.8.0 to 0.8.1 [`#221`](https://github.com/smashah/sulla/pull/221)
- Bump typedoc from 0.17.0 to 0.17.1 [`#218`](https://github.com/smashah/sulla/pull/218)
- Bump typedoc from 0.16.11 to 0.17.0 [`#213`](https://github.com/smashah/sulla/pull/213)
- Bump release-it from 13.0.2 to 13.1.1 [`#214`](https://github.com/smashah/sulla/pull/214)
- Bump futoin-hkdf from 1.3.1 to 1.3.2 [`#215`](https://github.com/smashah/sulla/pull/215)
- Bump @types/node from 13.9.0 to 13.9.1 [`#211`](https://github.com/smashah/sulla/pull/211)
- Release 1.8.20 [`01e1380`](https://github.com/smashah/sulla/commit/01e13801287715ab4a4f599ffbcf6cc10a8d17f0)
- fix for forceRefocs. Now shows message if broken. #217 [`ea426b4`](https://github.com/smashah/sulla/commit/ea426b45960b3912c5a9cdfdf520d657c99f49b0)
- added ts-ignore for lang_check [`42a17e3`](https://github.com/smashah/sulla/commit/42a17e325b7e2b8101aaa375fe35ff7234631e13)

**Comment by smashah** [comment]
should be fixed now @JoeDozan24
