### ISSUE TITLE
Problem with qr code.

### ISSUE THREAD

**Issue by LuizFelipeNeves** [smashah/sulla#23]
<h4>I have problem, the qr code is loading forever, the phone can not read the console version, but the browser yes!</h4>
<br/>
<img src='https://i.ibb.co/vkFZpgQ/Captura-de-tela-de-2019-12-01-03-25-55.png'/>

**Comment by smashah** [comment]
If I remember correctly this may be due to contrast issues. Try a dark terminal theme. Possible duplicate of #13
