### ISSUE TITLE
[Enhancement] - Events monitor

### ISSUE THREAD

**Issue by LuizFelipeNeves** [smashah/sulla#24]
- Function to monitor client status, "sulla.ev.on" <br/>
- Add event listener on remove phone session

<img src='https://i.ibb.co/n1g00Hr/Captura-de-tela-de-2019-12-01-12-02-25.png'/>

**Comment by smashah** [comment]
Till this is implemented I suggest polling client.isConnected()

As far as we know now there are no events fired in proper time to indicate that the device is offline. It is always delayed or happens when a message is unable to be sent

**Comment by LuizFelipeNeves** [comment]
Thanks!

**Comment by smashah** [comment]
@LuizFelipeNeves I'm going to close this for now. Thanks.
