### ISSUE TITLE
Seems as though you have been TOS_BLOCKed, unable to refresh QR Code.

### ISSUE THREAD

**Issue by myusuf354** [smashah/sulla#240]
Seems as though you have been TOS_BLOCKed, unable to refresh QR Code. Please see             https://github.com/smashah/sulla#best-practice for information on how to preven            t this from happeing. You will most likely not get a QR Code
(node:4379) UnhandledPromiseRejectionWarning: Error: TOSBLOCK
    at Object.<anonymous> (/var/www/html/wapi/src/controllers/auth.ts:48:36)
    at step (/var/www/html/wapi/src/controllers/auth.ts:33:23)
    at Object.next (/var/www/html/wapi/src/controllers/auth.ts:14:53)
    at fulfilled (/var/www/html/wapi/src/controllers/auth.ts:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:4379) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This             error originated either by throwing inside of an async function without a catch             block, or by rejecting a promise which was not handled with .catch(). To termina            te the node process on unhandled promise rejection, use the CLI flag `--unhandle            d-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejectio            ns_mode). (rejection id: 1)
(node:4379) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre            cated. In the future, promise rejections that are not handled will terminate the             Node.js process with a non-zero exit code.
Session timed out. Shutting down
Error  Protocol error: Connection closed. Most likely the page has been closed.

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>Template!</summary>

```js
(async () => {
//label issue
await githubClient.issues. addLabels({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        labels: ["doesn't follow template"]
      })

 await postComment(`⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.md&title=)⚠️⚠️⚠️`);

//close issue
await githubClient.issues. update({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        state: "closed"
      })
})();
```
</details>

**Comment by smashah** [comment]
⚠️⚠️⚠️[Please follow this issue template](https://github.com/smashah/sulla/issues/new?assignees=&labels=&template=bug_report.md&title=)⚠️⚠️⚠️
