### ISSUE TITLE
Arrow function doesn't look right

### ISSUE THREAD

**Issue by classic-gentleman** [smashah/sulla#241]
https://github.com/smashah/sulla/blob/7f770ea5a2d791db4322eafea9dabf660adb5945/src/api/whatsapp.ts#L409

This is either missing a return statement or has extra curly braces. Upon calling, causes the following error unless fixed: `Argument of type 'void' is not assignable to parameter of type 'string | undefined'.`

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i`);
exec(`npm run release-ci`);

var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [1.8.24](https://github.com/smashah/sulla/compare/1.8.23...1.8.24) (2020-03-27)

- Bump release-it from 13.3.1 to 13.3.2 [`#244`](https://github.com/smashah/sulla/pull/244)
- Release 1.8.24 [`fd52f52`](https://github.com/smashah/sulla/commit/fd52f521a1242fa3a4ac6e254698fc803b98d6c5)
- fix for #241 [`0ce70a6`](https://github.com/smashah/sulla/commit/0ce70a692490e4099a2b6b80e2f6363fd4a524c5)

**Comment by smashah** [comment]
@classic-gentleman it should be working now. Thanks for bringing this to my attention.

**Comment by classic-gentleman** [comment]
Was the log left intentionally? 😅

**Comment by smashah** [comment]
Removed for next release
