### ISSUE TITLE
forward a message issue

### ISSUE THREAD

**Issue by abbassnet** [smashah/sulla#246]
This message appears when trying to forward a message to a chat that has never been sent before
please help

![Capturefw](https://user-images.githubusercontent.com/6605689/77807848-c7a0e280-7091-11ea-88b3-fc288417eaea.PNG)

**Comment by smashah** [comment]
Please make sure you already have a conversation with a contact before trying to send a message.

**Comment by abbassnet** [comment]
How many messages can I send continuously per minute to different contacts without blocking?
How much difference between bulk?
