### ISSUE TITLE
delete chat

### ISSUE THREAD

**Issue by arelxcode** [smashah/sulla#248]
how sulla delete the chat?
i'm using client.deleteMessage but one only message.

![image](https://user-images.githubusercontent.com/54056041/77889356-e8d32000-7297-11ea-9a01-4d0aafdc3fe5.png)

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i`);
exec(`npm run release-ci`);

var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [1.8.28](https://github.com/smashah/sulla/compare/1.8.27...1.8.28) (2020-03-30)

- Release 1.8.28 [`ebff6cb`](https://github.com/smashah/sulla/commit/ebff6cb37a2b1bbced1d7f133868fe7508493a04)
- added `client.deleteChat(...` #248 [`bfc878c`](https://github.com/smashah/sulla/commit/bfc878c8a65d9d039c19057cbcf0581edfc5f828)

**Comment by smashah** [comment]
https://smashah.github.io/sulla/classes/whatsapp.html#deletechat

Please confirm if this worked for you. Thanks

**Comment by arelxcode** [comment]
WORKING NICE WORK:)

**Comment by arelxcode** [comment]
working but have bug in group chat
if successfully delete the chat group.

bot can send message again in that group but the message not showing in other member/phone

**Comment by arelxcode** [comment]
![image](https://user-images.githubusercontent.com/54056041/77949604-6d05c180-72f1-11ea-96a9-da061b9cedf7.png)

group maybe using this function

**Comment by smashah** [comment]
I'm sure that's because once you delete a chat you leave the group. `deleteChat` works as expected. I'm seeing the same behaviour.

Probably a good idea to implement a separate method to clear the chat.

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i`);
exec(`npm run release-ci`);

var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [1.8.29](https://github.com/smashah/sulla/compare/1.8.28...1.8.29) (2020-03-30)

- Release 1.8.29 [`782f77a`](https://github.com/smashah/sulla/commit/782f77a94df56551ad38c26838da7056d77f38d2)
- implemented `clearChat(...` #248 [`36cec39`](https://github.com/smashah/sulla/commit/36cec39a2be0b16b992d4c496ea36ee56838d6b2)

**Comment by smashah** [comment]
@arelxcode you can now try:

https://smashah.github.io/sulla/classes/whatsapp.html#clearchat

**Comment by arelxcode** [comment]
nice working too.

**Comment by arelxcode** [comment]
![image](https://user-images.githubusercontent.com/54056041/78072010-96dde780-73c8-11ea-913c-99ba01d1d62a.png)

client.deleteMessage(  is this?

**Comment by arelxcode** [comment]
@smashah just asked
