### ISSUE TITLE
Group Info

### ISSUE THREAD

**Issue by razisek** [smashah/sulla#253]
**Describe the bug**
get Group Info, like group name, description group

**create() code**
This is the code you use to create the client. e.g
```javascript
sulla.create('SESSION', {executablePath: '/usr/bin/google-chrome-stable'}).then(client => start(client));
```

**Expected behavior**
How sulla can get group info, like group name, description group, and other?

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
  WA_VERSION: '0.4.2081',
  PAGE_UA: 'WhatsApp/0.4.613 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36',
  SULLA_HOTFIX_VERSION: '1.8.26',
  BROWSER_VERSION: 'HeadlessChrome/80.0.3987.149'
}
```
**Host (please complete the following information):**
 - OS: Android

**Additional context**

**Comment by smashah** [comment]
Hi @razisek 

You can get groupMetadata from the chat object itself:

```javascript
    const groupchat = await client.getChatById("44712345678-15555556@g.us");
    console.log("start -> groupchat", groupchat.groupMetadata)
```

https://smashah.github.io/sulla/interfaces/chat.html#groupmetadata
