### ISSUE TITLE
Get group invite link

### ISSUE THREAD

**Issue by tinyCoder32** [smashah/sulla#255]
Hi, is there a way to get the group invite links?

**Comment by smashah** [comment]
great question, I'll look into it.

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i`);
exec(`npm run release-ci`);

var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [1.8.30](https://github.com/smashah/sulla/compare/1.8.29...1.8.30) (2020-03-31)

- Bump release-it from 13.5.0 to 13.5.1 [`#256`](https://github.com/smashah/sulla/pull/256)
- Bump @types/node from 13.9.5 to 13.9.8 [`#257`](https://github.com/smashah/sulla/pull/257)
- Release 1.8.30 [`e8778ce`](https://github.com/smashah/sulla/commit/e8778ce25fc3da1a78f4919f324d755cebb5a3e8)
- added `getGroupInviteLink` #255 [`f2e7bc9`](https://github.com/smashah/sulla/commit/f2e7bc992fbf592b157c0700abf0b83a26803dec)

**Comment by smashah** [comment]
@tinyCoder32 

You can now try: https://api.whatsapp.com/send?phone=447460975810&text=YOUMESSAGE

e.g:

```javascript
const inviteLink = await client.getGroupInviteLink('000000000-0000000000@g.us');
```

let me know if it works for you. Thanks

**Comment by tinyCoder32** [comment]
It works, thank you.
