### ISSUE TITLE
Server restarts

### ISSUE THREAD

**Issue by sanep10** [smashah/sulla#259]
**Describe the bug**
When I scan de QR Code, the local server (started with nodemon) restart. 

**Steps to Reproduce**
1. create the client
2. scan the qr code

**create() code**
```javascript
const sulla = require("sulla-hotfix");
const generatedUa =
      "WhatsApp/0.4.613 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36";
    sulla
      .create(
        "session",
        {
          executablePath: "/usr/bin/google-chrome",
          headless: true,
          autoRefresh: false,
          qrRefreshS: 30 //please note that if this is too long then your qr code scan may end up being invalid. Generally qr codes expire every 15 seconds.
        },
        generatedUa
      )
      .then(async client => this.handleWhatsapp(client));
```

**Expected behavior**
The client without restart the server

**DEBUG INFO**
```
Debug Info { WA_VERSION: '0.4.2088',
  PAGE_UA:
   'WhatsApp/0.4.613 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36',
  SULLA_HOTFIX_VERSION: '1.8.29',
  BROWSER_VERSION: 'HeadlessChrome/80.0.3987.149' }
```

**Screenshots**
![image](https://user-images.githubusercontent.com/46332292/78081636-9caadd00-7376-11ea-91a2-02d195efdb67.png)

**Host (please complete the following information):**
 - OS: Windows10

**Comment by barkerpedro** [comment]
This is because Sulla saves the file 'session.data.json' inside your project's folder.
Try:

`nodemon src/server.js --ignore *.data.json`
