### ISSUE TITLE
Assigning labels to chat

### ISSUE THREAD

**Issue by tinyCoder32** [smashah/sulla#260]
Hi, after a deep search, using WA Business account, I reached the function that labels a specific chat, but I cold not find how to use it, I appreciate your kind help:

`Store.Label.addOrRemoveLabels`

**Comment by tinyCoder32** [comment]
Can you please lead me how to investigate on this?

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i`);
exec(`npm run release-ci`);

var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [1.8.35](https://github.com/smashah/sulla/compare/1.8.34...1.8.35) (2020-04-05)

- Release 1.8.35 [`3820947`](https://github.com/smashah/sulla/commit/38209473f9490210e97ce02b3836b80b835d2872)
- implemented label methods #260 [`a0b183c`](https://github.com/smashah/sulla/commit/a0b183cbbc50c503213a4bec8735d91006c9aadc)
- removed release image on readme - doesnt work as exepcted [`713eb43`](https://github.com/smashah/sulla/commit/713eb4373050997f9dfbd35c68bd9ffc9909d762)
- update readme [`1999e26`](https://github.com/smashah/sulla/commit/1999e26951efc3ca41f4f057483a509d0736d74d)

**Comment by smashah** [comment]
@tinyCoder32 you can now try:

```javascript
//add a label by id
client.addLabel("1", "4477777777777@c.us")

//add a label by name (has to be exact match)
client.addLabel("Paid", "4477777777777@c.us")

//remove label
client.removeLabel("Paid", "4477777777777@c.us")
client.removeLabel("1", "4477777777777@c.us")
```

https://smashah.github.io/sulla/classes/whatsapp.html#addlabel

**Comment by tinyCoder32** [comment]
Thanks, I get `SyntaxError: Unexpected token ','`

**Comment by tinyCoder32** [comment]
Something is wrong here:
`var id = Store.labels.models.find(x=>x.id==label||x.name==label)`

It should be `Store.Label`

And here in the object has something wrong `{id,type}`.

**Comment by smashah** [comment]
try 1.8.37 #278 

Labels are tested and working.

**Comment by tinyCoder32** [comment]
![image](https://user-images.githubusercontent.com/17817239/78519433-ff173980-77cb-11ea-962b-1518e135f13d.png)

![image](https://user-images.githubusercontent.com/17817239/78519458-135b3680-77cc-11ea-9053-d42c543f43a1.png)

Something is still wrong with me, am I missing something?

**Comment by tinyCoder32** [comment]
I am still getting an error:

![image](https://user-images.githubusercontent.com/17817239/78519960-9204a380-77cd-11ea-8395-fbc3a2a7ea1d.png)

So I changed it to `Store.Label.addOrRemoveLabels([[id,type]],[to]);`
I get a `200` response and a message that the chat has been labeled successfully, but it's not, I still see the chat without any labels.

![image](https://user-images.githubusercontent.com/17817239/78520148-40a8e400-77ce-11ea-95b8-f3e7766be54a.png)

**Comment by smashah** [comment]
The reason you're getting an error is that you copied some random code (not what is in wapi) also you have no key for the type. Also it has to be an array of objects,not arrays.
```javascript
[{
id:"1",
type:"add"
}]
```
so
`Store.Label.addOrRemoveLabels([{id,type:'add'}],[to]);` will work.

**Comment by tinyCoder32** [comment]
It worked, thank you so much for the help. You're great.
