### ISSUE TITLE
Revoke group invite links

### ISSUE THREAD

**Issue by razisek** [smashah/sulla#264]
**Expected behavior**
is there a way to revoke the group invite links

**create() code**
This is the code you use to create the client. e.g
```javascript
sulla.create('SESSION', {executablePath: '/usr/bin/google-chrome-stable'}).then(client => start(client));
```

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
  WA_VERSION: '0.4.2088',
  PAGE_UA: 'WhatsApp/0.4.613 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36',
  SULLA_HOTFIX_VERSION: '1.8.30',
  BROWSER_VERSION: 'HeadlessChrome/80.0.3987.162'
}

```

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i`);
exec(`npm run release-ci`);

var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [1.8.31](https://github.com/smashah/sulla/compare/1.8.29...1.8.31) (2020-04-02)

- Bump release-it from 13.5.0 to 13.5.1 [`#256`](https://github.com/smashah/sulla/pull/256)
- Bump @types/node from 13.9.5 to 13.9.8 [`#257`](https://github.com/smashah/sulla/pull/257)
- Release 1.8.31 [`9b8cfa0`](https://github.com/smashah/sulla/commit/9b8cfa0f39402f7f8bca927ae0e1fa3f28b798c3)
- Release 1.8.30 [`e8778ce`](https://github.com/smashah/sulla/commit/e8778ce25fc3da1a78f4919f324d755cebb5a3e8)
- added `getGroupInviteLink` #255 [`f2e7bc9`](https://github.com/smashah/sulla/commit/f2e7bc992fbf592b157c0700abf0b83a26803dec)
- added `revokeGroupInviteLink` #264 [`120cdd9`](https://github.com/smashah/sulla/commit/120cdd95e1b574b671d0fa082d4596db50bb98b0)
- update readme [`477a795`](https://github.com/smashah/sulla/commit/477a795b6caf2cdd60eae4bc029d2a596eaddfbd)

**Comment by smashah** [comment]
@razisek try it out and let me know if it works for you. thanks

https://smashah.github.io/sulla/classes/whatsapp.html#revokegroupinvitelink

Please note, once revoked a link will stop working.

**Comment by razisek** [comment]
It works, thanks
