### ISSUE TITLE
Sending Files and Images

### ISSUE THREAD

**Issue by mrbarnk** [smashah/sulla#266]
sendFile is not working,
I did as instructed by @smashah in the readme file, but still not working.

This is how I read my file to base64 data URL format,

`
var bitmap = fs.readFileSync('/path/to/file/file.ext');
base64Format  = "data:image/png;base64,"+Buffer.from(bitmap, 'base64').toString('base64')
`

and then send the file like this.

`
await client.sendFile(message.from,[base64Format],'filename');
`

**Comment by mrbarnk** [comment]
Anyhelp to this?

**Comment by smashah** [comment]
@mrbarnk did you try `await client.sendFile(message.from,base64Format,'filename,jpg');`?

**Comment by mrbarnk** [comment]
I've been able to fix it, thanks.

I'm trying sendVCard as contact now, but not seeing the function there.

**Comment by smashah** [comment]
Ok I'll close this for now then.
