### ISSUE TITLE
Always offline presence

### ISSUE THREAD

**Issue by tinyCoder32** [smashah/sulla#276]
Hi, thanks for the incredible work so far.
Could anyone find a way to never send the online status to contacts? Like appearing offline all the time?

**Comment by smashah** [comment]
@tinyCoder32 you could set this in the privacy settings of your number.

**Comment by tinyCoder32** [comment]
No, I am not talking about the "Last Seen", I mean being online on the web while appearing offline to others.

**Comment by smashah** [comment]
So you want to make sure the bot doesn't come online while replying to messages? What if the person with the number opens WhatsApp on their phone? There's no way to stop it showing online in that case.

**Comment by tinyCoder32** [comment]
Of course there is no way to do it if we go online from mobile, but at least keep the bot offline always, do you think there is a way?

**Comment by smashah** [comment]
Let me check

**Comment by smashah** [comment]
To be honest, when sending a message via the library, it doesn't come up as online on the recipient's end.

**Comment by tinyCoder32** [comment]
I implemented parts of the library with the web version of WhatsApp, so the bot works in the browser but it always appear as online, do you think we can do something about that, please?

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i`);
exec(`npm run release-ci`);

var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [1.8.34](https://github.com/smashah/sulla/compare/1.8.33...1.8.34) (2020-04-05)

- Release 1.8.34 [`fa947b1`](https://github.com/smashah/sulla/commit/fa947b1f54cdfecfd6d6b9dc1f134f95a6f8826c)
- added `setPresence` #276 [`4a8855a`](https://github.com/smashah/sulla/commit/4a8855af687f60039652de9c30467e5ee2a47e95)
- typo fix [`bc5aa2f`](https://github.com/smashah/sulla/commit/bc5aa2fa1ee73dd4b5e77959038ff6e84e63962b)
- fixed release image sizing [`913f42b`](https://github.com/smashah/sulla/commit/913f42ba8839e9317c1d24ee99e40c1d9b7e3a5d)
- add release image change log [`6a29d04`](https://github.com/smashah/sulla/commit/6a29d044129aef9e4b81ed9c3ee8064510af889e)

**Comment by smashah** [comment]
@tinyCoder32 You can now try setPresence 
https://smashah.github.io/sulla/classes/whatsapp.html#setpresence

```javascript
//remove 'online' from participants phone
await client.setPresence(false)
```

You can put that on some sort of loop + delay to achieve what you want. Please let me know asap if this works for you. thanks

**Comment by tinyCoder32** [comment]
It works, I used it before but i didn't know that there are some other functions calling setPresenceAvailable which returns the status back to online. A loop might work, or even setting setPresenceAvailable to an empty promise function so it never works again.

Thanks.
