### ISSUE TITLE
Transition from Online to Offline not working

### ISSUE THREAD

**Issue by hamid512** [smashah/sulla#279]
**Describe the bug**
This Bug happens when using IsOnline on getChatByID function. using my code it can transition from offline(null) to online dynamically but wont change back to offline if contact goes offline unless i open up the contact chat page on my phone then it updates

**Steps to Reproduce**
1. Run code below and test behaviour

**create() code**
This is the code you use to create the client. e.g
```javascript
const sulla = require('sulla-hotfix');

sulla.create().then(client => start(client));

async function start(client) {
  client.getAllChats(chats=>{
  console.log(chats)
  })
  async function geton() {
    var contact =  await client.getContact("xyz@c.us")
    var chat = await client.getChatById("xyz@c.us")
    
    console.log(chat.isOnline,contact.name);
  }
   setInterval(() => {
    geton()
   }, 1000);

  client.onAnyMessage(message=>console.log(message.type));
  client.onMessage(message => {
    console.log(message)
    if (message.body === 'Hi') {
    
    }
  });
}
```

**Expected behavior**
When Contact is no longer online it 'isOnline' should return to null

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this

**Screenshots**
If applicable, add screenshots to help explain your problem. Use ```headless: false``` to get screenshots

NB: First column is online status.
Can transition from this:

<img width="125" alt="Screen Shot 2020-04-06 at 10 42 AM" src="https://user-images.githubusercontent.com/57622264/78530395-9c866380-77f4-11ea-99a1-043c4044d044.png">

To this:  
<img width="185" alt="Screen Shot 2020-04-06 at 10 46 15 AM" src="https://user-images.githubusercontent.com/57622264/78530289-6fd24c00-77f4-11ea-8c03-9be98e8a5efe.png">
But not backwards unless phone is opened to that contact page

**Host (please complete the following information):**
 - OS: Mac OS

**Additional context**
Trying to add notifications when a user transitions from online to offline or vice versa

**Comment by smashah** [comment]
@github-actions run

<details>
<summary>⚡ Release!  ⚡</summary>

```js
(async () => {
function exec(cmd) {
  console.log(execSync(cmd).toString());
}

// Config
const gitUserEmail = "github-actions[bot]@users.noreply.github.com";
const gitUserName = "github-actions[bot]";

exec(`echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc`);
exec(`git config --global user.email "${gitUserEmail}"`);
exec(`git config --global user.name "${gitUserName}"`);
exec(`npm i`);
exec(`npm run release-ci`);

var result = execSync(`npx auto-changelog -o ./tempchangelog.txt --commit-limit false --template ./compact-keepachangelog.hbs --stdout`).toString();

    await postComment(result);
  })();
```
</details>

**Comment by smashah** [comment]
# Changelog

## 🚀 Release [1.8.38](https://github.com/smashah/sulla/compare/1.8.37...1.8.38) (2020-04-06)

- Release 1.8.38 [`66035dd`](https://github.com/smashah/sulla/commit/66035dd43a9af12a1d92a1694bdddb78b0a839fa)
- added `isChatOnline` #279 [`4c203ea`](https://github.com/smashah/sulla/commit/4c203ea3a7f7cb8b5e56a6bb9c39755fcff24c6b)

**Comment by smashah** [comment]
try this

```javascript
const sulla = require('sulla-hotfix');

sulla.create().then(client => start(client));

async function start(client) {
  client.getAllChats(chats=>{
  console.log(chats)
  })
  async function geton() {
    var contact =  await client.getContact("xyz@c.us")
    var isOnline = await client.isChatOnline("xyz@c.us")
    
    console.log(isOnline,contact.name);
  }
   setInterval(() => {
    geton()
   }, 1000);

  client.onAnyMessage(message=>console.log(message.type));
  client.onMessage(message => {
    console.log(message)
    if (message.body === 'Hi') {
    
    }
  });
}
```

There's a bit of delay but it should work.

https://smashah.github.io/sulla/classes/whatsapp.html#ischatonline

**Comment by hamid512** [comment]
Works fine now thanks
