### ISSUE TITLE
Getting Online Status from new contact Enquiry

### ISSUE THREAD

**Issue by hamid512** [smashah/sulla#283]
@smashah  On Mobile and whatsapp web its possible to see 'Online' status of a **saved contact** without needing to start a chat, can 'isOnline' be added to contact model or rather make 'isChatOnline' work for empty chats as long as contact is saved and valid.

 For Example the image below i can see online status if they do come online without needing to chat 
<img width="996" alt="Screen Shot 2020-04-06 at 1 51 35 PM" src="https://user-images.githubusercontent.com/57622264/78546423-6ce45500-780e-11ea-8205-405a11d01030.png">

**Comment by hamid512** [comment]
for some uses cases you to get status before notifying a new user(contact saved) or if you delete the chat history and it becomes like the above but you stilll need to see online status

**Comment by smashah** [comment]
No. I'm not going to implement a way to creep on random contacts online status. If you want to check someone's online state then start a conversation.

**Comment by hamid512** [comment]
@smashah  this is the result of clearChat or deleteChat , even if its a wellknown contact, thats my point
