### ISSUE TITLE
check if session is still valid from outside?

### ISSUE THREAD

**Issue by ramonck** [smashah/sulla#3]
Hi,

Is there any simple way to check if it's connected and still working after sulla create?
sulla.create().then(client => start(client));

I wanted to check if it's connected but the code is running so how can I check from outside? Can I check in the session folder for something?

**Comment by smashah** [comment]
Hey there,


I have a few ideas for this. As you can see I've implemented an event handler (for grabbing the QR code).

I might set it up so it checks if it's still running every X seconds and if it fails the check it will fire an event.

I'll get on it as soon as I can in the meantime I'd appreciate if anyone can share a better solution :)

**Comment by ramonck** [comment]
I liked this idea, seems to be proactive instead of reactive.

**Comment by smashah** [comment]
@ramonck I think first we need to determine the 'unreactive' states

- Phone is offline
- Battery on phone is low
- Whatsapp web logged in from another computer
- ?

Are there any other 'unreactive' states?

**Comment by smashah** [comment]
@ramonck with the new v1.2.10 you can now call ```client.isConnected()``` to see if the phone is still connected.  This isn't real time though, WhatsApp web takes some time, or a failed sent message, before it realizes that the phone is disconnected. A step in the right direction though, for now.
