### ISSUE TITLE
[Suggestion] To add wrapper for WAPI.getProfilePicFromId

### ISSUE THREAD

**Issue by HypedMind** [smashah/sulla#32]
Actually I tried to add it myself, but it doesn't seem to work. The image url that required credentials can't be downloaded.

**Comment by smashah** [comment]
@HypedMind  can you share the code you're trying.

Also, you can see from here: https://github.com/smashah/sulla/blob/4e00c45a571b07f93687a415b936a4d62e6b7f2e/src/lib/wapi.js#L971

You can access the img url from the chat object.

So if you want you can use the wrapper method for getChatById then go to contact.profilePicThumbObj.imgFull or img like so:


```javascript
await WAPI.getChatById('44123598123@c.us').contact.profilePicThumbObj.imgFull
//OR
await WAPI.getChatById('44123598123@c.us').contact.profilePicThumbObj.img
```

In sulla-hotfix:

```javascript
await client.getChatById('44123598123@c.us').contact.profilePicThumbObj.imgFull
//OR
await client.getChatById('44123598123@c.us').contact.profilePicThumbObj.img
```


Make sure that when you request these files, you are using a user-agent. This was the big blocker for implementing decryption actually. If there was no user-agent then the request would fail. You can check out the decryption implmentation for a request with user-agent here:

https://github.com/smashah/sulla/blob/4e00c45a571b07f93687a415b936a4d62e6b7f2e/src/utils/decrypt.ts#L25

Luckily you do not need to decrypt these profile pic files.

**Comment by smashah** [comment]
Hope the above worked. Closing.
