### ISSUE TITLE
How to hanle error displaying when phone is not online

### ISSUE THREAD

**Issue by mrbarnk** [smashah/sulla#34]
Hello users, Is there any way to hadle the error displaying when I am not online?

I am not online on my phone, but I don't want that to affect my app.

How can I do that?

**Comment by smashah** [comment]
@mrbarnk the phone needs to be online for this to work.

Please see:

https://github.com/smashah/sulla/issues/24#issuecomment-560126039

Closing for now. Thanks.

**Comment by smashah** [comment]
@mrbarnk You can now achieve this. Check it out here:

https://github.com/smashah/sulla/issues/60#issuecomment-578189539
