### ISSUE TITLE
how to detect if someone leave, get kicked,added or join to my group

### ISSUE THREAD

**Issue by xshion13** [smashah/sulla#37]
i want to post a message when an event like this happens, in order to post rules in a group, etc. is possible this?.

**Comment by smashah** [comment]
If it results in some sort of action on the front end then it is technically possible to listen in on it. However some things are just really difficult to reverse engineer (like sending GIFs). I'd suggest maintaining your own db and polling the group participants until this can be figured out.

**Comment by smashah** [comment]
Just for future reference the event to be listened to is ```change:participants```

**Comment by smashah** [comment]
Groundwork:

https://github.com/smashah/sulla/commit/226371eee0e66a7c14d34fea85df2560835b7573

https://github.com/smashah/sulla/blob/79242aaab04fb403201067c807eba2eb369561ad/src/lib/wapi.js#L1260

Please note though, this thing keeps firing. There is an event as mentioned above but that does not hold any data as to who was added/removed.

**Comment by xshion13** [comment]
it seems interesting,, my knowledge about javascript is low but i am very instersted in how to code it, also functions as store images or sent request to php server

**Comment by smashah** [comment]
@xshion13 https://github.com/smashah/sulla#group-participant-changes
