### ISSUE TITLE
Possibility to know that the receiver has read the message.

### ISSUE THREAD

**Issue by GENL** [smashah/sulla#39]
After a message is sent, I want to be able to know that the receiver read or not the message.

**Comment by marcelocecin** [comment]
did you try to monitor the `ack` attribute ?

**Comment by smashah** [comment]
@GENL You can do this now in the latest version (^1.5.3)

Check out how here: https://github.com/smashah/sulla#listen-to-read-receipts

and

https://github.com/smashah/sulla/blob/a87fa6b06be69327f27a5fa42d6b5f54364f9893/demo/index.ts#L29

Related: https://github.com/smashah/sulla/issues/48

Thanks
