### ISSUE TITLE
Get all live locations being shared with client

### ISSUE THREAD

**Issue by smashah** [smashah/sulla#4]
It would be cool if I can have something like:

`client.getLiveLocations()`

to see who is sharing their live locations with me and then subsequently I would be able to provide them with some geographically contextual response.

Notes:
In order to grab live locations from whatsapp web right now you can enter this into the console:

```window.Store.LiveLocation.toJSON().forEach(l=>{console.log(l.participants[0].id._serialized,l.participants[0].lat, l.participants[0].lng,new Date(l.participants[0].expiration*1000))})```

**Comment by marcelocecin** [comment]
I found this two sources that can help

https://github.com/alfred82santa/whalesong/blob/master/examples/getlivelocations-chromium.py

https://github.com/alfred82santa/whalesong/blob/master/examples/getlivelocations.py

**Comment by smashah** [comment]
Note: To see all possible participant events

```javascript
Store.LiveLocation._models[0].participants.validLocations()[0]._definition
```

Also make sure to set active to true on every change:active event.

**Comment by smashah** [comment]
```javascript
Store.LiveLocation._models[0].participants.validLocations()[0].on('change:lastUpdated',(x,y,z)=>{
    const {id,lat,lng,accuracy,degrees,speed,lastUpdated}=x;
const l = {id,lat,lng,accuracy,degrees,speed,lastUpdated};
console.log('newloc',l)
})
```
