### ISSUE TITLE
Send video as gif not working

### ISSUE THREAD

**Issue by kobra101** [smashah/sulla#41]
await client.sendVideoAsGif(message.from, `data:video/mp4;base64,${d4.body}`, `dad.mp4`, "teste")

**Comment by Douglas12ds** [comment]
What a coincidence! I was ready to report this right now! 

Fala aí, anão. Suave?

**Comment by Douglas12ds** [comment]
What a coincidence! I was going to report this right now!

**Comment by happykobra** [comment]
Opa @Douglas12ds beleza, cara não estou conseguindo enviar nenhum sendGiphy, nem sendVideoAsGif, ai também?

**Comment by Douglas12ds** [comment]
> Opa @Douglas12ds beleza, cara não estou conseguindo enviar nenhum sendGiphy, nem sendVideoAsGif, ai também?

Sim. Estava neste exato momento tentando ambos os modos.

**Comment by smashah** [comment]
I'm gonna need some more information. I suggest clearing session and trying. If you have any errors or anything please share that also

**Comment by Douglas12ds** [comment]
> I'm gonna need some more information. I suggest clearing session and trying. If you have any errors or anything please share that also

Tried send the same Giphy as in the demo ( literally copied and pasted ) after clearing session and still don't work. The function don't throws any error, just don't work, silently.

**Comment by smashah** [comment]
Are you sure you are using the latest version (1.4.1)? Can you try the demo via git clone?

**Comment by Douglas12ds** [comment]
> Are you sure you are using the latest version (1.4.1)? Can you try the demo via git clone?

Just tried. Still nothing.

**Comment by smashah** [comment]
Are you using chrome instead of chromium?

**Comment by Douglas12ds** [comment]
Sorry about the dumb question, but how to verify it?

**Comment by smashah** [comment]
Initiate your session with headless:false. Also make sure your executable path points to your installation of chrome. Due to lack of ffmpeg support, video and therefore GIFs don't work on the standard session (i.e with chromium).

```javascript
create('session',{
  executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
headless:false
}).then(client => start(client));

```

**Comment by Douglas12ds** [comment]
It worked! 

Had to specify the absolute Chrome path on Windows. Here is the code.

`sulla.create('session', {
  executablePath: 'C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe',
  headless: false
}).then(cliente => iniciar(cliente))`

I suggest make it explict on readme.md.

Thanks for the support tho.

**Comment by kobra101** [comment]
Thanks working for me too!

**Comment by smashah** [comment]
Thanks all. Closing this
