### ISSUE TITLE
Bug Ubuntu Linux 'eventEmitter2 loader.js error'

### ISSUE THREAD

**Issue by rafael-sarti** [smashah/sulla#42]
Development worked perfectly on OSX, when the production byproduct to run a final test presented a problem 'eventEmitter2 loader.js error'.

I am still exploring what it can be. If anyone has any information as to what this error is occurring. Appreciate!

Congratulations on the project =)

**Comment by smashah** [comment]
thanks, @rafael-sarti for bringing this up. Keep us updated with your investigation.

**Comment by rafael-sarti** [comment]
The installation was performed on Ubuntu and Debian. When the operating system is running on the command line it or Sulla does not work.

The error is always linked

internal / modules / cjs / loader.js: 638
play err;
^

Error: Could not find module 'EventEmitter2'
in Function.Module._resolveFilename (internal / modules / cjs / loader.js: 636: 15)
in Function.Module._load (internal / modules / cjs / loader.js: 562: 25)
in Module.require (internal / modules / cjs / loader.js: 692: 17)
at require (internal / modules / cjs / helpers.js: 25: 18)
in Object. <anonymous> (/root/node_modules/sulla-hotfix/dist/controllers/auth.js:55:23)
in Module._compile (internal / modules / cjs / loader.js: 778: 30)
in Object.Module._extensions..js (internal / modules / cjs / loader.js: 789: 10)
in Module.load (internal / modules / cjs / loader.js: 653: 32)
in tryModuleLoad (internal / modules / cjs / loader.js: 593: 12)
in Function.Module._load (internal / modules / cjs / loader.js: 585: 3)

**Comment by smashah** [comment]
Can you go into the sulla-hotfix folder within node_modules and manually install eventemitter2. That should fix it

**Comment by rafael-sarti** [comment]
I already performed this test and it didn't work :(

**Comment by barkerpedro** [comment]
Hello, I solved this error as follows ...

In the file "node_modules/sulla-hotfix/dist/controllers/auth.js".
Look for the line "var EventEmitter2_1 = require("EventEmitter2");".
And change it to "var EventEmitter2_1 = require("eventemitter2");".
Just put the "require("eventemitter2");" in lowercase to solve.

What is happening is that Ubuntu / Debian is unable to differentiate "eventemitter2" and "EventEmitter2".

Sorry for my English, I'm using Google Translate.

**Comment by rafael-sarti** [comment]
Funcionou! Genial realmente esse era o problema! 
Resolvido. Muito obrigado ;) 

English: It worked! Great indeed that was the problem!
Sorted out. Thank you;)

**Comment by rafael-sarti** [comment]
The proposed fix worked. Modifying module name from EventEmitter2 to eventemitter2. I realized that it really has something to do with some case-sensitive interpretation of NodeJS running in linux environments.

I think it is worth an observation in the readme of the project to help other colleagues.

Big hug and congratulations on the project. I'm studying hard and I want to contribute to the fantastic project.

**Comment by smashah** [comment]
Amazing teamwork all! I will push a new version in a few minutes!

**Comment by smashah** [comment]
@rafael-sarti @barkerpedro Try now with version 1.4.2

**Comment by barkerpedro** [comment]
> @ rafael-sarti @barkerpedro Experimente agora com a versão 1.4.2

We are together on this journey.
Whatever it takes to improve the project, I will always be helping.

I will test 1.4.2 now.

**Comment by barkerpedro** [comment]
> @ rafael-sarti @barkerpedro Experimente agora com a versão 1.4.2

Very good. Worked perfectly.

**Comment by rafael-sarti** [comment]
We are always together! I will test =)
I thank everyone. Hug!

**Comment by smashah** [comment]
Great I'll close this for now then!
