### ISSUE TITLE
 UnhandledPromiseRejectionWarning: Error: Page crashed!

### ISSUE THREAD

**Issue by dogcalas** [smashah/sulla#44]
The following error occurs randomly without any apparent reason.
```
whatsapp_1  | (node:1) UnhandledPromiseRejectionWarning: Error: Page crashed!
whatsapp_1  |     at Page._onTargetCrashed (/app/node_modules/puppeteer/lib/Page.js:216:24)
whatsapp_1  |     at CDPSession.Page.client.on.event (/app/node_modules/puppeteer/lib/Page.js:124:56)
whatsapp_1  |     at CDPSession.emit (events.js:198:13)
whatsapp_1  |     at CDPSession._onMessage (/app/node_modules/puppeteer/lib/Connection.js:200:12)
whatsapp_1  |     at Connection._onMessage (/app/node_modules/puppeteer/lib/Connection.js:112:17)
whatsapp_1  |     at WebSocketTransport._ws.addEventListener.event (/app/node_modules/puppeteer/lib/WebSocketTransport.js:44:24)
whatsapp_1  |     at WebSocket.onMessage (/app/node_modules/ws/lib/event-target.js:120:16)
whatsapp_1  |     at WebSocket.emit (events.js:198:13)
whatsapp_1  |     at Receiver.receiverOnMessage (/app/node_modules/ws/lib/websocket.js:789:20)
whatsapp_1  |     at Receiver.emit (events.js:198:13)
whatsapp_1  |     at Receiver.dataMessage (/app/node_modules/ws/lib/receiver.js:422:14)
whatsapp_1  |     at Receiver.getData (/app/node_modules/ws/lib/receiver.js:352:17)
whatsapp_1  |     at Receiver.startLoop (/app/node_modules/ws/lib/receiver.js:138:22)
whatsapp_1  |     at Receiver._write (/app/node_modules/ws/lib/receiver.js:74:10)
whatsapp_1  |     at doWrite (_stream_writable.js:415:12)
whatsapp_1  |     at writeOrBuffer (_stream_writable.js:399:5)
whatsapp_1  |     at Receiver.Writable.write (_stream_writable.js:299:11)
whatsapp_1  |     at Socket.socketOnData (/app/node_modules/ws/lib/websocket.js:864:35)
whatsapp_1  |     at Socket.emit (events.js:198:13)
whatsapp_1  |     at addChunk (_stream_readable.js:287:12)
whatsapp_1  |     at readableAddChunk (_stream_readable.js:268:11)
whatsapp_1  |     at Socket.Readable.push (_stream_readable.js:223:10)
whatsapp_1  | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 10)
whatsapp_1  | (node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

This error doesn't kill the node process, so the container never restart and, therefore, the bot stop working.
Can you help me find why this error occurs?

**Comment by smashah** [comment]
Hmm, not clear from this error log. Can you try to recreate it by resending the last message that was not received by sulla?

**Comment by dogcalas** [comment]
There is not received message by sulla when the error comes up. I am monitoring on my phone all received message, and I notice the failure because the bot is not responding on an user message. From the last sent message by the bot to the error time there is a difference of 5 hours. The message without response came 8 hours later.

I need that if it fails, at least close the process to restart the container.

**Comment by mrbarnk** [comment]
Yea @dogcalas , same here. if it can crash the container and reload it. It would have been awesome.

**Comment by smashah** [comment]
I'd love to add the functionality, I just need to be able to recreate the issue

**Comment by mrbarnk** [comment]
``
whatsapp_1  | (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 10)
whatsapp_1  | (node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
``

**Comment by mrbarnk** [comment]
Maybe there will be a watcher to let you know if the page has crashed. @smashah 

I don't know any solution after that.

**Comment by smashah** [comment]
Possibly this ? https://github.com/puppeteer/puppeteer/issues/1030

**Comment by mrbarnk** [comment]
maybe so.

**Comment by mrbarnk** [comment]
@smashah  you can check this out. https://stackoverflow.com/questions/57956697/unhandledpromiserejectionwarning-error-page-crashed-while-using-puppeteer

**Comment by smashah** [comment]
@mrbarnk can you share your code so I can figure out how to reproduce this.

**Comment by mrbarnk** [comment]
I read your best practice, and I've tried adding await to all my codes now, let see how this goes.

Thanks @smashah

**Comment by smashah** [comment]
@mrbarnk @dogcalas in v =1.6.6 you can now use client.kill() 

This way you can control when a session is destroyed upon catch statements  

e.g

```javascript
...
try{
...
await client.sendMessage(...
...
} catch(error){
client.kill();
//maybe restart the session then
}
```

https://github.com/smashah/sulla/issues/68#issuecomment-578819782

Hope that works for you. I'll close this for now. thanks

**Comment by dogcalas** [comment]
Before write this issue all my awaits calls was between try-catch. Although, I still receiving this error, and never a catch section is executed. After 5 days without problems, boom, it happened again. Most weird is that the trace doesn't show any **sulla** files.

Just to know, what nodejs version are you using? I am using node:10-slim docker image. 
@mrbarnk are you using WebSockets to do others things in your code?

**Comment by mrbarnk** [comment]
I use express along side with it.

So, they bot listen to same port.

**Comment by smashah** [comment]
From the error code, you can see that this error is happening `onMessage` so maybe you should try something like:

```javascript
try{
client.onMessage(message=>{...})
} catch(error){
client.kill();
//maybe restart the session then
}
```

**Comment by mrbarnk** [comment]
I'm using `client.sendText()`.

Please, guide me on this you posted.

**Comment by mrbarnk** [comment]
And again on the latest version, please set auto-refresh QR code to option.

So, we that do not need it will not be affected, sir.

Thanks!

**Comment by smashah** [comment]
@mrbarnk in v1.6.10 you can now set `autoRefresh:false` when you start sulla.

https://github.com/smashah/sulla/blob/629f75969416cc4cf6c58cf45b004db1c9240e49/demo/index.ts#L108

**Comment by dogcalas** [comment]
@smashah Today in the morning I received the same error, and sulla stop receiving messages. The only reason I can figure out, is a today change  in whatsapp version.
I have noticed in my web browser when whatsapp is updated, this messages comes up. 
![image](https://user-images.githubusercontent.com/2521769/74175731-61a4ec80-4c04-11ea-968f-38ddb34686da.png)
Could this be the issue cause?

**Comment by smashah** [comment]
@dogcalas possibly. Over the last 2 days they released version 0.4.613. Is it ok when u restart?

**Comment by dogcalas** [comment]
Yes, it's ok, when I restart everything is working normally.

**Comment by mrbarnk** [comment]
When you run the sulla-hotfix on a server, after some hours or days, it goes crash! I don't seem to understand that.

and I think this is the possible fix for the problem sir.
 
> https://stackoverflow.com/questions/57956697/unhandledpromiserejectionwarning-error-page-crashed-while-using-puppeteer

**Comment by mrbarnk** [comment]
Or in from the whatsapp.ts or initializer.ts, whichever one what works,  the class should have a method that kills the session and restarts it automatically. 

`public async reload() {
    console.log('Restarting node');
    if (!this.page) await this.kill();
    this.create(globalSession,globalpuppeteerConfigOverride,globalcustomUserAgent)
return true;
`
Then the `globalSession`, `globalpuppeteerConfigOverride` and `globalcustomUserAgent` would have been stored when the create function was initaly initialized by us.

So like `export async function create` would be changed to

`
let globalSession,globalpuppeteerConfigOverride,globalcustomUserAgent;

export async function create(sessionId?: string, puppeteerConfigOverride?:any, customUserAgent?:string) {
  if (!sessionId) sessionId = 'session';
     globalSession = sessionId
     globalpuppeteerConfigOverride = puppeteerConfigOverride
     globalcustomUserAgent = customUserAgent
`

I think with this, the problem should be solved @smashah

**Comment by mrbarnk** [comment]
I saw something now,  

like you have it in create function, 
```
    spinner.fail('The session is invalid. Retrying')
    await kill()
    return await create(sessionId,puppeteerConfigOverride,customUserAgent);
```

You can just implement this in the public async reload() function we just want to create.
