### ISSUE TITLE
forward Message

### ISSUE THREAD

**Issue by marcelocecin** [smashah/sulla#46]
hi there
please consider to implement forward Message function
thanks

https://github.com/mukulhase/WebWhatsapp-Wrapper/issues/581
https://github.com/mukulhase/WebWhatsapp-Wrapper/pull/494/files

**Comment by smashah** [comment]
Ready. Should be up in about an hour

**Comment by smashah** [comment]
@marcelocecin Implemented in v1.5.1

https://github.com/smashah/sulla/blob/a5d7a11c658a09ca815b38e1e634d01376e106e0/demo/index.ts#L59

**Comment by smashah** [comment]
https://github.com/smashah/sulla#forward-messages
