### ISSUE TITLE
Event on qr not working any longer

### ISSUE THREAD

**Issue by mrbarnk** [smashah/sulla#47]
Hi, my qr code catcher is no longer working after updating my npm.

`ev.on('qr', async qrcode => {
      console.log(qrcode)
})
`

**Comment by smashah** [comment]
Hmmm @mrbarnk can you try

```ev.on('qr.**',```

**Comment by mrbarnk** [comment]
I tried that, qr never load.

**Comment by mrbarnk** [comment]
Qr code taking forever to load. Been debugging since morning.

**Comment by mrbarnk** [comment]
I think it has to do with my cache or browser, it's working now. Thanks.
