### ISSUE TITLE
Callback when message status update

### ISSUE THREAD

**Issue by marcelocecin** [smashah/sulla#48]
`Store.Msg.on("change:ack", c => console.log(c))`

**Comment by smashah** [comment]
Have you tested this in browser? Is c the message?

**Comment by marcelocecin** [comment]
not yet, but I get from here https://github.com/mukulhase/WebWhatsapp-Wrapper/issues/669

**Comment by smashah** [comment]
Works well.

1 => Message Sent (1 tick)
2 => Message Received by Recipient (2 ticks)
3 => Message Read Receipt Confirmed (2 blue ticks)

```javascript
Store.Msg.on("change:ack", c => console.log(c.id.toString(),c.body,c.ack))
```

Note: You won't get 3 if the recipient has read receipts off.

**Comment by smashah** [comment]
Done, tested, closing, thanks

https://github.com/smashah/sulla#listen-to-read-receipts
