### ISSUE TITLE
LOADING QR 

### ISSUE THREAD

**Issue by rafael-sarti** [smashah/sulla#49]
@smashah You have now stopped loading QR CODE

![Captura de Tela 2020-01-16 às 6 10 32 PM](https://user-images.githubusercontent.com/59804684/72563136-c9794900-388b-11ea-94b9-af6f3e83425c.png)

**Comment by phantom-limb** [comment]
check it out:
https://github.com/smashah/sulla/pull/50/commits/da482da152467bf305f8ed86e6ff929074bcf841

**Comment by rafael-sarti** [comment]
failed :(

**Comment by andersomsousa1406** [comment]
for min stopped loading QR CODE

**Comment by fernandolcardoso** [comment]
Thanks @phantom-limb, works!

**Comment by habibshahid** [comment]
After applying the change of commit #da482da

qrCode image is not in base64 i guess and that is the reason not able to save to a .png file to export to a webpage. can you help. The following piece of code is giving error while converting the qrcode response to base64. qrcode is NULL

``ev.on('qr.**', async (qrcode,sessionId) => {
  console.log("TCL: qrcode,sessioId", qrcode,sessionId)
  //base64 encoded qr code image
  const imageBuffer = Buffer.from(qrcode.replace('data:image/png;base64,',''), 'base64');
  fs.writeFileSync(`qr_code${sessionId?'_'+sessionId:''}.png`, imageBuffer);
});``

![image](https://user-images.githubusercontent.com/2361125/72617875-c2217080-395b-11ea-8103-7208c10d2585.png)

**Comment by phantom-limb** [comment]
@habibshahid, see: https://github.com/smashah/sulla/pull/50

**Comment by rafael-sarti** [comment]
Que estranho!

**Comment by rafael-sarti** [comment]
A rather strange business that my project runs on NodeJS so the installation of sulla is done through npm i sulla.

If I enter inside node_modules and select this commit the error displayed is Error: Cannot find module 'sulla'

Is there a trick to importing the commit correctly?

**Comment by smashah** [comment]
Fix is live

Please make sure you are using ^1.5.5.

@rafael-sarti  sulla is the original project, this is sulla-hotfix. Use this to install.

```javascript
npm i sulla-hotfix
```


Thanks all for bringing this up and wroking through it. MVP of the day is @phantom-limb !

**Comment by habibshahid** [comment]
Thank you Gents.

**Comment by joaomirandasa** [comment]
Thank you @phantom-limb works for me too!
