### ISSUE TITLE
It's possible to send a link with thumb?

### ISSUE THREAD

**Issue by joaomirandasa** [smashah/sulla#51]
I'am trying to send an link with thumbnail but i realize this functions does not exist yet in library, anyone already develop this function by ourselves? I've tried to send but don't know why not function properly, someone can help me?

i see function `WAPI.sendMessageWithThumb` already exist but i did not realize how to use that, look my attempt of develop:

`Whatsapp.prototype.sendMessageWithThumb = function (to, thumb,url,title,description) {
        return __awaiter(this, void 0, void 0, function () {
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0: return [4, this.page.evaluate(function (_a) {
                            var to = _a.to, thumb = _a.thumb, url = _a.url, title = _a.title, description = _a.description;
                            return WAPI.sendMessageWithThumb(thumb, url, title, description, to);
                        },{ to: to, thumb: thumb, url: url, title: title, description: description })];
                    case 1: return [2, _a.sent()];
                }
            });
        });
    };`

![Captura de Tela 2020-01-19 às 18 20 55](https://user-images.githubusercontent.com/29043431/72688690-7bad4c80-3ae8-11ea-8c6a-a4847cc28d73.png)

#Edit
Making a screen capture from puppeteer and this is showed
![Captura de Tela 2020-01-19 às 18 23 23](https://user-images.githubusercontent.com/29043431/72688756-258cd900-3ae9-11ea-97c7-1cf1befeccf5.png)

in a file: _whatsapp.js_

**Comment by smashah** [comment]
Sure I'll implement this thanks

**Comment by smashah** [comment]
@joaomirandasa In v1.5.7 you can now use ```await client.sendMessageWithThumb(...```

I haven't been able to test it so this is alpha right now.

Check it out here:

https://github.com/smashah/sulla/blob/d311658fe5a74eb9a77c3a17b169bb270973a281/src/api/whatsapp.ts#L36

Please let me know if this works.

Thanks

**Comment by joaomirandasa** [comment]
✅ Awesome, it worked! 

I just make modifications on my code, **thumb field is an base64 string without mime type** and identification so i decode string an remove this parts using this function:

`global.base64MimeType = function (encoded) {
  var result = null;
  if (typeof encoded !== 'string') {
    return result;
  }
  var mime = encoded.match(/data:([a-zA-Z0-9]+\/[a-zA-Z0-9-.+]+).*,.*/);
  if (mime && mime.length) {
    result = mime[1];
  }
  return result;
};`

![Captura de Tela 2020-01-20 às 18 13 20](https://user-images.githubusercontent.com/29043431/72758098-93500800-3bb0-11ea-83fd-f9717b3914f1.png)


**So this way i can call function like:** 
![Captura de Tela 2020-01-20 às 18 15 19](https://user-images.githubusercontent.com/29043431/72758184-db6f2a80-3bb0-11ea-9de8-45f3a4a516a3.png)

**Comment by joaomirandasa** [comment]
Closing, this issue because solution is implemented, @smashah please add **send Link** into Readme.md
