### ISSUE TITLE
Decrypting Media

### ISSUE THREAD

**Issue by phantom-limb** [smashah/sulla#52]
**Describe the bug**
decryptMedia() function is not working.

**sulla-hotfix version**
1.5.7

**Whatsapp version**
0.4.315

**Comment by smashah** [comment]
I was also having issues with decrypt media and decided to hardcode the WhatsApp user agent into it.

**Comment by arturromaorocha** [comment]
ua = useragentOverride || 'WhatsApp/2.16.352 Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.0.2990 Safari/537.36';
            
PT-BR
minha solução foi essa!

**Comment by phantom-limb** [comment]
I fix liked this: 

`decryptMedia(message, 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) WhatsApp/0.4.315 Chrome/69.0.3497.128 Electron/4.1.4 Safari/537.36')`

@smashah see:

![Captura de tela em 2020-01-21 15-05-16](https://user-images.githubusercontent.com/58053798/72836824-1d10db80-3c6c-11ea-864a-897a7e339624.png)

![image](https://user-images.githubusercontent.com/58053798/72836955-68c38500-3c6c-11ea-8b74-de44d876cd2e.png)

**Comment by smashah** [comment]
Wow thanks for the screenshots @phantom-limb I'll use the same technique to keep up to date on wa user agents going forth. I'll check to WhatsApp code to see if there's an OS check outside the user agent.

**Comment by smashah** [comment]
@phantom-limb https://github.com/smashah/sulla#issues-with-decyption
