### ISSUE TITLE
API HTTP REQUEST

### ISSUE THREAD

**Issue by barkerpedro** [smashah/sulla#55]
Hello. Can you add "sulla-hotfix" on an API nodejs to make HTTP requests?
Could you explain to me how to be part of "function start (client) {}", for example.
To try to add an API, but it has the following error "client is not defined".

**Comment by smashah** [comment]
Well you would run that start function after the client is created using

```javascript
sulla.create().then(client => start(client));
```

What I do is define a global variable in the start function which I can then access via other methods.

```javascript
const sulla = require('sulla-hotfix');

const express = require('express')
const app = express()

let globalClient = {};
sulla.create().then(client => start(client));

function start(client) {
globalClient = client;
  client.onMessage(message => {
    if (message.body === 'Hi') {
      client.sendText(message.from, '👋 Hello from sulla!');
    }
  });
}

app.get('/getAllUnreadMessages', (req, res) => {
const newMessages = await client.getAllUnreadMessages();
return res.send(newMessages)
})

app.post('/sendText' , (req,res) => {
const {message} = req.body;
      await client.sendText(message.from, message.body);
return res.send(true);
}}

```

**Comment by barkerpedro** [comment]
Thank you my friend.
I managed to solve by adding:

function start (client) {
   global.client = client;
   ...........
}

Excellent work, I am always accompanied by this project.

**Comment by barkerpedro** [comment]
When I run "client.getAllUnreadMessages();" it normally reads unread messages, but it does not update and continues sending those that have already been read.

**Comment by smashah** [comment]
@barkerpedro I've edited the code (added async). That should work now

**Comment by barkerpedro** [comment]
It still keeps showing the messages already read.

**Comment by gnadelwartz** [comment]
will the Messages marked as read automagically if message is processed by on.message?
or must we set message to read explicitly by something like message.read()?

**Comment by smashah** [comment]
@gnadelwartz it's set to read automatically

**Comment by smashah** [comment]
Closing this for now thanks.
