### ISSUE TITLE
Session closed. Most likely the page has been closed.

### ISSUE THREAD

**Issue by FarazPatankar** [smashah/sulla#57]
**Describe the bug**
So I've been using the library for a while and it works pretty well except for a few issues here and there but I've been running into an issue today which I can't seem to resolve.

I do something along these lines and it suddenly stopped working today.
```
let whatsappClient = null;

create().then(client => {
  whatsappClient = client;
  start(client);
});

app.post("/webhook", async (req, res) => {
  const message = getMessage();
  if (whatsappClient) whatsappClient.sendText(TEST_ID, message);

  res.sendStatus(200);
});
```

When it gets to the point where it has to send the message, I see the error mentioned in the title of this issue.

Surprisingly, this started happening today even though I didn't change any versions or anything at all. I also tried updating to the latest version and that did not help. Any idea as to what I can do to fix this?

**Comment by FarazPatankar** [comment]
Looking at the logs, it seems to be happening here - https://github.com/smashah/sulla/blob/master/src/api/whatsapp.ts#L121

**Comment by smashah** [comment]
@FarazPatankar can you run it ```headless :false``` and let me know what is the method to reproduce this issue.

Learn how here:
https://github.com/smashah/sulla#best-practice

Also make sure to await the sendText method.

**Comment by FarazPatankar** [comment]
Using `await` seems to fix the issue. I guess we should go ahead and close this?

**Comment by smashah** [comment]
Great news @FarazPatankar !
