### ISSUE TITLE
Send Message to new Contact

### ISSUE THREAD

**Issue by gildastema** [smashah/sulla#6]

**Comment by gildastema** [comment]
function start(client) {
    client.onMessage(message => {
        client.sendText(message.from, "👋 Hello from APi");
    })

  

    app.post("/send", (req, res) =>{
    
              client.sendText(req.body.receivers+'@c.us', req.body.content)
              .then(()=>{
                res.json({ status: 200});
              } )
              .catch(err => {
                  res.json({status:400})
              })
           
       
     
    })      
}

**Comment by smashah** [comment]
I'm almost completely certain you can't instantiate a conversation with someone you don't already have a conversation through this system. If you want to start a conversation with someone please do it manually or encourage your users to start a conversation with you through the whatsapp api link e.g

https://api.whatsapp.com/send?phone=${NUMBER}&text=Hi there, I just checked out your website and would love to try out this service for free!! :D


I will not be putting effort into creating tools that may be abused to spam people and eventually result in this workaround being blocked or patched.
