### ISSUE TITLE
not getting any trigger when user logout from mobile device or block whatsapp number due to multiple messages

### ISSUE THREAD

**Issue by jigipatel** [smashah/sulla#60]
Hello,
i'm not getting any trigger when user logout from mobile device or block whatsapp number due to multiple messages. i wanted to notify when certain scenario occur will you please suggest what should i do and how will i get those trigger.

Thank You.

**Comment by smashah** [comment]
I'll have to look into this. I'm more confident on setting up events so this would be a good one to get done soon.

**Comment by smashah** [comment]
I've implemented onStateChanged in version 1.6.0

```javascript
  //Returns 'CONNECTED' or 'TIMEOUT'
  client.onStateChanged(state=>console.log('statechanged', state));
```

**Comment by smashah** [comment]
Actually I'm going to leave this open for now. Let me know how it goes for you @jigipatel

**Comment by jigipatel** [comment]
it's throwing error 'TypeError: client.onStateChanged is not a function'

**Comment by jigipatel** [comment]
![my code](https://user-images.githubusercontent.com/33049650/73122067-574ce680-3fa6-11ea-977e-f8136ff53dad.png)

this is screenshot of my code i'm using node npm package sulla-hotfix

**Comment by smashah** [comment]
@jigipatel make sure you are using the latest version.

**Comment by jigipatel** [comment]
Thank you @smashah .
now it's working, i haven't restarted node server that's why i was getting this error

**Comment by smashah** [comment]
Great glad it's working for you now. Thanks for the suggestion.
