### ISSUE TITLE
Can i get messages from me? [Get help]

### ISSUE THREAD

**Issue by tatosjb** [smashah/sulla#61]
I have noticed that the messages a i send from my smartphone does not calls the onMessage callback. 

How can i listen that?

**Comment by smashah** [comment]
hmmm, any reason you'd want to do that @tatosjb ? Maybe there is another solution for your end goal.

**Comment by tatosjb** [comment]
Imagine that i want to integrate this with one chat, to work like the whatsapp, but for teams. A team could send and receive those messages, even if it was sent from smartphone.

Other use for that is automation, if I send the message, the automation will never work, just it other send it. I have noticed, that some apis send that as `fromMe: Boolean` parameter on the message.

I could do this, but I not understood pretty much how this works behind the scenes.

**Comment by smashah** [comment]
@tatosjb in v1.6.1 you can now use ```client.onAnyMessage(async message => {...```

Let me know how it goes for you.
