### ISSUE TITLE
Refresh QRCode

### ISSUE THREAD

**Issue by ramonck** [smashah/sulla#62]
Hi,

The qrcode is valid only for 15-20 seconds, is there a way to keep on refreshing the image generated? 
`ev.on('qr.**',`
or refresh the qr on the terminal?

**Comment by smashah** [comment]
Yes there is a way I found out how to do it.

I added the procedure as a note here:
https://github.com/smashah/sulla/blob/8906c994979b1a0f24b792155f8ea02aee2c6131/src/lib/wapi.js#L85

It's on the todo list.

**Comment by smashah** [comment]
@ramonck great news! Auto refresh qr code is now implemented in v1.6.2 It will refresh the qr code continuously every 10 seconds. Please test it out and let me know how it goes!

Thanks for choosing sulla-hotfix.

**Comment by ramonck** [comment]
@smashah it's working great! Terrific!
The only bug I noticed on Windows 10 was on the first time after authenticating I was not able to use the API, had to shutdown and restart with the session then it worked fine.
