### ISSUE TITLE
How to call isAuthenticated function?

### ISSUE THREAD

**Issue by mmc16** [smashah/sulla#63]
I can't call this function as  `sulla.isAuthenticated`, probably because it's not being exported in "index.ts".

The error message that I get is:

> UnhandledPromiseRejectionWarning: TypeError: sulla.isAuthenticated is not a function

**Comment by smashah** [comment]
What are you trying to achieve? isAuthenticated is not a function of client and not exposed outside of the puppeteer set up.

**Comment by mmc16** [comment]
I’m trying to integrate whatsapp with a web platform my team is developing. It uses ajax requests to communicate with sulla/whatsapp.
The issue I am facing is in the login request. If the qr code event is fired, the image is sent to the client as the response. But if it is not fired, I would like to check whether the client is already connected or there was an error.

**Comment by smashah** [comment]
@mmc16 try client.isConnected() or https://github.com/smashah/sulla/issues/60#issuecomment-578189539

**Comment by mrbarnk** [comment]
Hello @smashah can I create another session without it tampering with the working one?

For example, multi-session can be created like this.

`sulla.create('session').then(client => start(client)).catch()`
`sulla.create('session_2').then(client => start(client)).catch()`
 await ev.on('qr.**', async (qrcode,sessionId) => {
            console.log(sessionId)
             console.log('qrcode') 
       })
`

Now, can I created `session_2` while the session remain uninterrupted?.

Thanks!

**Comment by smashah** [comment]
@mrbarnk yes thats fine

**Comment by smashah** [comment]
Closing this for now. Thanks
