### ISSUE TITLE
QR Code no capturing

### ISSUE THREAD

**Issue by mrbarnk** [smashah/sulla#64]
This codes
`const { ev, create, Whatsapp, decryptMedia } = require('sulla-hotfix')`

`await  ev.on('qr', async qrcode => {
 console.log(qrcode)
})`
and
`await  ev.on('qr.**', async qrcode => {
 console.log(qrcode)
})`

is not capturing the qr code.

**Comment by smashah** [comment]
@mrbarnk please make sure you are using the latest version of sulla-hotfix (v1.6.1) and going forward use the issue template. I have just tested the code in the demo folder and it is working as expected.

**Comment by mrbarnk** [comment]
Thanks very much, I used `await` on `sulla.create` while the `ev.on('qr.**` was after the create.

This means it must finish authenticating before capturing the QR code.

I hope it helps someone anyway.
