### ISSUE TITLE
client.onStateChanged - restart issue

### ISSUE THREAD

**Issue by jigipatel** [smashah/sulla#65]
Hello,

i want to create new QR code image on client.onStateChanged if status is UNPAIRED or CONFLICT but,

when i first get UNPAIRED or CONFLICT it will give me new QRcode. if status changed to UNPAIRED or CONFLICT twice i'm not getting any QR code.

so, i called sulla.create().then(client => start(client)); on status changed to  UNPAIRED or CONFLICT in that case not getting sulla.ev.on('qr.**', qrcode => {}); trigger. please suggest me something to handle this scenario.

Thank You.

**Comment by smashah** [comment]
@jigipatel can you do a screen recording of what is going on please

**Comment by jigipatel** [comment]
Hello @smashah, will you please check by your self i have attached demo code below

- it has unexpected behaviour in different scenario like

[sulla-hotfix-demo.zip](https://github.com/smashah/sulla/files/4116122/sulla-hotfix-demo.zip)

1. if i don't scan first QR code it will generate another QR code after few seconds that is awesome but if i scan 2nd or 3rd QR code then stop receiving onStateChanged trigger
2. if i scan 1st QR code it will give onStateChanged trigger after then i logged out from mobile device and getting new QR code. if i logged out again it will not giving me new QR code on 2nd time (same behaviour  in CONFLICT case)

i really appreciate your response on my issue.
Thanks a lot

**Comment by smashah** [comment]
@jigipatel conflict occurs when whatsapp web is opened somewhere else. You can now use forceRefocus()

https://github.com/smashah/sulla/issues/69#issuecomment-578830306

**Comment by jigipatel** [comment]
now i'm getting new error from puppeteer and sulla-hotfix
![puppeteer error](https://user-images.githubusercontent.com/33049650/73245427-34067f00-41d2-11ea-9b36-0865d2f99cd5.png)

i have just checked that puppeteer has updated npm before 17 hours 

should i go with old puppeteer npm package or sulla-hotfix is depending on new puppeteer update

**Comment by jigipatel** [comment]
now i'm getting new puppeteer and sulla-hotfix error
![puppeteer error](https://user-images.githubusercontent.com/33049650/73246921-c5c3bb80-41d5-11ea-9b69-1b1d6b95f7a9.png)

i have just checked puppeteer has updated npm package before 18 hours and it's blocking new sulla-hotfix Initialization 

does new update of sulla-hotfix  is depend on new update of puppeteer ?

**Comment by dogcalas** [comment]
Same problem. If I restart my docker container, that error come out. I have to destroy the container, and delete session folder to make it work again.

**Comment by jigipatel** [comment]
also, not getting onStateChanged trigger on connect, conflict, logged out(unpaired) feel like previous version was better at catching those triggers or may be getting issue because of puppeteer package update.

also it will be great if QR code regenerate after 30 seconds rather than every 10 seconds

**Comment by smashah** [comment]
This new issue you lot are seeing is Related to #71 not this issue. Please discuss there

**Comment by smashah** [comment]
I have no idea why this is happening it is extremely weird. However, this happens even when autoRefresh is off if you wait a long time to scan the code. This may be related to puppeteer itself.

**Comment by smashah** [comment]
@jigipatel @dogcalas I have implemented a procedure in  v.1.6.15 that automatically restarts the creation of the client if it detects that the session is invalid for sulla-hotfix to operate properly.
![image](https://user-images.githubusercontent.com/5903821/73475358-1aa73380-4388-11ea-9a78-a32a3977f2ed.png)
