### ISSUE TITLE
Listen when the current client session looses the focus.

### ISSUE THREAD

**Issue by GENL** [smashah/sulla#66]
When we scan the qr code with a whatsapp acccount, sulla creates a session and can play with that session. But when we use the same whatsapp account in another web browser, chromium looses his session (normal). I want to know if it is possible to implement a listener on a client that triggers each time his sulla session looses the focus.

**Comment by smashah** [comment]
Yes I'm sure there's a way to do this

**Comment by smashah** [comment]
duplicate #1
