### ISSUE TITLE
Kill the session if it's not connected

### ISSUE THREAD

**Issue by ramonck** [smashah/sulla#68]
Hi @smashah ,

I was wondering about multiple sessions situation if I can close the session if it's not connected. I'm just not sure what to call if it's not connected, was thinking about it like this sort of, not sure because you're the guru :).
What do you recommend too, do you think it's worth to try to reload the session just one more time and if not then really kill it? Do you think this is possible in another way? What do you think?
`const isConnected = await client.isConnected();
    if(!isConnected){
      //sulla.kill('another_session');
    }`

**Comment by smashah** [comment]
That's a good idea. I'll add it to the board.

**Comment by smashah** [comment]
Sulla does not keep track of the sessions you create so you'll need to call kill() on a specific client. You will need to manage your sessions yourself

**Comment by ramonck** [comment]
I was wondering here in puppeeteer if I kill a pid it will kill that tab only with that session or will it kill all of Chrome and the other sessions subquently? I'm going to test here the process kill scenario and see how it works with the multi session situation.

**Comment by smashah** [comment]
@ramonck check out the commit ^

client.kill() will kill the sessions page and browser.

More than 1 sulla-hotfix instance cannot run in the same session/browser due to limitations from whatsapp web.

Every session id creates it's own (kinda) containerized browser and therefore page.

https://github.com/smashah/sulla/blob/172643103e2c9267b94f4c00ca8468d2f747dadd/demo/index.ts#L36

This is now live in v1.6.4

**Comment by ramonck** [comment]
@smashah ,
Nice That's what I used to sort of think because in a regular browser we're not able to do this so it makes total sense to me now to be in a different instance to be able to manipulate the different sessions. That's why I said you're the guru you know better haha.
Thanks for the quick implementation! You're the man!
Best on Github!
I was working with process ids and I was thinking it made more sense to be inside the library so others can benefit from it too.

**Comment by smashah** [comment]
My pleasure, keep the great ideas coming!
