### ISSUE TITLE
Sulla.create opens a blank page when it is called when the browser is already open

### ISSUE THREAD

**Issue by GENL** [smashah/sulla#69]
Scenario:
When I start the server for the first time and call sulla.create(), it automatically authenticates the client. Then during the working session of the server, I call sulla.create another time it opens a browser tab "about:blank". As a result, I need to scan the qr code again. Is this a bug or how can I avoid it?

![image](https://user-images.githubusercontent.com/36866702/73171754-cdb22b80-4101-11ea-8a49-f82a42e4d853.png)

then

![image](https://user-images.githubusercontent.com/36866702/73171789-db67b100-4101-11ea-8338-2de0d6690881.png)

**Comment by smashah** [comment]
why would you want to open the same session twice?

**Comment by GENL** [comment]
Yes I know. The behavior I expect is that the old session is closed and the new tab becomes the new session. This is what happens when you open whatsapp web in two different tabs.

**Comment by smashah** [comment]
I would suggest changing the session id every time you call sulla.create then. I will be pushing a new version where you can call client.kill() to shut down the page and the browser. Standby

**Comment by GENL** [comment]
If you do, the problem is that the user will have to scan the qr code again. I want the user to be able to reconnect to "sulla" without having to scan the qr code again.

**Comment by smashah** [comment]
The reason you get the 'Utiliser Ici' is because the person with the phone has activated a whatsapp web somewhere else. As soon as they close that window (somewhere else) this page will eventually continue working.

On the other hand, you can now kill a client/session and then restart as required.

https://github.com/smashah/sulla/issues/68#issuecomment-578819782

I guess the ultimate solution to this issue is to create a function on the client to click 'Utiliser ici' when required. related to #1

**Comment by GENL** [comment]
Yes that's the greatest solution. But it's not implemented yet.

**Comment by smashah** [comment]
@GENL give me 5 mins.

**Comment by GENL** [comment]
Okay thanks!

**Comment by smashah** [comment]
@GENL can you open whatsapp web in french and run this in the console

```
window.l10n.localeStrings.en[0][255]
```

in English it resolves to 'Use Here'. I wonder if it is 'Utiliser ici' for french.

In v.1.6.5 you can now call client.forceRefocus() which will click that button. You can see a valid implementation here:

https://github.com/smashah/sulla/blob/8bc9094f7bc08b88a87aa9b24d17f1e92bdb0970/demo/index.ts#L34

```javascript
client.onStateChanged(state=>{
    console.log('statechanged', state)
    if(state==="CONFLICT") client.forceRefocus();
  });
```

Right now this code will only work in English and French.

**Comment by smashah** [comment]
Ok I just checked in french, It is at the same address, 255. I'll implement that next.

**Comment by GENL** [comment]
Great.

**Comment by smashah** [comment]
v.1.6.6 forceRefocus() now works in any language

**Comment by GENL** [comment]
You really do a good job @smashah . I can close this issue right now.
