### ISSUE TITLE
getAllChats doesn't load all the profile pictures

### ISSUE THREAD

**Issue by mmc16** [smashah/sulla#70]
The function getAllChats returns the instances of older chats (those that don't appear in the screen) with empty profilePicThumbObj. A workaround that I found is to crate the client with `headless: false` and then scroll the chat list all the way down and then call getAllChats and retrieve the images URL...

**Comment by smashah** [comment]
That's a good workaround but not a viable solution to this issue. Let me look into this

**Comment by smashah** [comment]
@mmc16  As of v.1.6.3 you can now use the following to get profile pictures for chats that are not in your local cache.

```javascript
client.getProfilePicFromServer('XXXXXXX-YYYYY@c.us')
```
