### ISSUE TITLE
not getting onStateChanged trigger in sulla-hotfix Version 1.6.7

### ISSUE THREAD

**Issue by jigipatel** [smashah/sulla#74]
not getting onStateChanged trigger on connect, conflict, logged out(unpaired) feel like previous version was better at catching those triggers or may be getting issue because of puppeteer package update.

also it will be great if QR code regenerate after 30 seconds rather than every 10 seconds

**Comment by smashah** [comment]
Need more info on first point.

Regarding the second point, next version you will be able to set custom refresh time like so:

```javascript
create('session',
{
  executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
  headless:false,
  qrRefreshS:30
},
uaOverride
)
```

**Comment by jigipatel** [comment]
function start(client) {
client.onStateChanged(state=>{
    console.log('statechanged', state)
    if(state==="CONFLICT") client.forceRefocus();
  });

  client.onMessage(message => {
    if (message.body === 'Hi') {
      client.sendText(message.from, '👋 Hello from sulla!');
    }
  });
}

into this code console.log('statechanged', state) is not printing state because i'm not getting onStateChanged callback 

Thank you for other one

**Comment by smashah** [comment]
@jigipatel are your messages coming through?

**Comment by smashah** [comment]
v1.6.8 is live with the custom refresh interval.

https://github.com/smashah/sulla/blob/ca461f7a727500e7077678e9c9ece713580edd3a/demo/index.ts#L108

**Comment by jigipatel** [comment]
> @jigipatel are your messages coming through?

yes

**Comment by smashah** [comment]
Please follow best practices: https://github.com/smashah/sulla#best-practice

try this:

```javascript
async function start(client) {
await client.onStateChanged(state=>{
    console.log('statechanged', state)
    if(state==="CONFLICT") client.forceRefocus();
  });

 await client.onMessage(message => {
    if (message.body === 'Hi') {
      client.sendText(message.from, '👋 Hello from sulla!');
    }
  });
}
```

**Comment by smashah** [comment]
@jigipatel Try v1.6.15
