### ISSUE TITLE
client.isConnected() is always true

### ISSUE THREAD

**Issue by ramonck** [smashah/sulla#76]
Hi @smashah ,

I have tried in a couple of different ways to use the isConnected and it's always true even when my "test computer" is offline I totally unplugged the internet and it's still saying it's true haha.

I also tried shutting down the internet on the mobile phone and it continues to be true all the time.

Here's the test code snippet:
`var isConnected = await client.isConnected();
  console.log(isConnected)
    if(!isConnected){`

I don't know the exact logic that you're doing there but I`m suspicious that it got some how "cached" from the first verification and it's not verifying everytime we call it, or it's not recalling the verification everytime we call the isConnected is just a variable defined from the first call that's what is looking like the situation.

**Comment by smashah** [comment]
Check in headless:false mode.

Isconnected only changes once the UI in WhatsApp web changes and WhatsApp does not instantly detect whether or not the phone is connected. If you want to instigate a check then you need to send a text. Even then it's not instant.

Please share a screenshot where the UI shows the phone is disconnected but isConnected() is still true.

**Comment by otromaximiliano** [comment]
Hi @smashah !
Here is an image of what appears in headless: false mode.


It shows me as if the browser is controlled by automated software


![imagen-chrome](https://user-images.githubusercontent.com/19803990/73371897-28c85780-4295-11ea-8908-35519aabdf03.jpg)

**Comment by smashah** [comment]
@ramonck 

You should use onStateChanged instead of onConnected(). Also, in version v1.6.9 you can use getConnectionState().

```
client.onStateChanged(state=>{
    console.log('statechanged', state)
    if(state==="CONFLICT") client.forceRefocus(); //use opened whatsapp web somewhere else
    if(state==="TIMEOUT") notifyUser(); //phone is not connected
  });

...

const state =  await client.getConnectionState();
var isConnected = state=="CONNECTED"; console.log(isConnected) if(!isConnected){

```
Here are the possible states.

![image](https://user-images.githubusercontent.com/5903821/73371230-4acdd400-42ad-11ea-8374-8f99898c5ce9.png)

**Comment by smashah** [comment]
> Hi @smashah !
> Here is an image of what appears in headless: false mode.
> 
> It shows me as if the browser is controlled by automated software
> 
> ![imagen-chrome](https://user-images.githubusercontent.com/19803990/73371897-28c85780-4295-11ea-8908-35519aabdf03.jpg)

Can you translate this for me please?

**Comment by ramonck** [comment]
> > Hi @smashah !
> > Here is an image of what appears in headless: false mode.
> > It shows me as if the browser is controlled by automated software
> > ![imagen-chrome](https://user-images.githubusercontent.com/19803990/73371897-28c85780-4295-11ea-8908-35519aabdf03.jpg)
> 
> Can you translate this for me please?

This means that the phone is not connected you need to try again screen when the phone is either sleeping or offline.

**Comment by otromaximiliano** [comment]
Translate:

Retrying on Invalid Date.

Make sure your computer has an active and stable internet connection.

My connection is good. My smartphone also.

**Comment by smashah** [comment]
@otromaximiliano this seems to be an unrelated problem. Can you please open a new issue with the issue template. Thanks.

@ramonck Please try the solution mentioned above and let me know if this works for you https://github.com/smashah/sulla/issues/76#issuecomment-579824368

**Comment by ramonck** [comment]
> @otromaximiliano this seems to be an unrelated problem. Can you please open a new issue with the issue template. Thanks.
> 
> @ramonck Please try the solution mentioned above and let me know if this works for you [#76 (comment)](https://github.com/smashah/sulla/issues/76#issuecomment-579824368)

Hi @smashah it worked out fine now thanks to your tip there.

**Comment by mrbarnk** [comment]
sendText doesn't send seen in new version sir.

**Comment by smashah** [comment]
@mrbarnk please fill out a new issue with the template
