### ISSUE TITLE
queue.add(message=> { is null value

### ISSUE THREAD

**Issue by ramonck** [smashah/sulla#77]
Hi @smashah,

I tried your example in the readme and it's not passing the variable into the last piece.
function processMessage (message) {
  console.log(message) // here the value is fine
  return queue.add(message=> {
    console.log('nova mensagem')
    console.log(message) // here it returns null

**Comment by smashah** [comment]
Try this


```javascript
const proc = async message => {
    console.log('nova mensagem')
    console.log(message)
}

const processMessage = message => queue.add(proc(message));
```

**Comment by ramonck** [comment]
worked thanks!
