### ISSUE TITLE
Today I realized that Send Images no longer works Do you have any idea ?

### ISSUE THREAD

**Issue by stefano71** [smashah/sulla#78]
**Describe the bug**
Today 29-01-2020 
I realized that Send Images no longer works
Do you have any idea ?

**To Reproduce**

**Expected behavior**

**sulla-hotfix version**
Which sulla-hotfix version

**Whatsapp version**
Go to console in the chromium/chrome instance and type ```window.Debug.VERSION```

**Screenshots**
If applicable, add screenshots to help explain your problem. Use ```headless: false``` to get screenshots

**Host (please complete the following information):**

**Additional context**

**Comment by smashah** [comment]
@stefano71 please fill out the template more thoroughly. I've just tested it and it is working ok so I will need more info for reproduction

**Comment by stefano71** [comment]
I'm not getting any error messages.
the wapi.sendimage function after I cleared the chrome cache doesn't work

**Comment by rizki96** [comment]
@smashah I'm also getting the same problem, sendImage function is not working. After debugging the sendImage code then I've found out that this line is crashing
`var mc = new Store.MediaCollection()`

I've tried on both macosx and linux, tried also on sulla-hotfix 1.5.x and 1.6.10, all have the same behaviour.

**Comment by stefano71** [comment]
![image](https://user-images.githubusercontent.com/10145060/73438909-16125900-434f-11ea-90f8-c13cee1d9ca7.png)

this is the error message that has now occurred in the chrome console

**Comment by duzaq** [comment]
error message WAPI.sendImage
![erro_wp](https://user-images.githubusercontent.com/4000971/73440536-2e26b000-4330-11ea-8d19-a92e0a41ac07.png)

**Comment by nicolaubrasil** [comment]
> error message WAPI.sendImage
> ![erro_wp](https://user-images.githubusercontent.com/4000971/73440536-2e26b000-4330-11ea-8d19-a92e0a41ac07.png)

Search for all occurrences of mediaCollection and replace:
```var mc = new Store.MediaCollection();```
to
```var mc = new Store.MediaCollection(chat);```

**Comment by smashah** [comment]
Can you all share you whatsapp version please.

In the console in the browser run ``window.Debug.VERSION``

**Comment by stefano71** [comment]
with this change it works
Search for all occurrences of mediaCollection and replace:
var mc = new Store.MediaCollection();
to
var mc = new Store.MediaCollection(chat);

thanks

**Comment by smashah** [comment]
@stefano71 @nicolaubrasil As it seems to work for you, I'll implement this now

**Comment by smashah** [comment]
Should be live in v1.6.11

**Comment by smashah** [comment]
Closing this for now. Please reopen if it happens again

**Comment by duzaq** [comment]
The problem really came back, with the last modification above.

![error_whats_](https://user-images.githubusercontent.com/4000971/74778381-3791a100-527a-11ea-9b39-faf261a76561.png)

**Comment by haroldorodsilva** [comment]
I tried now and the image was not send.

@smashah 
Debug Info { WA_VERSION: '0.4.930',
  PAGE_UA:
   'WhatsApp/0.4.613 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36',
  SULLA_HOTFIX_VERSION: '1.7.24',
  BROWSER_VERSION: 'HeadlessChrome/79.0.3945.0' }

**Comment by smashah** [comment]
@haroldorodsilva @duzaq new version of WhatsApp :/

**Comment by marcelocecin** [comment]
change this
```javascript
{ id: "MediaCollection", conditions: (module) => (module.default && module.default.prototype && module.default.prototype.processFiles !== undefined) ? module.default : null },

mc.processFiles([mediaBlob], chat, 1).then(() => {
    var media = mc.models[0];
    media.sendToChat(chat, { caption: caption });
    if (done !== undefined) done(true);
});
```
to this
```javascript
{ id: "MediaCollection", conditions: (module) => (module.default && module.default.prototype && module.default.prototype.processAttachments) ? module.default : null },

mc.processAttachments([{file: mediaBlob}, 1], chat, 1).then(() => {
    var media = mc.models[0];
    media.sendToChat(chat, { caption: caption });
    if (done !== undefined) done(true);
})
```

**Comment by gildastema** [comment]
send image not work

**Comment by smashah** [comment]
@gildastema @marcelocecin @haroldorodsilva @duzaq Fix is live in v.1.7.25

I've tested it here and it's working. Please report back ASAP if it is/is not working for you.

Thanks

**Comment by stefano71** [comment]
I have the same problem too
on mac while on windows it works
could it depend on the user agent?
it is strange that on chrome mac whatsapp web responds differently

**Comment by smashah** [comment]
@stefano71 did you try latest version 1.7.25? Also please share your debug info on both systems for context

**Comment by stefano71** [comment]
i was wrong by clearing the chrome cache on windows i get the same mac error

VM1223:1442 Uncaught TypeError: Cannot read property 'createWid' of undefined
    at Object.window.WAPI.sendImage (<anonymous>:1442:39)
    at <anonymous>:2097:13

has anyone solved it?

**Comment by stefano71** [comment]
> @stefano71 did you try latest version 1.7.25? Also please share your debug info on both systems for context

yes

**Comment by smashah** [comment]
@stefano71 this appears to be a seperate problem if it is still happnening then please make a new issue. Closing this for now.

**Comment by stefano71** [comment]
with your wapi.js I can't send images
i tried this and it works even if it also sends to wrong numbers.

https://raw.githubusercontent.com/blubbll/wabot/72fd4f6353109d7f933f78942b03c3dd7fcd84a5/inject/WAPI.js

**Comment by marcelocecin** [comment]
please attach print with the error

**Comment by stefano71** [comment]
![image](https://user-images.githubusercontent.com/10145060/75347181-848bfd80-58a0-11ea-9f0b-dae383f1c2eb.png)

**Comment by stefano71** [comment]
unfortunately I get this error  
VM2223:1458 Uncaught TypeError: Cannot read property 'createWid' of undefined
    at Object.window.WAPI.sendImage (<anonymous>:1458:39)
    at <anonymous>:2131:13

**Comment by stefano71** [comment]
![image](https://user-images.githubusercontent.com/10145060/75347309-c74dd580-58a0-11ea-87c3-d82b2ec05599.png)

**Comment by smashah** [comment]
@stefano71 please clear your console history

**Comment by stefano71** [comment]
you're right now it works, but I don't understand why the MIME type of the base 64 file with the preview is not recognized
![image](https://user-images.githubusercontent.com/10145060/75377145-84582600-58d1-11ea-9f90-3703780c792e.png)

**Comment by stefano71** [comment]
unfortunately some file types are not recognized on android

**Comment by stefano71** [comment]
It works well only the control of sending the file on the wrong phone number is missing. unfortunately the file is also sent to non-existent numbers

**Comment by stefano71** [comment]
window.WAPI.sendImage = function(imgBase64, chatid, filename, caption, done) {
  try {
    //alert 'WhatsApp';
    window.getContact = chatid => {
      return Store.WapQuery.queryExist(chatid);
	  //alert 'WhatsApp';
    };
    window.getContact(chatid).then(contact => {
      if (contact.status === 404) {
	  //alert 'WhatsApp Error';
        done(true);
      } else {
        Store.Chat.find(contact.jid)
          .then(chat => {
            //chat.sendMessage(message);
			//alert("1");
			  //var idUser = new window.Store.UserConstructor(chatid);
				  var idUser = new window.Store.UserConstructor(chatid, {
					intentionallyUsePrivateConstructor: true
				  });
				  // create new chat
				  return Store.Chat.find(idUser).then(chat => {
					var mediaBlob = window.WAPI.base64ImageToFile(imgBase64, filename);
					var mc = new Store.MediaCollection(chat);
					mc.processAttachments([{ file: mediaBlob }, 1], chat, 1).then(() => {
					  var media = mc.models[0];
					  media.sendToChat(chat, { caption: caption });
					  if (done !== undefined) done(true);
					});
				  });
			////alert 'WhatsApp';
            return true;
          })
          .catch(reject => {
            if (WAPI.sendMessage(chatid, message)) {
				//alert("2");
            } else {    		
				//alert("3");
            }
          });
      }
    });
  } catch (e) {
    if (window.Store.Chat.length === 0) {
		//alert 'WhatsApp';
		return false};

    firstChat = Store.Chat.models[0];
    var originalID = firstChat.chatid;
    firstChat.chatid =
      typeof originalID === "string"
        ? chatid
        : new window.Store.UserConstructor(chatid, {
            intentionallyUsePrivateConstructor: true
          });
    if (done !== undefined) {
      firstChat.sendMessage(message).then(function() {
        firstChat.chatid = originalID;
        done(true);
      });
	  //alert 'WhatsApp';
      return true;
    } else {
      //firstChat.sendMessage(message);
      //firstChat.id = originalID;
	  			  //var idUser = new window.Store.UserConstructor(chatid);
				  var idUser = new window.Store.UserConstructor(chatid, {
					intentionallyUsePrivateConstructor: true
				  });
				  // create new chat
				  return Store.Chat.find(idUser).then(chat => {
					var mediaBlob = window.WAPI.base64ImageToFile(imgBase64, filename);
					var mc = new Store.MediaCollection(chat);
					mc.processAttachments([{ file: mediaBlob }, 1], chat, 1).then(() => {
					  var media = mc.models[0];
					  media.sendToChat(chat, { caption: caption });
					  if (done !== undefined) done(true);
					});
				  });	  
	  //alert 'WhatsApp';
      return true;
    }
  }
  if (done !== undefined) done(false);
  return false;
};

**Comment by stefano71** [comment]
now if the number is wrong the file is not sent
to paicere you can check if everything is correct

window.WAPI.sendImage = function(imgBase64, chatid, filename, caption, done) {
  try {
    //alert 'WhatsApp';
    window.getContact = chatid => {
      return Store.WapQuery.queryExist(chatid);
	  //alert 'WhatsApp';
    };
    window.getContact(chatid).then(contact => {
      if (contact.status === 404) {
	  //alert 'WhatsApp Error';
        done(true);
      } else {
        Store.Chat.find(contact.jid)
          .then(chat => {
            //chat.sendMessage(message);
			//alert("1");
			  //var idUser = new window.Store.UserConstructor(chatid);
				  var idUser = new window.Store.UserConstructor(chatid, {
					intentionallyUsePrivateConstructor: true
				  });
				  // create new chat
				  return Store.Chat.find(idUser).then(chat => {
					var mediaBlob = window.WAPI.base64ImageToFile(imgBase64, filename);
					var mc = new Store.MediaCollection(chat);
					mc.processAttachments([{ file: mediaBlob }, 1], chat, 1).then(() => {
					  var media = mc.models[0];
					  media.sendToChat(chat, { caption: caption });
					  if (done !== undefined) done(true);
					});
				  });
			////alert 'WhatsApp';
            return true;
          })
          .catch(reject => {
            if (WAPI.sendMessage(chatid, message)) {
				//alert("2");
            } else {    		
				//alert("3");
            }
          });
      }
    });
  } catch (e) {
    if (window.Store.Chat.length === 0) {
		//alert 'WhatsApp';
		return false};

    firstChat = Store.Chat.models[0];
    var originalID = firstChat.chatid;
    firstChat.chatid =
      typeof originalID === "string"
        ? chatid
        : new window.Store.UserConstructor(chatid, {
            intentionallyUsePrivateConstructor: true
          });
    if (done !== undefined) {
      firstChat.sendMessage(message).then(function() {
        firstChat.chatid = originalID;
        done(true);
      });
	  //alert 'WhatsApp';
      return true;
    } else {
      //firstChat.sendMessage(message);
      //firstChat.id = originalID;
	  			  //var idUser = new window.Store.UserConstructor(chatid);
				  var idUser = new window.Store.UserConstructor(chatid, {
					intentionallyUsePrivateConstructor: true
				  });
				  // create new chat
				  return Store.Chat.find(idUser).then(chat => {
					var mediaBlob = window.WAPI.base64ImageToFile(imgBase64, filename);
					var mc = new Store.MediaCollection(chat);
					mc.processAttachments([{ file: mediaBlob }, 1], chat, 1).then(() => {
					  var media = mc.models[0];
					  media.sendToChat(chat, { caption: caption });
					  if (done !== undefined) done(true);
					});
				  });	  
	  //alert 'WhatsApp';
      return true;
    }
  }
  if (done !== undefined) done(false);
  return false;
};

**Comment by stefano71** [comment]
now if the number is wrong the file is not sent
please you can check if everything is correct

window.WAPI.sendImage = function(imgBase64, chatid, filename, caption, done) {
  try {
    //alert 'WhatsApp';
    window.getContact = chatid => {
      return Store.WapQuery.queryExist(chatid);
	  //alert 'WhatsApp';
    };
    window.getContact(chatid).then(contact => {
      if (contact.status === 404) {
	  //alert 'WhatsApp Error';
        done(true);
      } else {
        Store.Chat.find(contact.jid)
          .then(chat => {
            //chat.sendMessage(message);
			//alert("1");
			  //var idUser = new window.Store.UserConstructor(chatid);
				  var idUser = new window.Store.UserConstructor(chatid, {
					intentionallyUsePrivateConstructor: true
				  });
				  // create new chat
				  return Store.Chat.find(idUser).then(chat => {
					var mediaBlob = window.WAPI.base64ImageToFile(imgBase64, filename);
					var mc = new Store.MediaCollection(chat);
					mc.processAttachments([{ file: mediaBlob }, 1], chat, 1).then(() => {
					  var media = mc.models[0];
					  media.sendToChat(chat, { caption: caption });
					  if (done !== undefined) done(true);
					});
				  });
			////alert 'WhatsApp';
            return true;
          })
          .catch(reject => {
            if (WAPI.sendMessage(chatid, message)) {
				//alert("2");
            } else {    		
				//alert("3");
            }
          });
      }
    });
  } catch (e) {
    if (window.Store.Chat.length === 0) {
		//alert 'WhatsApp';
		return false};

    firstChat = Store.Chat.models[0];
    var originalID = firstChat.chatid;
    firstChat.chatid =
      typeof originalID === "string"
        ? chatid
        : new window.Store.UserConstructor(chatid, {
            intentionallyUsePrivateConstructor: true
          });
    if (done !== undefined) {
      firstChat.sendMessage(message).then(function() {
        firstChat.chatid = originalID;
        done(true);
      });
	  //alert 'WhatsApp';
      return true;
    } else {
      //firstChat.sendMessage(message);
      //firstChat.id = originalID;
	  			  //var idUser = new window.Store.UserConstructor(chatid);
				  var idUser = new window.Store.UserConstructor(chatid, {
					intentionallyUsePrivateConstructor: true
				  });
				  // create new chat
				  return Store.Chat.find(idUser).then(chat => {
					var mediaBlob = window.WAPI.base64ImageToFile(imgBase64, filename);
					var mc = new Store.MediaCollection(chat);
					mc.processAttachments([{ file: mediaBlob }, 1], chat, 1).then(() => {
					  var media = mc.models[0];
					  media.sendToChat(chat, { caption: caption });
					  if (done !== undefined) done(true);
					});
				  });	  
	  //alert 'WhatsApp';
      return true;
    }
  }
  if (done !== undefined) done(false);
  return false;
};
