### ISSUE TITLE
Error: Evaluation failed: TypeError: Cannot read property '_serialized' of undefined

### ISSUE THREAD

**Issue by mrbarnk** [smashah/sulla#79]
On the latest version, see what i'm getting.
`
Error: Evaluation failed: TypeError: Cannot read property '_serialized' of undefined
0|index  |     at Object.window.WAPI.getChat (/root/waabot/node_modules/sulla-hotfix/dist/lib/wapi.js:326:42)
0|index  |     at Object.window.WAPI.sendSeen (/root/waabot/node_modules/sulla-hotfix/dist/lib/wapi.js:867:28)
0|index  |     at __puppeteer_evaluation_script__:3:34
0|index  |     at ExecutionContext._evaluateInternal (/root/waabot/node_modules/puppeteer/lib/ExecutionContext.js:122:13)
0|index  |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
0|index  |     at ExecutionContext.evaluate (/root/waabot/node_modules/puppeteer/lib/ExecutionContext.js:48:12)
0|index  |   -- ASYNC --
0|index  |     at ExecutionContext.<anonymous> (/root/waabot/node_modules/puppeteer/lib/helper.js:111:15)
0|index  |     at DOMWorld.evaluate (/root/waabot/node_modules/puppeteer/lib/DOMWorld.js:112:20)
0|index  |   -- ASYNC --
0|index  |     at Frame.<anonymous> (/root/waabot/node_modules/puppeteer/lib/helper.js:111:15)
0|index  |     at Page.evaluate (/root/waabot/node_modules/puppeteer/lib/Page.js:863:43)
0|index  |     at Page.<anonymous> (/root/waabot/node_modules/puppeteer/lib/helper.js:112:23)
0|index  |     at Whatsapp.<anonymous> (/root/waabot/node_modules/sulla-hotfix/dist/api/whatsapp.js:95:50)
0|index  |     at step (/root/waabot/node_modules/sulla-hotfix/dist/api/whatsapp.js:33:23)
0|index  |     at Object.next (/root/waabot/node_modules/sulla-hotfix/dist/api/whatsapp.js:14:53)
0|index  |     at /root/waabot/node_modules/sulla-hotfix/dist/api/whatsapp.js:8:71
0|index  |     at new Promise (<anonymous>)
0|index  |     at __awaiter (/root/waabot/node_modules/sulla-hotfix/dist/api/whatsapp.js:4:12)
0|index  |     at Whatsapp.sendText (/root/waabot/node_modules/sulla-hotfix/dist/api/whatsapp.js:92:16)
0|index  |     at /root/waabot/controllers/start.js:26:42
0|index  |     at Array.forEach (<anonymous>)
0|index  |     at /root/waabot/controllers/start.js:25:29
`

This happens when I want to send a text with `client.sendText()`

**Comment by smashah** [comment]
Did the text get sent? Are you sure this number is valid?

**Comment by mrbarnk** [comment]
Yes, the number is valid.

No, again in my other app. It shows sent but never got any message.

**Comment by barkerpedro** [comment]
For me, sendText, sendMedia and sendFile are not working.

**Comment by smashah** [comment]
@mrbarnk @barkerpedro can you share the following details:
- whatsapp version (in console run: `window.Debug.VERSION`)
- `sulla.create(...` code

**Comment by smashah** [comment]
In v1.6.13 you should get some relevant debug information when you launch sulla.

**Comment by mrbarnk** [comment]
This is what I get after putting this code to check if there is a page crash so to be able to restart the session.

The code

`setInterval(async () => {
              //Returns 'CONNECTED' or 'TIMEOUT' or 'CONFLICT' (if user opens whatsapp web somewhere else)
                await client.isConnected().then(async res => {
                    if (res != true) {
                        console.log('Disconnected')
                        await client.kill()
                    }
                }).catch(e => console.log('error => '+e.message))
            }, 10000)
`
Error produced

`Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed`

It doesn't restart the session, what's wrong with that code?

**Comment by smashah** [comment]
@mrbarnk Please see https://github.com/smashah/sulla/issues/76#issuecomment-579824368
and update to latest version. If this happens again please reopen thanks
