### ISSUE TITLE
Send video

### ISSUE THREAD

**Issue by uargb** [smashah/sulla#8]
sendImage and sendFile do not handle video messaging(. I have a base64 like 
`let mediaData = 'data:{mime};base64,{base64}'` where mime is geeting with `npm: mime-types`. I have no message delivered with this piece(

**Comment by uargb** [comment]
@smashah any comment)?

**Comment by smashah** [comment]
hey @uargb Can you share the code that you're using?

The index.ts in the demo literally reads a file, saves it and sends it back to the number that sent the file so it should work fine.

**Comment by Marcoserious** [comment]
Hello, I want to send a video (aaa.mp4) that is in the same folder of the server.js file and what am I doing wrong?  help please...


// import { create, Whatsapp } from 'sulla-hotfix';
const sulla = require('sulla-hotfix');

sulla.create().then(client => start(client));


var fs = require('fs');

// function to encode file data to base64 encoded string
function base64_encode(file) {
    // read binary data
    var bitmap = fs.readFileSync(file);
    // convert binary data to base64 encoded string
    return new Buffer(bitmap).toString('base64');
}
a=base64_encode("aaa.mp4");
var base64str = 'data:video/mp4'+";base64,"+a.toString('base64')
console.log(base64str)
function start(client) {
  client.onMessage(async message => {

 if (message.body === 'Hi') {

      client.sendText(message.from, '👋 Hello from sulla!');
      await client.sendFile(message.from,[base64str],'aaa.mp4', `Hello this is the caption`)
      console.log()

       //client.sendText(message.from, '👋 Hello from sulla!');
    }


/*
  	console.log(message)
  	console.log("................................................................................")
  	console.log(message.mimetype)
  	console.log("...............................................................")
  	const mediaData = decryptMedia(message);
  	console.log(mediaData)
   */
  });
}

**Comment by smashah** [comment]
@Marcoserious why are there square brackets around base64str?

**Comment by smashah** [comment]
I'm closing this issue for now. Please keep me updated if there are some more issues.
