### ISSUE TITLE
What programming language do you use for "import {create, Whatsapp} from 'sulla-hotfix';" work?

### ISSUE THREAD

**Issue by arturromaorocha** [smashah/sulla#80]
What programming language do you use for "import {create, Whatsapp} from 'sulla-hotfix';" work?

Good evening!
I am starting the service using node however when I use "import {create, Whatsapp} from 'sulla-hotfix';" it generates an error saying that the "import" is not found

Boa noite!
Estou iniciando o serviço usando node porém quando utilizo o "import { create, Whatsapp} from 'sulla-hotfix';" ele me gera um erro disendo que o "import" não é encontrado

Português-BR

**Comment by gnadelwartz** [comment]
same for me, use the method in the simple example:

```javascript
// instead "import { create, Whatsapp } from 'sulla-hotfix';" use:
const sulla = require('sulla-hotfix');

// and prefix create with sulla ...
sulla.create().then(client => start(client));

function start(client) {
  client.onMessage(message => {
    if (message.body === 'Hi') {
      client.sendText(message.from, '👋 Hello from sulla!');
    }
  });
}
```

**Comment by smashah** [comment]
The demo/index.ts is in typescript. You can run it as is with [ts-node](https://github.com/TypeStrong/ts-node).
