### ISSUE TITLE
WA_VERSION: 'I think you have been TOS_BLOCKed'

### ISSUE THREAD

**Issue by fernandolcardoso** [smashah/sulla#83]
Hello people,

Eventually there is a loss of connection and in some cases it is necessary to stop and start the sulla-hotfix again.

In these cases, when the session is lost, the QR reading should be made available, which was possible in the first versions.

In the latest versions, QR availability has been compromised.

To resover, I need to delete the session folder and all modules.

Finally, I install all the modules again and start a new session, to show the QR.

Is there a solution?

Note that in this latest version, I am receiving a debug alert with the warning of a possible block, what can we do to resolve it?

![image](https://user-images.githubusercontent.com/16019127/73538469-e2e0d000-4409-11ea-9987-8cbea2ba2ca3.png)

**Comment by fernandolcardoso** [comment]
Duplicate of #71

**Comment by fernandolcardoso** [comment]
Is the browser agent's information respecting what is reported by any chance?

![image](https://user-images.githubusercontent.com/16019127/73542315-33a8f680-4413-11ea-9ba0-3d0b4fdbb2e6.png)

I took the liberty of opening Chromium directly and accessed WhatsApp Web which answered me correctly with QR.

![image](https://user-images.githubusercontent.com/16019127/73542662-fdb84200-4413-11ea-9e61-4df558c5738f.png)

**Comment by smashah** [comment]
@fernandolcardoso No worries

Can you try the UA mentioned here:
https://github.com/smashah/sulla/issues/71#issuecomment-580547372

I think the lack of Whatsapp and the inclusion of Windows NT results in TOS_BLOCK

**Comment by mmc16** [comment]
I am getting this error sometimes because sulla gets a `VALID_SESSION = false`, even though I had already authenticated the session with the QR code....


```bash
✔ Initializing whatsapp
Debug Info {
  WA_VERSION: '0.4.315',
  PAGE_UA: 'WhatsApp/2.16.352 Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36'
}
ℹ Authenticate to continue
✔ Loading QR

[QR code here] 

✔ Authenticating
✖ The session is invalid. Retrying
✔ Initializing whatsapp
Debug Info {
  WA_VERSION: 'I think you have been TOS_BLOCKed',
  PAGE_UA: 'WhatsApp/2.16.352 Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36'
}
Possilby TOS_BLOCKed
ℹ Authenticate to continue
✔ Loading QR

[Nothing here]
```

**Comment by smashah** [comment]
If sulla-hotfix says the session is invalid it is invalid (the check is to see if `Store.Msg` exists. If it doesn't then the session is considered invalid. Even if you signed in, none of the client listeners would work without `Store.Msg`) 

@mmc16 Please try https://github.com/smashah/sulla/issues/71#issuecomment-580547372 and report back

**Comment by habibshahid** [comment]
I am experiencing the same problem. I tried the User Agent mentioned in #71 but its still the same. 
I delete the session. It regenerates the QR code and after scan it says the session is invalid and tries to re-generate the QR. 
I am at the latest version of sulla-hotfix

Kindly advise

**Comment by smashah** [comment]
@habibshahid  without your debug info I wouldn't be able to tell. The only solution I can think of now is to add a timeout before checking for a valid session. In my testing everything is working fine so I will need some repro steps to help you further.

I will release a new version with a timeout soon.

**Comment by rizki96** [comment]
I've managed to solve the problem by doing the steps below :
- downgrade the puppeteer to ver. 2.0.0, previously it was 2.1.0
- downgrade sulla-hotfix to ver. 1.6.10
- using default ua (don't use custom ua option when call sulla.create)
- for decrypting media, the user agent is "WhatsApp/2.16.352 Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:72.0) Gecko/20100101 Firefox/72.0"

But there is still one issue, the session saved will not be loaded after qr code is being authenticated successfully. The work around for my case is just creating a new session for every attempt to login to whatsapp.

**Comment by smashah** [comment]
@rizki96 I also have puppeteer at 2.0.0

I'll make sure to lock it there for now. Thanks for the solution

**Comment by GENL** [comment]
I downgraded pupeeter to version 2.0.0 and the issue "WA_VERSION: 'I think you have been TOS_BLOCKed" was solved.
I also found it is better for production to run sulla with `headless: true` (no visible browser).

**Comment by gnadelwartz** [comment]
can confirm it's also working in  my Setup, incl. decrypt media, when using given UA here https://github.com/smashah/sulla/issues/83#issuecomment-580797877
sulla-hotfix 1.6.15 instead say `The session is invalid. Retrying` and hang's

OpenSuse 15.3
pupeteer 2.0.0
sulla-hotfix 1.6.10

default UA on startup

DECRYPTUA = 'WhatsApp/2.16.352 Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:72.0) Gecko/20100101 Firefox/72.0';

```
ts-node *.ts
✔ Initializing whatsapp
ℹ Authenticate to continue
✔ Loading QR

▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄
█ ▄▄▄▄▄ █▄▄█▀▀█▀█▀█▀█▄ █▀█▀ █▄█▄▄▄█ ▄▄▄▄▄ █
█ █   █ █ ▄▄ ▀ ▄█▀█▄█▀▀ ▀█▄ ▀ ▀▀▀▀█ █   █ █
█ █▄▄▄█ █▄ █ █ ▀█ ▀█ ▀  █▀█▄▄▀▀▀ ▀█ █▄▄▄█ █
█▄▄▄▄▄▄▄█▄▀ █ █ ▀ ▀▄█ █ ▀▄█ █▄▀▄▀ █▄▄▄▄▄▄▄█
...
█ █   █ █▀▀ ▀ ██▄▀   ▄▄▄██▀  ▄▀▀█  ▄▄▄▄▀▄██
█ █▄▄▄█ █ █  █▄▄▀█▄▄▄▄▀▀▀ ▄▀▀ ██▄█ ▀▄▀▀▄▀██
█▄▄▄▄▄▄▄█▄█▄██▄█▄██▄▄▄▄█▄████▄█▄▄▄██▄█▄▄▄██

✔ Authenticating
✔ Whatsapp is ready
1.2.2020, 11:20:39 deal processing started!
1.2.2020, 11:21:00 =========== new message =================
1.2.2020, 11:21:00 From: 49152017xxxxxx@c.us To: 4917951xxxxxx@c.us Sender: 4915201xxxxxx@c.us
1.2.2020, 11:21:00 Chat: 49152017xxxxxx@c.us Name: KayM
1.2.2020, 11:21:00 Chatname: Kay Mobil  Type: image Caption: undefined
1.2.2020, 11:21:00 Content: /9j/4AAQSkZJRgABAQAAAQABAAD/4gI .... fzKEKaLRRu4dSa2j/snbaLPuMI39Su7gsBipwPjkGo3QhS4pq1oALb/MIZrIaTbIuhCyLmwOShCEH/2Q==
1.2.2020, 11:21:00 From: KayM (4915201xxxxxx@c.us) Chat: Kay Mobil (49152017xxxxxx@c.us)
1.2.2020, 11:21:00 UUID=f6227047-2916-47ec-b9e6-5ad3d4cd568e , 
1.2.2020, 11:21:00 Found Media, start decrypting (WhatsApp/2.16.352 Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:72.0) Gecko/20100101 Firefox/72.0) ...
1.2.2020, 11:21:00 ... decrypting done!
1.2.2020, 11:21:00 Save Media to file: /f6227047-2916-47ec-b9e6-5ad3d4cd568e.jpeg
1.2.2020, 11:21:00 No text in message
1.2.2020, 11:21:00 Media image/jpeg saved to f6227047-2916-47ec-b9e6-5ad3d4cd568e.jpeg
```

**Comment by smashah** [comment]
Puppeteer is locked to 2.0.0 in v1.6.16
