### ISSUE TITLE
How to use decryptMedia with node.js?

### ISSUE THREAD

**Issue by gnadelwartz** [smashah/sulla#84]
I want to save recieved media to current dir, so tried to adapt your example from here https://github.com/smashah/sulla/blob/3d7a0e6505b28e44db10a7aee1067fd376f7cfa6/demo/index.ts#L49-L58

As this is typescript I had to adapt it to javascript, see my shortened example below:

```javascript
const sulla = require('sulla-hotfix');
const fs = require('fs');
const uuid = require('uuid/v4');
const mime = require('mime-types');

sulla.create().then(client => start(client));

function start(client) {
  client.onMessage(message => {

    // uuidv4 as filename
    const fname = uuid();

    // found media (picture, voice, etc)
    if (message.mimetype) {
      const filename = fname +'.'+ mime.extension(message.mimetype);
      const mediaData = sulla.decryptMedia(message, uaOverride);
       //  sulla.decryptMedia(.. , ..).then(mediaData => () { ... ?????

      // save to outdir/filename
      const savepath=outdir+filename;
      fs.writeFile(savepath, mediaData, function(err) {
        // wait for saved
        if (err) { return console.log(err); }
        console.log(`Media ${message.mimetype} saved to ${savepath}`);
      });
    }      
  });
}
```

to code pass eslint and does execute, but instead of saving the media content I get only a [promise object].

whats the correct way resolve the promise to get the media content from decryptMedia promise? simply adding await seems not to work an about the .then() I'm not shure ...

**Comment by smashah** [comment]
The demo already saves to current dir. Use ts-node to run the demo or just compile it using tsc.

**Comment by gnadelwartz** [comment]
I want to use the code in my already existing node script, if Ifllow your suggestion I hav to rewrite everything ... and I'm a javascipt (and much mire typescipt) newbie

Will the following work?

```javascript
 sulla.decryptMedia(message, uaOverride).then(mediaData => () {
      // save to outdir/filename
      const savepath=outdir+filename;
      fs.writeFile(savepath, mediaData, function(err) {
        // wait for saved
        if (err) { return console.log(err); }
        console.log(`Media ${message.mimetype} saved to ${savepath}`);
      });
  });
```

**Comment by gnadelwartz** [comment]
even your ts-node examples for downloading media does hang on my Linux box, so I give up and ignore media for now ...

**Comment by gnadelwartz** [comment]
for decryptMedia solution see here https://github.com/smashah/sulla/issues/83#issuecomment-581016684
