### ISSUE TITLE
How to reply/quote a message?

### ISSUE THREAD

**Issue by algoz098** [smashah/sulla#86]
Is there a way to reply a message?

As when on a phone you swipe right on a message and you quote it?

WAPI.js has a function but it's not accessible

**Comment by CosmicSnow** [comment]
I haven't tried it yet, but,
the message object have keys named `quotedMsg:` , `quotedStanzaID` and `quotedParticipant`
where, `quotedMsg` contains `{ type: , body: }`, `quotedStanzaID` contains the msg id (think), and `quotedParticipant` contains the the user jid,

I'll try it as soon as I have time, but, maybe try using these object keys?

**Comment by smashah** [comment]
ReplyMessage in WAPI.js doesn't work

**Comment by smashah** [comment]
@algoz098 @CosmicSnow This is now implemented in v1.6.17

https://github.com/smashah/sulla#reply-to-messages

Thanks
