### ISSUE TITLE
onAnyMessage throws not defined

### ISSUE THREAD

**Issue by algoz098** [smashah/sulla#87]
**Describe the bug**
When setting a use for 'onAnyMessage' event it doesnt work and throw a error while loading the api

**To Reproduce**
1. Set up sulla
2. Add a event callback for the funcion onAnyMessage
3. Scan the QR code

**Expected behavior**
The event would be fired when send a message or received

**sulla-hotfix version**
1.6.1 and 1.6.10

**Whatsapp version**
WA_VERSION: '0.4.315',

**Screenshots**
![image](https://user-images.githubusercontent.com/1363526/73611576-e1f29e80-45c1-11ea-9460-bb530d773101.png)

**Host (please complete the following information):**
Mac OS X Catalina
Chromium
Puppeteer 2.0.0

**Comment by smashah** [comment]
onAnyMessage should be working as expected in v1.6.16
