### ISSUE TITLE
getting invalid session with TOS Block error

### ISSUE THREAD

**Issue by jigipatel** [smashah/sulla#88]
Hello,

![TOS_Block error](https://user-images.githubusercontent.com/33049650/73650706-c615f800-46a8-11ea-99a4-972e036c1f9b.png)

I'm getting 'the session is invalid. retrying' and after that getting possibly TOS_BLOCKed error. not able to execute forward.

i have tried on windows and ubuntu with different whatsapp number but no luck.
please help me to solve this issue

Thank You.

**Comment by gnadelwartz** [comment]
gave you read this issue? https://github.com/smashah/sulla/issues/83#issuecomment-580796345

**Comment by alishahlakhani** [comment]
Even I'm getting this issue @gnadelwartz 
I did try to go back to old versions it still doesn't work for some reason.

**Comment by gnadelwartz** [comment]
ok, try the following:

```
rm -rf session
npm i pupeteer@2.0.0
npm i sulla-hotfix@1.6.10

```
do not override useragent on sulla startup! from your script!

this works for my script, but you have to rm session and reauth on every start.

**Comment by alishahlakhani** [comment]
This works now!! thanks :D

**Comment by gnadelwartz** [comment]
Glad to hear, thats exacly the solution described in https://github.com/smashah/sulla/issues/83#issuecomment-580796345

So you can close the issue

**Comment by smashah** [comment]
I'll release a new version with the above fix in about an hour thanks

**Comment by smashah** [comment]
duplicate #83

**Comment by smashah** [comment]
Puppeteer is locked to 2.0.0 in v1.6.16
