### ISSUE TITLE
authenticate 

### ISSUE THREAD

**Issue by gildastema** [smashah/sulla#9]
the qrcode loader is undefined when the session was previously created

**Comment by smashah** [comment]
Can you give me steps to recreate and the actual problem? If the sessions was already created does it continuously load for you? Whatsapp might changed their detection.

**Comment by gildastema** [comment]
Actually I think whatsapp has changed the mode of detection. when the section is created for the first time and everything is ok.
but at the second launches its loop at the level on the loading of the qrcode

**Comment by gildastema** [comment]
![DeepinScreenshot_select-area_20191108160833](https://user-images.githubusercontent.com/19803232/68486740-08fb3780-0242-11ea-9487-db7b4b90f867.png)

**Comment by gildastema** [comment]
I think this condition has changed
![DeepinScreenshot_select-area_20191108161515](https://user-images.githubusercontent.com/19803232/68487319-2086f000-0243-11ea-88fd-18ae3578b036.png)

**Comment by smashah** [comment]
I think WhatsApp has blocked our user-agent. I'll make an update where users can set the user agent themselves in order to have some sort of variation between users of this lib.

**Comment by gildastema** [comment]
Great idea.

**Comment by smashah** [comment]
@gildastema https://github.com/smashah/sulla#custom-set-up

v.1.2.6

Give it a whirl let me know if it works out for you thanks.

**Comment by rubenfaria** [comment]
The QR is not being shown on the console.
![image](https://user-images.githubusercontent.com/28407098/68634947-c6ea2400-04d5-11ea-968b-95d00f42d1e0.png)

**Comment by smashah** [comment]
@rubenfaria Can you please show me your code. Also, try deleting the sessions folder and try again.

**Comment by rubenfaria** [comment]
Sure thing!
![image](https://user-images.githubusercontent.com/28407098/68638867-aa53e900-04e1-11ea-9307-2ce9490dab27.png)
It's just the starter example. I wanted to test whether the session would be saved.

PS. You're the man! This repo of yours has the best care for sure.

**Comment by gildastema** [comment]
> @gildastema https://github.com/smashah/sulla#custom-set-up
> 
> v.1.2.6
> 
> Give it a whirl let me know if it works out for you thanks.

Let me check and come back to you

**Comment by gildastema** [comment]
> > @gildastema https://github.com/smashah/sulla#custom-set-up
> > v.1.2.6
> > Give it a whirl let me know if it works out for you thanks.
> 
> Let me check and come back to you

![DeepinScreenshot_select-area_20191112103229](https://user-images.githubusercontent.com/19803232/68659620-d8fcae80-0537-11ea-9780-95d25aa5067c.png)

**Comment by gildastema** [comment]
The problem is different with the initialization on loop on the loading of the qrcode

**Comment by smashah** [comment]
I'm going to try to set up the hardcoded user agent to that of WhatsApp web desktop client itself. Let's see what they do with that.

**Comment by smashah** [comment]
@gildastema @rubenfaria it looks like it works if you make the user agent the same as a whatsapp web desktop electron client one. You can find others here:
https://developers.whatismybrowser.com/useragents/explore/software_name/whatsapp/?order_by=-software_version

e.g

`Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) WhatsApp-Rebellin/1.0 Chrome/53.0.2785.143 Electron/1.4.15 Safari/537.36`

I'll push a new version of sulla-hotfix with this new user agent.

**Comment by smashah** [comment]
https://github.com/smashah/sulla/commit/cb6619faa85669a9e7b1330fe2a63d874faacebb

![image](https://user-images.githubusercontent.com/5903821/68716478-3591b500-059c-11ea-970d-26e5e34ca8c8.png)

**Comment by rubenfaria** [comment]
Am I missing something?
The QR appears on Sulla but no on Hotfix.
![image](https://user-images.githubusercontent.com/28407098/68718822-2c4b1d00-0589-11ea-8e82-8834147b3f63.png)

**Comment by smashah** [comment]
@rubenfaria can you confirm you:

1. Are using latest version.
2. Deleted the sessions folder before trying
3. Tried without the custom parameters and see if it works (I'm pretty sure if you change user-agents while still using the same session folder it will fail)

**Comment by rubenfaria** [comment]
> 
> 
> @rubenfaria can you confirm you:
> 
>     1. Are using latest version.
> 
>     2. Deleted the sessions folder before trying
> 
>     3. Tried without the custom parameters and see if it works (I'm pretty sure if you change user-agents while still using the same session folder it will fail)

Yes to all three. I had a collegue and myself to start two different brand new projects from scratch and the outcome was the same. 

I'm really lost about what's happening. Sulla works with the problem of having to delete the session folder at restart.

**Comment by smashah** [comment]
@rubenfaria can you screenshot what you see when you do headless:false and what environments are you running on?

**Comment by rubenfaria** [comment]
> 
> 
> @rubenfaria can you screenshot what you see when you do headless:false and what environments are you running on?
Thanks for your time, man.
![image](https://user-images.githubusercontent.com/28407098/68727741-07b06e80-05a4-11ea-8aad-61f5243172e7.png)
It also opens up WhatsApp Web at Chromium.

**Comment by smashah** [comment]
@rubenfaria what does chromium show?

**Comment by davigdc** [comment]
I'm having the same problem as @rubenfaria 

> @rubenfaria can you screenshot what you see when you do headless:false and what environments are you running on?

![image](https://user-images.githubusercontent.com/36992852/68728981-81962700-05a7-11ea-9e1a-0158ddbe5f6e.png)

**Comment by smashah** [comment]
Looks like both of you are running windows. I'm on mac right now, can you try using a custom user agent (use your own by googling 'whats my user agent') and try that way.

**Comment by rubenfaria** [comment]
> 
> 
> @rubenfaria what does chromium show?

![image](https://user-images.githubusercontent.com/28407098/68730563-cae87580-05ab-11ea-8bab-a1d5a6800a56.png)

**Comment by rubenfaria** [comment]
> 
> 
> Looks like both of you are running windows. I'm on mac right now, can you try using a custom user agent (use your own by googling 'whats my user agent') and try that way.

Same thing as before.
![image](https://user-images.githubusercontent.com/28407098/68730664-274b9500-05ac-11ea-9f4d-4160ad176a21.png)

**Comment by rubenfaria** [comment]
It must be a windows thing.
I deployed the sample project on Heroku with:
"session",
{ headless: true },
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3882.0 Safari/537.36"
![image](https://user-images.githubusercontent.com/28407098/68732094-00dc2880-05b1-11ea-9272-4f754b4faea0.png)

**Comment by rubenfaria** [comment]
It must be a Windows thing.
I deployed the same sample project usin a custom user agent to Heroku and it ran just fine.

"session",
{ headless: true },
"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3882.0 Safari/537.36"

![image](https://user-images.githubusercontent.com/28407098/68732352-e35b8e80-05b1-11ea-9cdd-a3c5c8f38aad.png)

**Comment by smashah** [comment]
I guess it messes up because you have a safari user agent on a Windows device. Try locally without the safari at the end or just use your own user agent as I described above.

**Comment by rubenfaria** [comment]
> 
> 
> I guess it messes up because you have a safari user agent on a Windows device. Try locally without the safari at the end or just use your own user agent as I described above.

I did. That one above I got from Chromium. I also tried Mozilla's, Edge's and Chrome's. For now I'm gonna work on this project using Linux. I'll get back to you telling whether anything went well in there. Thanks for your help.

**Comment by smashah** [comment]
I'm going to close this issue for now, thanks.
