### ISSUE TITLE
Hanging on Initializing whatsapp

### ISSUE THREAD

**Issue by ramonck** [smashah/sulla#90]
√ Initializing whatsapp
```
Debug Info {
  WA_VERSION: '0.4.612',
  PAGE_UA: 'WhatsApp/0.4.607 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) ' +
    'AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 ' +
    'Safari/537.36',
  SULLA_HOTFIX_VERSION: '1.7.2',
  BROWSER_VERSION: 'Chrome/79.0.3945.0'
}
```
The issue is basically the session is already "opened" but after disconnecting on the terminal (ctrl+c) and trying to re-run to fetch the session again the second time it did work again fine. The third time it stopped working it's now just hanging and there's no TOS_Block issue for now I can see the normal screen in Whatsapp.

![image](https://user-images.githubusercontent.com/5229948/73747082-631e7280-4735-11ea-86ca-41cdcf370bac.png)

It seems there's some bug on recapturing the saved session.

OBS: Not sure if there's something to do with the downgrading the Puppeteer version.

**Comment by smashah** [comment]
@ramonck how many times has this happened? I've followed your steps for reproduction but unable to reproduce. Also, please next time can you use the issue template. It saves a lot of time.

**Comment by ramonck** [comment]
@smashah it's hapenning all the time and I noticed something weird too, it's combined with this situation of session invalid.
I tried fresh from another folder too from zero and it still persisted the issue

but then it resolves.. in headless:false I can see it's authenticating fine.. seems there's some bug somewhere on the steps, maybe it didn't wait for the promise were it need to wait a bit more. On headless:false I also noticed that the browser closed and re-opened in the past it would just stay open I believe it's due to the session invalid message, maybe it needs a little delay or the promise is waiting for the wrong thing.
![image](https://user-images.githubusercontent.com/5229948/73766333-a3d9b400-4754-11ea-827f-1201c053ea6a.png)

**Comment by smashah** [comment]
@ramonck please share your create code. The invalid session message is normal. Try again with latest version.

**Comment by rfscheidt** [comment]
I am using the last version and it is ok!

**Comment by ramonck** [comment]
sulla.create('session',
      { headless:false,
        whatsappUrl: 'https://web.whatsapp.com/accept?code=xxxxxxxxxxxx'
      }
      ).then(client => {start(client)});

**Comment by ramonck** [comment]
I tried fresh again new folder installed sulla-hotfix again and that session invalid happens again.

![image](https://user-images.githubusercontent.com/5229948/73769229-12b90c00-4759-11ea-9efd-1c1439f1e1f6.png)

Another thing I noticed too is that it takes a long while to go to the next step after the initializing whatsapp I can see in headless:false even the QRcode changing before going to the next step in the initializing phase.

**Comment by smashah** [comment]
@ramonck try without the whatsappUrl since that was a workaround for the TOS_BLOCKing. You shouldn't need to do that anymore

**Comment by ramonck** [comment]
I'm still getting that session invalid thing even taking out the url. I'm going to try fresh again in another folder and let you know.

**Comment by smashah** [comment]
Ok. The last thing I would suggest is to run with a chrome instance and using the new smartUserAgent function

https://github.com/smashah/sulla/blob/490e5472a1e5c7164831b117f959668f8f2b88de/src/utils/tools.ts#L6

**Comment by ramonck** [comment]
I'm just using the default UA now since the TOS block went await.
I just think the session thing is weird, it gives that error then it connects. It's almost like a boot after the first scan.

**Comment by smashah** [comment]
@ramonck I implemented the invalid session checker due to the fact that sometimes, when a user waits too long to scan the QR code (or when qr autorefresh is on), the session becomes invalid (i.e Store.Msg does not exist, which in turn results in `client.onMessage` not working). So it automatically restarts the browser & page and because it's already authenticated, it loads up properly the second time.

So it's a good thing that it restarts automatically because otherwise none of your code would work.

**Comment by ramonck** [comment]
let me see if it stops working on the new folder then if it doesn't stop working I will close the ticket, if it stops working again then it's a wacky behavior.

**Comment by ramonck** [comment]
I'm closing it because it's working fine now, maybe it was some crazy issue with the other folder or mixed versions I don't know. Seems to be ok for now, no further issues.
Thanks @smashah

**Comment by alishahlakhani** [comment]
This seems to be happening to me now. I can't debug too :/ any idea @ramonck on how to solve it?

**Comment by smashah** [comment]
@alishahlakhani delete node_modules, npm i, try again

**Comment by alishahlakhani** [comment]
@smashah it was an issue with Puppeteer. Solved it using [this](puppeteer/troubleshooting.md at master · puppeteer/puppeteer) or `sudo apt-get install gconf-service libasound2 libatk1.0-0 libatk-bridge2.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget`

**Comment by smashah** [comment]
Hmm interesting thanks for the solution @alishahlakhani
