### ISSUE TITLE
Same old story: TOS Blocked

### ISSUE THREAD

**Issue by mmc16** [smashah/sulla#92]
**Describe the bug**
I am still encountering this error... But this time I am trying to run sulla on a remote server. I cleaned the session data, tried different UA (I even used the new smartUserAgent), to no avail. On my local computer it works just fine.... (its OS is Manjaro).

**create() code**
This is the code you use to create the client. e.g
```javascript
const uaOverride = 'WhatsApp/2.16.352 Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36';

sulla.create(`sessionData/${req.params.sessioId}`, { executablePath: '/usr/bin/google-chrome'},uaOverride);
```

**Expected behavior**
Don't get blocked

**DEBUG INFO**
I tried this: (it worked on the local computer)
```
Debug Info { WA_VERSION: 'I think you have been TOS_BLOCKed',
  PAGE_UA:
   'WhatsApp/2.16.352 Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36',
  SULLA_HOTFIX_VERSION: '1.7.2',
  BROWSER_VERSION: 'HeadlessChrome/72.0.3626.121' }
Possilby TOS_BLOCKed

```
And this:
```
Debug Info { WA_VERSION: 'I think you have been TOS_BLOCKed',
  PAGE_UA:
   'WhatsApp/2.16.352 Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/72.0.3626.121 Safari/537.36',
  SULLA_HOTFIX_VERSION: '1.7.2',
  BROWSER_VERSION: 'HeadlessChrome/72.0.3626.121' }

```
And this: (I used the smartUserAgent function)
```
Debug Info { WA_VERSION: 'I think you have been TOS_BLOCKed',
  PAGE_UA:
   'WhatsApp/0.4.315 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36',
  SULLA_HOTFIX_VERSION: '1.7.2',
  BROWSER_VERSION: 'HeadlessChrome/72.0.3626.121' }


```

**Screenshots**
No screenshot, sorry

**Host (please complete the following information):**
 - OS: Debian GNU/Linux 10 (buster)

**Additional context**
That's it...

**Comment by smashah** [comment]
@mmc16 thanks for using the issue template and providing all context and details.

Can you vnc into the server and open WhatsApp web? My suspicion is that due to the fact it's in a cloud server, your IP is being blocked.  Who is the cloud provider?

Or it could be the fact that your browser version is 'HeadlessChrome'.

**Comment by mmc16** [comment]
Sooooo, just now I tried creating the session without all those parameters, just `sulla.create(`sessionData/${req.params.sessionId}`)`, and it worked....
Yeah, I should've tried this earlier.
