### ISSUE TITLE
Problem to use loadAndGetAllMessagesInChat method with big contact list

### ISSUE THREAD

**Issue by rfscheidt** [smashah/sulla#93]
I'm using the `loadAndGetAllMessagesInChat` method (as shown in the code below). When using on a cellphone with until 1000 contacts it works fine, however I have 40k contacts on my list. The method takes a long time to initialize the reading of the first contact (in general, do not work). Is there any way to improve the performance of this method? Thank's a lot!
```javascript
router.get("/msg/retrieve/saveallbyjsonitem/:ident/", function(req, res) {
        console.log('Disparando: + ' + req.params.ident);
        try {
            getEveryMessageInChat(req.params.ident);  
        }
        catch (e) {
            console.log("entering catch block");
            console.log(e);
            console.log("leaving catch block");
        }

        res.send('OK');
    });

    const getEveryMessageInChat = async chatId => {
        console.log('telephone: ' + chatId);
        const allMessages = await client.loadAndGetAllMessagesInChat(chatId, false, false);
        console.log(allMessages.length);

        for (var i = 0; i < allMessages.length; i++) {
            let item = {
                idmessage: allMessages[i].id,
                user: allMessages[i].from.user,
                serialized: allMessages[i].from._serialized,
                body : allMessages[i].body,
                datetime: allMessages[i].t
            };

            console.log(allMessages[i].id + ' - ' + i);
            var respSleep = sleep(50);
            ChatService.add(_.pickBy(item));

            if (i % 1000 === 0) {
                var respSleep2 = sleep(5000);
            }
        }
    }
```

**Comment by smashah** [comment]
@rfscheidt damn son! 40k! What the hell are you using this for?

With sulla-hotfix, the bottleneck will always be the browser session. There's nothing that can be done to make this any quicker. I would suggest making this operation some sort of background pub-sub-type process instead of a single function and then queue up these requests to stop your whole instance from freezing up.

**Comment by rfscheidt** [comment]
@smashah how can I queue up the call client.loadAndGetAllMessagesInChat method? is there a way to do this from the outside (in the method call)?

**Comment by smashah** [comment]
@rfscheidt you'll need to architect your API to respond with something like `your request is in the queue` then add the job `getEveryMessageInChat` into a properly configured [promise queue](https://github.com/sindresorhus/p-queue) then once it's done you'll need to inform that user that the process has been completed and respond with the actual data.

One possible solution would be to filter the messages by type==chat

e.g

```javascript
...

    const getEveryMessageInChat = async chatId => {
        console.log('telephone: ' + chatId);
        const msgs = await client.loadAndGetAllMessagesInChat(chatId, false, false);
        const allMessages = msgs.filter(x=>x.type==='chat')
        console.log(allMessages.length);
...
```

That way you save time processing media.

**Comment by rfscheidt** [comment]
But I know that freezing up in the part  client.loadAndGetAllMessagesInChat(chatId, false, false).

**Comment by smashah** [comment]
@rfscheidt yes, that will remain the bottleneck, my suggestion at the end of the last comment was to improve speed and efficiency in other areas. Regarding the rest of my comment:
[![](https://mermaid.ink/img/eyJjb2RlIjoic2VxdWVuY2VEaWFncmFtXG5cdENsaWVudC0-PitBcHA6IFwiL21zZy9yZXRyaWV2ZS9zYXZlYWxsYnlqc29uaXRlbS9cIlxuXHRBcHAtLT4-UXVldWU6IEFkZHMgcmVxdWVzdCB0byBxdWV1ZVxuXHRBcHAtPj5DbGllbnQ6IFlvdXIgcmVxdWVzdCBpcyBpbiB0aGUgcXVldWVcbiAgUXVldWUtLT4-QXBwOiBkYXRhXG4gIEFwcC0-Pi1DbGllbnQ6IGRhdGEiLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9LCJ1cGRhdGVFZGl0b3IiOmZhbHNlfQ)](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoic2VxdWVuY2VEaWFncmFtXG5cdENsaWVudC0-PitBcHA6IFwiL21zZy9yZXRyaWV2ZS9zYXZlYWxsYnlqc29uaXRlbS9cIlxuXHRBcHAtLT4-UXVldWU6IEFkZHMgcmVxdWVzdCB0byBxdWV1ZVxuXHRBcHAtPj5DbGllbnQ6IFlvdXIgcmVxdWVzdCBpcyBpbiB0aGUgcXVldWVcbiAgUXVldWUtLT4-QXBwOiBkYXRhXG4gIEFwcC0-Pi1DbGllbnQ6IGRhdGEiLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9LCJ1cGRhdGVFZGl0b3IiOmZhbHNlfQ)

**Comment by rfscheidt** [comment]
I tried several ways to parallelize the call, but freezing up the method "const msgs = await client.loadAndGetAllMessagesInChat (chatId, false, false)";

I have a lot of contacts (40k) it looks like tries to load everything before loading just this record (chatId).

**Comment by ramonck** [comment]
> I tried several ways to parallelize the call, but freezing up the method "const msgs = await client.loadAndGetAllMessagesInChat (chatId, false, false)";
> 
> I have a lot of contacts (40k) it looks like tries to load everything before loading just this record (chatId).

I agree with @smashah I think if you work on queues it should be the best approach to optimize.

Another idea too can be with an async function you can use a for await, make sure that you have the "chunk" give it some breathing room with timeout or whatever then continue.

You need to free up memory and then continue, that should be the path.

**Comment by smashah** [comment]
Closing for now. Thanks
