### ISSUE TITLE
Method reply fires onAnyMessage several times

### ISSUE THREAD

**Issue by algoz098** [smashah/sulla#96]
**Describe the bug**
When have a onAnyMessage listenner, and send a reply it fires the event several times

**Steps to Reproduce**
1. Create a sulla basic setup
2. Set a function for onAnyMessage
3. Use the Reply function to send a reply to anything
It will fire the onAnyMessage more than 1 time

**create() code**
global.sender = await sulla.create(session, options);
global.sender.onAnyMessage(async message => {
		console.log('any message!')
})
 await global.sender.sendText(req.body.to, req.body.body);
```

**Expected behavior**
It should fire only one time the onAnyMessage

**DEBUG INFO**
This is the info printed to the console when you start your app. It should look like this
```
Debug Info {
6|3001   |   WA_VERSION: '0.4.612',
6|3001   |   PAGE_UA: 'WhatsApp/0.4.607 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36',
6|3001   |   SULLA_HOTFIX_VERSION: '1.7.5',
6|3001   |   BROWSER_VERSION: 'Chrome/79.0.3945.0'
6|3001   | }
```

**Screenshots**
If applicable, add screenshots to help explain your problem. Use ```headless: false``` to get screenshots

**Host (please complete the following information):**
 - Mac OS Catalina

**Additional context**

**Comment by smashah** [comment]
This is expected behaviour and by design as it is supposed to be a raw listener. You will need to implement a debouncer yourself. Although I will accept any PRs for a new listener with the functionality you are expecting.
