### ISSUE TITLE
Force close puppeteer session browser

### ISSUE THREAD

**Issue by GENL** [smashah/sulla#97]
Can you implement a simple way to close the browser of a session handled by puppeteer?,

**Comment by smashah** [comment]
https://github.com/smashah/sulla/blob/master/README.md#kill-the-session

**Comment by GENL** [comment]
> https://github.com/smashah/sulla/blob/master/README.md#kill-the-session

That not exaclty the same. I mean closing the browser directly with puppeteer, when the client instance is not already created. For example when the qr has not been scanned yet. The KILL method only works with an existing whatsapp client instance

**Comment by GENL** [comment]
I mean something like `sulla.create('sessionId', {closeSessionBrowserIfLaunched = true})` to create a whatsapp client instance with a new fresh browser to avoid about:blank when calling sulla.create twice when we don't have a whatsapp client instance yet.

**Comment by smashah** [comment]
@GENL why would you call create twice with the same sessionid?

**Comment by GENL** [comment]
I need it especially when I haven't scanned the qr code in time. Instead of restarting the server, I just set up an endpoint which I call to request another qr code (sulla.create). The second time I call the endpoint, "about: blank" is open because the session browser is already open. The solution is to close the current open browser for this session and open a new one.

**Comment by smashah** [comment]
Ok good idea

**Comment by joaomirandasa** [comment]
@GENL Amazing idea, did you already try code this?! If yes, please post for us help or collab. 

Thank you, nice idea! Following the issue.

**Comment by smashah** [comment]
> I need it especially when I haven't scanned the qr code in time. Instead of restarting the server, I just set up an endpoint which I call to request another qr code (sulla.create). The second time I call the endpoint, "about: blank" is open because the session browser is already open. The solution is to close the current open browser for this session and open a new one,

hold on a second, you can use QR auto-refresh for this.

**Comment by GENL** [comment]
> > I need it especially when I haven't scanned the qr code in time. Instead of restarting the server, I just set up an endpoint which I call to request another qr code (sulla.create). The second time I call the endpoint, "about: blank" is open because the session browser is already open. The solution is to close the current open browser for this session and open a new one,
> 
> hold on a second, you can use QR auto-refresh for this.

Yes, I tried, but it's fast, it generates too much qr code until you scan one, so the listener method is called several times so too many qr images are saved. In production, chrome is headless, so I think it's always a good idea to be able to close an unused browser session that was open.

**Comment by smashah** [comment]
@GENL why don't you just keep overriding the same file? You can also set the frequency for the refresh.

I've tried running the demo script twice but there's no way for puppeteer to know whether or not a session exists already after running puppeteer.launch() unless it crashes. When it does crash you can't really shut down the browser since it doesn't exist really.

The best solution to this would be to implement some sort of kill timer i.e if a qr code isn't scanned within X seconds, kill the browser.

**Comment by GENL** [comment]
Ok for a timer. It's an alternative that can do the trick.

**Comment by smashah** [comment]
@GENL in v1.7.6 you set a killTimer now:

https://github.com/smashah/sulla/blob/26b7b403dd7a3711f77c9762eb620160c3ec97ee/demo/index.ts#L122

let me know if this works for you.

thanks

**Comment by GENL** [comment]
Thanks for this implementation.
It's a shame that it is not possible to close a session on the fly before the whatsapp session.
Is this can be possible if sulla-hotfix expose the puppeteer browser instance just after it launches through a callback. I mean something like: `sulla.create ('sessionId', {}, onBrowserLaunched: (browser) => / * So I can get this browser instance, store it in a global variable and then use it to close the browser on another API request before creating the new session. * /) `

**Comment by haroldorodsilva** [comment]
@smashah  How can I treat and get the error of killtime?

Session timed out. Shutting down
(node:6388) UnhandledPromiseRejectionWarning: Error: QR Timeout      
    at D:\Projetos\Node\sulla_teste\node_modules\sulla-hotfix\dist\controllers\initializer.js:146:27

**Comment by smashah** [comment]
@haroldorodsilva add catch to your create code.

https://github.com/smashah/sulla/blob/7dcf40146c88a23c282b39641f97edaabda20e99/demo/index.ts#L128

@GENL sulla-hotfix doesn't have visibility onto your set up so you will have to set it up yourself. The killtimer should work for your needs for now.

**Comment by GENL** [comment]
@smashah  Thanks for your help and your time.
